(define (check . args)
  (let* ((two? (= (length args) 2))
         (label (if two? "check" (car args)))
         (actual (if two? (car args) (cadr args)))
         (expected (if two? (cadr args) (caddr args))))
    (if (equal? actual expected)
        (begin (display "[PASS] ") (display label) (newline))
        (begin (display "[FAIL] ") (display label)
               (display "  expected: ") (display expected)
               (display "  actual: ") (display actual) (newline)))))


(define (dv-sum p) (+ (car p) (cdr p)))
(define (dv-check label n d)
  (let ((fq (floor-quotient n d)) (fr (floor-remainder n d))
        (tq (truncate-quotient n d)) (tr (truncate-remainder n d)))
    (check (string-append label " floor-div") (floor-div n d) fq)
    (check (string-append label " floor-mod") (floor-mod n d) fr)
    (check (string-append label " floor/") (dv-sum (floor/ n d)) (+ fq fr))
    (check (string-append label " truncate/") (dv-sum (truncate/ n d)) (+ tq tr))
    (check (string-append label " ceiling-div") (ceiling-div n d) (ceiling-quotient n d))
    (check (string-append label " ceiling-rem") (ceiling-rem n d) (ceiling-remainder n d))
    (check (string-append label " round-div") (round-div n d) (round-quotient n d))
    (check (string-append label " euclidean-div") (euclidean-div n d) (euclidean-quotient n d))
    (check (string-append label " euclidean-rem") (euclidean-rem n d) (euclidean-remainder n d))))
(dv-check "7/3" 7 3)
(dv-check "-7/3" -7 3)
(dv-check "7/-3" 7 -3)
(dv-check "frac" 7/3 2/3)
(dv-check "negative-frac" -7/3 2/3)
(dv-check "negative-divisor-frac" 7/3 -2/3)
