(define (atom? x) (not (pair? x)))
(define void-sentinel (void))
(define (void? x) (eq? x void-sentinel))
(define nil '())
(define (my-macro-expand expr env) (my-macro-expand-helper expr env))
(define (my-macro-expand-helper expr env) (if (pair? expr) (if (eq? (car expr) 'quote) expr (if (eq? (car expr) 'quasiquote) expr ((lambda (expanded) (if (eq? expanded #f) (cons (my-macro-expand (car expr) env) (my-macro-expand (cdr expr) env)) (my-macro-expand-helper expanded env))) (sx-expand-call expr env)))) expr)) 
(define (my-bind-pattern pattern args) (if (symbol? pattern) (begin (if (eq? pattern (quote _)) (quote ()) (list (cons pattern args)))) (if (not (pair? pattern)) (begin (quote ())) (if (null? pattern) (begin (quote ())) (begin (append (my-bind-elem (car pattern) (car args)) (my-bind-pattern (cdr pattern) (cdr args))))))))
(define (my-bind-elem elem arg) (if (eq? elem (quote _)) (begin (quote ())) (if (symbol? elem) (begin (list (cons elem arg))) (if (if (pair? elem) (if (symbol? (car elem)) (null? (cdr elem)) #f) #f) (begin (list (cons (car elem) arg))) (if (pair? elem) (begin (my-bind-pattern elem arg)) (begin (quote ())))))))
(define (sx-macro-expand pattern body args callenv) ((lambda (bindings) ((lambda (app-form) (begin (eval app-form callenv))) (cons (cons (quote lambda) (cons (map (lambda (b) (car b)) bindings) body)) (map (lambda (b) (list (quote quote) (cdr b))) bindings)))) (my-bind-pattern pattern args)))
(define (my-definemacro name-pat . body) ((lambda (name pat) (sx-defmacro name (quote args) (list (list (quote sx-macro-expand) (list (quote quote) pat) (list (quote quote) body) (quote args) (quote (sx-expand-env)))) (sx-expand-env))) (car name-pat) (cdr name-pat)))
(my-definemacro '(define-macro name-pat . dm-body) '(cons 'my-definemacro (cons (list 'quote name-pat) (map (lambda (b) (list 'quote b)) dm-body))))
(define (qq-reverse-helper src dst) (if (null? src) dst (qq-reverse-helper (cdr src) (cons (car src) dst))))
(define (qq-reverse l) (qq-reverse-helper l (quote ())))
(define (qq-append-lists a b) (if (null? a) b (cons (car a) (qq-append-lists (cdr a) b))))
(define (qq-build-list items tail) (if (null? items) tail (qq-build-list (cdr items) (cons (car items) tail))))
(define (qq-unquote? x) (if (pair? x) (eq? (car x) (quote unquote)) #f))
(define (qq-unsplice? x) (if (pair? x) (eq? (car x) (quote unquote-splicing)) #f))
(define (qq-tail-unquote? tail) (if (pair? tail) (eq? (car tail) (quote unquote)) #f))
(define (qq-tail-unsplice? tail) (if (pair? tail) (eq? (car tail) (quote unquote-splicing)) #f))
(define (qq-process-el el items env) (if (qq-unquote? el) (cons (eval (cadr el) env) items) (if (qq-unsplice? el) ((lambda (v) (if (pair? v) (qq-append-lists (qq-reverse v) items) (if (null? v) items (cons v items)))) (eval (cadr el) env)) (if (pair? el) (if (eq? (car el) 'quasiquote) (cons el items) (cons (qq-walk el env) items)) (cons (qq-walk el env) items)))))
(define (qq-walk-list-helper cur items env) (if (null? cur) (begin (qq-reverse items)) (if (not (pair? cur)) (begin (qq-build-list (qq-reverse items) cur)) (begin ((lambda (new-items tail) (if (qq-tail-unquote? tail) (begin ((lambda (v) (qq-build-list (qq-reverse new-items) v)) (eval (cadr tail) env))) (if (qq-tail-unsplice? tail) (begin ((lambda (v) (qq-walk-list-helper tail (if (pair? v) (begin (qq-append-lists (qq-reverse v) new-items)) (if (null? v) (begin new-items) (begin (cons v new-items)))) env)) (eval (cadr tail) env))) (begin (qq-walk-list-helper tail new-items env))))) (qq-process-el (car cur) items env) (cdr cur))))))
(define (qq-walk-list e env) (qq-walk-list-helper e (quote ()) env))
(define (qq-walk-vector-helper cur items env) (if (null? cur) (list->vector (qq-reverse items)) ((lambda (el) (if (qq-unquote? el) (begin (qq-walk-vector-helper (cdr cur) (cons (eval (cadr el) env) items) env)) (if (qq-unsplice? el) (begin ((lambda (v) (if (pair? v) (begin (qq-walk-vector-helper (cdr cur) (qq-append-lists (qq-reverse v) items) env)) (if (null? v) (begin (qq-walk-vector-helper (cdr cur) items env)) (begin (qq-walk-vector-helper (cdr cur) (cons v items) env))))) (eval (cadr el) env))) (begin (qq-walk-vector-helper (cdr cur) (cons (qq-walk el env) items) env))))) (car cur))))
(define (qq-walk-vector v env) (qq-walk-vector-helper (vector->list v) (quote ()) env))
(define (qq-walk e env) (if (pair? e) (begin (qq-walk-list e env)) (if (vector? e) (begin (qq-walk-vector e env)) (begin e))))
(define (sx-lookup var bindings) ((lambda (b) (if b (cdr b) #f)) (assq var bindings)))
(define (sx-merge-bindings b1 b2) (append b2 b1))
(define (sx-rev-append src acc) (if (null? src) acc (sx-rev-append (cdr src) (cons (car src) acc))))
(define (sx-reverse l) (sx-rev-append l (quote ())))
(define (sx-pattern-vars pat) (sx-reverse (sx-pattern-vars-loop (list pat) (quote ()))))
(define (sx-pattern-vars-loop stack acc) (if (null? stack) acc ((lambda (curr) (if (symbol? curr) (begin (if (eqv? curr (quote _)) (begin (sx-pattern-vars-loop (cdr stack) acc)) (if (eqv? curr (quote ...)) (begin (sx-pattern-vars-loop (cdr stack) acc)) (begin (sx-pattern-vars-loop (cdr stack) (cons curr acc)))))) (if (pair? curr) (begin (sx-pattern-vars-loop (cons (car curr) (cons (cdr curr) (cdr stack))) acc)) (begin (sx-pattern-vars-loop (cdr stack) acc))))) (car stack))))
(define (sx-merge-vars a b) (if (null? b) (begin a) (if (memq (car b) a) (begin (sx-merge-vars a (cdr b))) (begin (sx-merge-vars (cons (car b) a) (cdr b))))))
(define (sx-accum-ellipsis vars groups base) (if (null? vars) base ((lambda (v vals) (sx-merge-bindings (cons (cons v (sx-rev-append vals (quote ()))) (quote ())) (sx-accum-ellipsis (cdr vars) groups base))) (car vars) (map (lambda (g) (sx-lookup (car vars) g)) groups))))
(define (sx-match pat inp lits) (if (null? pat) (begin (if (null? inp) (quote ()) #f)) (if (symbol? pat) (begin (sx-match-sym pat inp lits)) (if (not (pair? pat)) (begin (if (equal? pat inp) (quote ()) #f)) (if (pair? (cdr pat)) (begin (if (eq? (cadr pat) (quote ...)) (sx-match-ellipsis (car pat) (cddr pat) inp lits) (sx-match-pair pat inp lits))) (begin (sx-match-pair pat inp lits)))))))
(define (sx-match-sym pat inp lits) (if (eq? pat (quote _)) (begin (quote ())) (if (memq pat lits) (begin (if (if (symbol? inp) (eq? pat inp) #f) (quote ()) #f)) (begin (list (cons pat inp))))))
(define (sx-match-pair pat inp lits) (if (pair? inp) ((lambda (b1) (if (not b1) #f ((lambda (b2) (if (not b2) #f (sx-merge-bindings b1 b2))) (sx-match (cdr pat) (cdr inp) lits)))) (sx-match (car pat) (car inp) lits)) #f))
(define (sx-match-ellipsis prefix rest-pat inp lits) ((lambda (res) (sx-match-ellipsis-finish prefix rest-pat res lits)) (sx-match-ellipsis-loop prefix rest-pat inp lits (quote ()))))
(define (sx-match-ellipsis-finish prefix rest-pat res lits) ((lambda (in groups evars) (if (null? rest-pat) (if (null? in) (sx-accum-ellipsis evars groups (quote ())) #f) ((lambda (rb) (if rb (sx-accum-ellipsis evars groups rb) #f)) (sx-match rest-pat in lits)))) (car res) (cdr res) (sx-pattern-vars prefix)))
(define (sx-match-ellipsis-loop prefix rest-pat in lits groups) (if (not (pair? in)) (cons in groups) ((lambda (b) (if b (if (null? rest-pat) (begin (sx-match-ellipsis-loop prefix rest-pat (cdr in) lits (cons b groups))) (if (sx-match rest-pat in lits) (begin (cons in groups)) (begin (sx-match-ellipsis-loop prefix rest-pat (cdr in) lits (cons b groups))))) (cons in groups))) (sx-match prefix (car in) lits))))
(define (sx-expand tmpl bindings) (if (symbol? tmpl) (begin (sx-expand-sym tmpl bindings)) (if (not (pair? tmpl)) (begin tmpl) (if (pair? (cdr tmpl)) (begin (if (eq? (cadr tmpl) (quote ...)) (sx-expand-ellipsis (car tmpl) (cddr tmpl) bindings) (sx-expand-pair tmpl bindings))) (begin (sx-expand-pair tmpl bindings))))))
(define *sx-mutated-vars* '())
(define (sx-collect-set-targets tmpl acc) (if (not (pair? tmpl)) (begin acc) (if (eq? (car tmpl) (quote set!)) (begin (if (if (pair? (cdr tmpl)) (symbol? (cadr tmpl)) #f) (sx-collect-set-targets (cdr tmpl) (cons (cadr tmpl) acc)) (sx-collect-set-targets (cdr tmpl) acc))) (begin (sx-collect-set-targets (car tmpl) (sx-collect-set-targets (cdr tmpl) acc))))))
(define (sx-expand-sym tmpl bindings) ((lambda (p) (if p (cdr p) (if (if (not (eq? tmpl (quote _))) (if (not (eq? tmpl (quote ...))) (if (not (memq tmpl *sx-mutated-vars*)) (if (sx-defined? tmpl (sx-def-env)) (not (procedure? (eval tmpl (sx-def-env)))) #f) #f) #f) #f) (list (quote sx-hygiene) tmpl) tmpl))) (assq tmpl bindings)))
(define (sx-expand-pair tmpl bindings) (cons (sx-expand (car tmpl) bindings) (sx-expand (cdr tmpl) bindings)))
(define (sx-expand-ellipsis sub rest bindings) ((lambda (evars) (if (null? evars) (sx-expand-ellipsis-novar sub rest bindings) (sx-expand-ellipsis-var sub rest bindings evars))) (sx-ellipsis-vars sub bindings)))
(define (sx-expand-ellipsis-novar sub rest bindings) (sx-repeat sub rest bindings #f (sx-find-list-count bindings)))
(define (sx-expand-ellipsis-var sub rest bindings evars) (sx-repeat sub rest bindings evars (length (cdr (assq (car evars) bindings)))))
(define (sx-repeat sub rest bindings evars cnt) (sx-repeat-helper sub rest bindings evars (- cnt 1) (sx-expand rest bindings)))
(define (sx-repeat-helper sub rest bindings evars i res) (if (< i 0) res (sx-repeat-helper sub rest bindings evars (- i 1) (cons (if evars (sx-expand sub (sx-sub-bindings evars bindings i)) (sx-expand sub bindings)) res))))
(define (sx-ellipsis-vars sub bindings) (filter (lambda (v) ((lambda (p) (if p ((lambda (__or_temp) (if __or_temp __or_temp (null? (cdr p)))) (pair? (cdr p))) #f)) (assq v bindings))) (sx-pattern-vars sub)))
(define (sx-find-list-count bindings) (if (null? bindings) 0 ((lambda (v) (if (pair? v) (length v) (sx-find-list-count (cdr bindings)))) (cdar bindings))))
(define (sx-sub-bindings evars bindings i) (if (null? evars) (quote ()) (cons (sx-sub-bindings-cons (car evars) bindings i) (sx-sub-bindings (cdr evars) bindings i))))
(define (sx-sub-bindings-cons v bindings i) ((lambda (lst) (cons v (if (< i (length lst)) (list-ref lst i) (quote ())))) (cdr (assq v bindings))))
(define (sx-dispatch args lits rules) (if (null? rules) (error "syntax-rules: no match") ((lambda (rule) ((lambda (pat) ((lambda (tmpl) ((lambda (pat-args) ((lambda (b) (begin (if b ((lambda (old-mut) (set! *sx-mutated-vars* (sx-collect-set-targets tmpl (quote ()))) ((lambda (r) (set! *sx-mutated-vars* old-mut) r) (sx-expand tmpl b))) *sx-mutated-vars*) (sx-dispatch args lits (cdr rules))))) (sx-match pat-args args lits))) (if (pair? pat) (cdr pat) (quote ())))) (if (pair? rule) (sx-rule-tmpl rule) (quote ())))) (if (pair? rule) (car rule) (quote ())))) (car rules))))
(define (sx-rule-tmpl rule) (if (pair? (cdr rule)) (cadr rule) (quote ())))
(define *sx-bindings* '())
(define (sx-get-bindings) *sx-bindings*)
(define (sx-set-bindings! b) (set! *sx-bindings* b))
(define (sx-with-bindings b thunk) ((lambda (old) (sx-set-bindings! b) ((lambda (r) (sx-set-bindings! old) r) (thunk))) *sx-bindings*))
(define *sx-gensym-counter* 0)
(define (sx-gensym)  (set! *sx-gensym-counter* (+ *sx-gensym-counter* 1)) (string->symbol (string-append "__t" (number->string *sx-gensym-counter*))))
(define (qs-unquote? x) (if (pair? x) (eq? (car x) (quote unsyntax)) #f))
(define (qs-unsplice? x) (if (pair? x) (eq? (car x) (quote unsyntax-splicing)) #f))
(define (qs-walk-list cur) (if (null? cur) (begin (quote ())) (if (not (pair? cur)) (begin (qs-expand cur)) (if (qs-unsplice? (car cur)) (begin ((lambda (v) (qq-append-lists (qq-reverse v) (qs-walk-list (cdr cur)))) (eval (cadr (car cur)) (sx-expand-env)))) (if (qs-unquote? (car cur)) (begin (cons (eval (cadr (car cur)) (sx-expand-env)) (qs-walk-list (cdr cur)))) (begin (cons (qs-expand (car cur)) (qs-walk-list (cdr cur)))))))))
(define (qs-expand x) (if (symbol? x) (begin (sx-expand-sym x (sx-get-bindings))) (if (not (pair? x)) (begin x) (if (qs-unquote? x) (begin (eval (cadr x) (sx-expand-env))) (if (qs-unsplice? x) (begin (eval (cadr x) (sx-expand-env))) (if (eq? (car x) (quote quasisyntax)) (begin x) (begin (qs-walk-list x))))))))
(define (sx-gen-temps lst) ((lambda (loop) (set! loop (lambda (n acc) (if (= n 0) acc (loop (- n 1) (cons (sx-gensym) acc))))) (begin (loop (length lst) (quote ())))) #f))
(define (sx-syntax-case expr lits clauses) ((lambda (datum) ((lambda (cl) ((lambda (rest-cl) ((lambda (pat) ((lambda (has-fender) ((lambda (fender) ((lambda (tmpl) ((lambda (b) (begin (if (null? clauses) (begin (error "syntax-case: no match")) (if b (begin (if ((lambda (__or_temp) (if __or_temp __or_temp (sx-check-fender fender b))) (not has-fender)) (sx-eval-tmpl tmpl b) (sx-syntax-case datum lits (cdr clauses)))) (begin (sx-syntax-case datum lits (cdr clauses))))))) (sx-match pat datum lits))) (if has-fender (cadr rest-cl) (car rest-cl)))) (if has-fender (car rest-cl) #f))) (if (pair? rest-cl) (pair? (cdr rest-cl)) #f))) (car cl))) (cdr cl))) (car clauses))) expr))
(define (sx-check-fender fender b) (sx-with-bindings b (lambda () (not (eq? (eval fender (sx-expand-env)) #f)))))
(define (sx-eval-tmpl tmpl b) (sx-with-bindings b (lambda () ((lambda (r) (if (symbol? r) (list (quote quote) r) r)) (eval tmpl (sx-expand-env))))))
(define (sx-with-syntax pairs body) ((lambda (loop) (set! loop (lambda (ps acc) (if (null? ps) (sx-with-bindings (sx-merge-bindings acc (sx-get-bindings)) (lambda () (sx-eval-body body (sx-expand-env)))) ((lambda (p) ((lambda (pat) ((lambda (val) ((lambda (b) (begin (if b (loop (cdr ps) (sx-merge-bindings acc b)) (error "with-syntax: no match")))) (sx-match pat val (quote ())))) (cadar ps))) (caar ps))) (car ps))))) (begin (loop pairs (quote ())))) #f))
(define (sx-eval-body body env) (if (null? body) (void) ((lambda (last) (for-each (lambda (form) (set! last (eval form env))) body) last) (void))))
(define (sx-let-syntax bindings body) (list (cons (quote lambda) (cons (quote ()) (append (map sx-make-macro-binding bindings) body)))))
(define (sx-make-macro-binding binding) ((lambda (name trans) (if (if (pair? trans) (eq? (car trans) (quote syntax-rules)) #f) ((lambda (lits rules) (list (quote define-macro) (cons name (quote args)) (list (quote sx-dispatch) (quote args) (list (quote quote) lits) (list (quote quote) rules)))) (if (pair? (cdr trans)) (cadr trans) (quote ())) (cddr trans)) (list (quote define-macro) (cons name (quote args)) (list (cons (quote lambda) (cdr trans)) (list (quote cons) (list (quote quote) name) (quote args)))))) (car binding) (cadr binding)))
(define-macro (quasiquote e) (list 'quote (qq-walk e (the-environment))))
(define-macro (syntax tmpl) (list 'quote (sx-expand tmpl (sx-get-bindings))))
(define-macro (quasisyntax tmpl) (list 'quote (qs-expand tmpl)))
(define-macro (generate-temporaries lst) (list 'sx-gen-temps lst))
(define-macro (syntax-case . args) ((lambda (expr lits clauses) (list 'sx-syntax-case expr (list 'quote lits) (list 'quote clauses))) (car args) (cadr args) (cddr args)))
(define-macro (with-syntax . args) ((lambda (bindings body) (list 'sx-with-syntax (cons 'list (map (lambda (b) (list 'list (list 'quote (car b)) (cadr b))) bindings)) (list 'quote body))) (car args) (cdr args)))
(define-macro (let-syntax . args) (sx-let-syntax (car args) (cdr args)))
(define-macro (letrec-syntax . args) (sx-let-syntax (car args) (cdr args)))
(define-macro (define-syntax name trans) (sx-make-macro-binding (list name trans)))

(display "=== boot-min2.scm 加载完成 ===\n")
(newline)
