(define (my-definemacro name-pat . body) ((lambda (name pat) (sx-defmacro name (quote args) (list (list (quote sx-macro-expand) (list (quote quote) pat) (list (quote quote) body) (quote args) (quote (sx-expand-env)))) (sx-expand-env))) (car name-pat) (cdr name-pat)))
(my-definemacro '(define-macro name-pat . dm-body) '(cons 'my-definemacro (cons (list 'quote name-pat) (map (lambda (b) (list 'quote b)) dm-body))))
(define-macro (quasiquote _e) (list 'quote (qq-walk _e (the-environment))))
(define-macro (syntax tmpl) (list 'quote (sx-expand tmpl (sx-get-bindings))))
(define-macro (quasisyntax tmpl) (list 'quote (qs-expand tmpl)))
(define-macro (generate-temporaries lst) (list 'sx-gen-temps lst))
(define-macro (syntax-case . args) ((lambda (expr lits clauses) (list 'sx-syntax-case expr (list 'quote lits) (list 'quote clauses))) (car args) (cadr args) (cddr args)))
(define-macro (with-syntax . args) ((lambda (bindings body) (list 'sx-with-syntax (cons 'list (map (lambda (b) (list 'list (list 'quote (car b)) (cadr b))) bindings)) (list 'quote body))) (car args) (cdr args)))
(define-macro (let-syntax . args) (sx-let-syntax (car args) (cdr args)))
(define-macro (letrec-syntax . args) (sx-let-syntax (car args) (cdr args)))
(define-macro (define-syntax name trans) (sx-make-macro-binding (list name trans)))
(newline)
