;; test-data-structures-edge.scm
;; Deep edge-case and stress tests for data-structures-ext.scm
;; Covers untested items + complex boundary scenarios.

(define (t-eq label actual expected)
  (if (equal? actual expected)
      (begin (display "[PASS] ") (display label) (newline))
      (begin (display "[FAIL] ") (display label)
             (display "  expected: ") (write expected)
             (display "  actual: ") (write actual) (newline))))

(display "=== fl<? fl<=? fl>=? (untested flonum predicates) ===\n")
(t-eq "fl<? true" (fl<? 1.0 2.0) #t)
(t-eq "fl<? false" (fl<? 3.0 2.0) #f)
(t-eq "fl<? equal" (fl<? 2.0 2.0) #f)
(t-eq "fl<=? less" (fl<=? 1.0 2.0) #t)
(t-eq "fl<=? equal" (fl<=? 2.0 2.0) #t)
(t-eq "fl<=? greater" (fl<=? 3.0 2.0) #f)
(t-eq "fl>=? greater" (fl>=? 3.0 2.0) #t)
(t-eq "fl>=? equal" (fl>=? 2.0 2.0) #t)
(t-eq "fl>=? less" (fl>=? 1.0 2.0) #f)

(display "=== char-set:punctuation (untested) ===\n")
(t-eq "punct contains !" (char-set-contains? char-set:punctuation #\!) #t)
(t-eq "punct contains ." (char-set-contains? char-set:punctuation #\.) #t)
(t-eq "punct not a" (char-set-contains? char-set:punctuation #\a) #f)
(t-eq "punct not digit" (char-set-contains? char-set:punctuation #\5) #f)
(t-eq "punct not space" (char-set-contains? char-set:punctuation #\space) #f)

(display "=== hash-table edge cases ===\n")
(define ht (make-eq-hash-table))
(t-eq "ht empty size" (hash-table-size ht) 0)
(hash-table-set! ht 'a 1)
(hash-table-set! ht 'b 2)
(hash-table-set! ht 'c 3)
(t-eq "ht size 3" (hash-table-size ht) 3)
(t-eq "ht exists a" (hash-table-exists? ht 'a) #t)
(t-eq "ht ref a" (hash-table-ref ht 'a) 1)
(t-eq "ht ref default" (hash-table-ref ht 'x 99) 99)
(hash-table-delete! ht 'b)
(t-eq "ht size after delete" (hash-table-size ht) 2)
(t-eq "ht exists deleted" (hash-table-exists? ht 'b) #f)
(hash-table-set! ht 'a 10)
(t-eq "ht update" (hash-table-ref ht 'a) 10)
(hash-table-set! ht 'b 'bvalue)
(t-eq "ht re-add" (hash-table-ref ht 'b) 'bvalue)
(define ht-keys (hash-table-keys ht))
(t-eq "ht keys" (length ht-keys) 3)
(define ht-vals (hash-table-values ht))
(t-eq "ht vals" (length ht-vals) 3)

;; equal hash table
(define eht (make-equal-hash-table))
(hash-table-set! eht 'list-key 'list-val)
(hash-table-set! eht "hello" 'str-val)
(t-eq "equal ht ref list" (hash-table-ref eht 'list-key) 'list-val)
(t-eq "equal ht ref str" (hash-table-ref eht "hello") 'str-val)
(t-eq "equal ht exists" (hash-table-exists? eht "hello") #t)

;; eqv hash table
(define vht (make-eqv-hash-table))
(hash-table-set! vht 42 'int-val)
(hash-table-set! vht 3.14 'float-val)
(t-eq "eqv ht int" (hash-table-ref vht 42) 'int-val)
(t-eq "eqv ht float" (hash-table-ref vht 3.14) 'float-val)

(display "=== <bimap> edge cases ===\n")
(define bm (make-bimap '((1 . a) (2 . b) (3 . c))))
(t-eq "bimap forward" (bimap-forward bm 1) 'a)
(t-eq "bimap forward 2" (bimap-forward bm 2) 'b)
(t-eq "bimap reverse" (bimap-reverse bm 'a) 1)
(t-eq "bimap reverse b" (bimap-reverse bm 'b) 2)
(define bm-empty (make-bimap '()))
(t-eq "bimap empty forward" (bimap-forward bm-empty 1) #f)
(t-eq "bimap empty reverse" (bimap-reverse bm-empty 'x) #f)
(define bm-single (make-bimap '((42 . answer))))
(t-eq "bimap single forward" (bimap-forward bm-single 42) 'answer)
(t-eq "bimap single reverse" (bimap-reverse bm-single 'answer) 42)

(display "=== <deque> edge cases ===\n")
(define dq (make-deque))
(t-eq "deque empty?" (deque-empty? dq) #t)
(deque-push-front! dq 1)
(deque-push-front! dq 2)
(deque-push-back! dq 3)
(deque-push-back! dq 4)
(t-eq "deque size 4" (deque-length dq) 4)
(t-eq "deque front" (deque-front dq) 2)
(t-eq "deque back" (deque-back dq) 4)
(define dq-list (deque->list dq))
(t-eq "deque->list" dq-list '(2 1 3 4))
(t-eq "deque pop-front" (deque-pop-front! dq) 2)
(t-eq "deque pop-back" (deque-pop-back! dq) 4)
(t-eq "deque size after pop" (deque-length dq) 2)

;; single element deque
(define dq1 (make-deque))
(deque-push-front! dq1 42)
(t-eq "deque single front" (deque-front dq1) 42)
(t-eq "deque single back" (deque-back dq1) 42)
(t-eq "deque single pop" (deque-pop-front! dq1) 42)
(t-eq "deque single empty after pop" (deque-empty? dq1) #t)

(display "=== <binary-heap> edge cases ===\n")
(define h (make-binary-heap <))
(binary-heap-insert! h 5)
(binary-heap-insert! h 3)
(binary-heap-insert! h 8)
(binary-heap-insert! h 1)
(binary-heap-insert! h 4)
(t-eq "heap size 5" (binary-heap-size h) 5)
(t-eq "heap min" (binary-heap-min h) 1)
(t-eq "heap delete-min 1" (binary-heap-delete-min! h) 1)
(t-eq "heap new min" (binary-heap-min h) 3)
(t-eq "heap delete-min 3" (binary-heap-delete-min! h) 3)
(t-eq "heap delete-min 4" (binary-heap-delete-min! h) 4)
(t-eq "heap delete-min 5" (binary-heap-delete-min! h) 5)
(t-eq "heap delete-min 8" (binary-heap-delete-min! h) 8)
(t-eq "heap empty" (binary-heap-empty? h) #t)

;; heap with duplicates
(define hd (make-binary-heap <))
(binary-heap-insert! hd 3)
(binary-heap-insert! hd 1)
(binary-heap-insert! hd 3)
(binary-heap-insert! hd 2)
(t-eq "heap dup min" (binary-heap-min hd) 1)
(binary-heap-delete-min! hd)
(t-eq "heap min after dup removal" (binary-heap-min hd) 2)

;; heap with custom comparator (max heap)
(define max-h (make-binary-heap >))
(binary-heap-insert! max-h 5)
(binary-heap-insert! max-h 9)
(binary-heap-insert! max-h 3)
(binary-heap-insert! max-h 7)
(t-eq "max-heap max" (binary-heap-min max-h) 9)

(display "=== <box> edge cases ===\n")
(define bx (make-box 42))
(t-eq "box unbox" (unbox bx) 42)
(set-box! bx 99)
(t-eq "box after set!" (unbox bx) 99)
(define bx-nil (make-box '()))
(t-eq "box nil" (unbox bx-nil) '())
(define bx-false (make-box #f))
(t-eq "box false" (unbox bx-false) #f)

(display "=== <list-queue> edge cases ===\n")
(define lq (make-list-queue '(1 2 3)))
(t-eq "lq front" (list-queue-front lq) 1)
(t-eq "lq back" (list-queue-back lq) 3)
(list-queue-remove-front! lq)
(t-eq "lq remove front" (list-queue-front lq) 2)
(list-queue-add-back! lq 4)
(t-eq "lq add back" (list-queue-back lq) 4)
(list-queue-remove-front! lq)
(list-queue-remove-front! lq)
(list-queue-remove-front! lq)
(t-eq "lq empty" (list-queue-empty? (make-list-queue '())) #t)

(display "=== <random-source> ===\n")
(define rs1 (make-random-source))
(random-source-randomize! rs1)
(define rs2 (make-random-source))
(random-source-randomize! rs2)
(let ((vals '()))
  (do ((i 0 (+ i 1))) ((= i 20))
    (set! vals (cons (random-source-random-integer rs1 100) vals)))
  (t-eq "random produces values" (pair? vals) #t)
  (t-eq "random in range" (every (λ (x) (and (>= x 0) (< x 100))) vals) #t))

(display "=== complex hash-table operations ===\n")
(define big-ht (make-eq-hash-table))
(do ((i 0 (+ i 1))) ((= i 100))
  (hash-table-set! big-ht (string->symbol (string-append "k" (number->string i))) i))
(t-eq "100 entries" (hash-table-size big-ht) 100)
(do ((i 0 (+ i 1))) ((= i 100))
  (hash-table-delete! big-ht (string->symbol (string-append "k" (number->string i)))))
(t-eq "all deleted" (hash-table-size big-ht) 0)

;; hash-table->alist / alist->hash-table round-trip
(define ht-alist '((a . 1) (b . 2) (c . 3)))
(define ht-from-alist (alist->hash-table ht-alist))
(t-eq "alist->ht size" (hash-table-size ht-from-alist) 3)
(t-eq "ht->alist roundtrip" (hash-table->alist ht-from-alist) ht-alist)
(define ht-copy (hash-table-copy ht-from-alist))
(t-eq "ht copy size" (hash-table-size ht-copy) 3)
(hash-table-set! ht-copy 'd 4)
(t-eq "ht copy independent" (hash-table-size ht-from-alist) 3)

(display "=== string-map edge cases (srfi-13) ===\n")
(t-eq "string-map empty" (string-map char-upcase "") "")
(t-eq "string-map identity" (string-map (λ (c) c) "abc") "abc")
(t-eq "string-map all up" (string-map char-upcase "hello") "HELLO")
(define cnt 0)
(string-for-each (λ (c) (set! cnt (+ cnt 1))) "abcde")
(t-eq "string-for-each count" cnt 5)
(string-for-each (λ (c) (set! cnt (+ cnt 1))) "")
(t-eq "string-for-each empty" cnt 5)

(display "=== complex srfi-1 list edges ===\n")
;; circular list edge cases
(define circ (circular-list 1 2 3))
(t-eq "circular-list? detected" (circular-list? circ) #t)
(t-eq "circular-list not in proper" (proper-list? circ) #f)
(t-eq "dotted-list?" (dotted-list? '(1 2 . 3)) #t)
(t-eq "proper-list? dotted" (proper-list? '(1 2 . 3)) #f)
(t-eq "proper-list? empty" (proper-list? '()) #t)
(t-eq "null-list? empty" (null-list? '()) #t)
(t-eq "null-list? pair" (null-list? '(1)) #f)

;; fold / fold-left consistency
(t-eq "fold-left additive" (fold-left + 0 '(1 2 3 4 5)) 15)
(t-eq "fold-left empty" (fold-left + 0 '()) 0)
(t-eq "fold-left string" (fold-left (λ (s c) (string-append s (string c))) "" '(#\a #\b #\c)) "abc")
(t-eq "fold-right additive" (fold-right + 0 '(1 2 3 4 5)) 15)
(t-eq "fold-right list" (fold-right cons '() '(1 2 3)) '(1 2 3))

;; take/drop edge cases
(t-eq "take none" (take '(a b c) 0) '())
(t-eq "take all" (take '(a b c) 3) '(a b c))
(t-eq "drop none" (drop '(a b c) 0) '(a b c))
(t-eq "drop all" (drop '(a b c) 3) '())
(t-eq "take-right" (take-right '(1 2 3 4) 2) '(3 4))
(t-eq "drop-right" (drop-right '(1 2 3 4) 2) '(1 2))

;; delete-duplicates
(t-eq "delete-duplicates none" (delete-duplicates '(1 2 3)) '(1 2 3))
(t-eq "delete-duplicates all same" (delete-duplicates '(1 1 1)) '(1))
(t-eq "delete-duplicates mixed" (delete-duplicates '(1 2 1 3 2 4)) '(1 2 3 4))

;; partition / span / break edge cases
(let-values (((l r) (partition even? '(1 2 3 4 5))))
  (t-eq "partition evens" l '(2 4))
  (t-eq "partition odds" r '(1 3 5)))
(let-values (((l r) (span (λ (x) (< x 3)) '(1 2 3 4 1 2))))
  (t-eq "span prefix" l '(1 2))
  (t-eq "span rest" r '(3 4 1 2)))
(let-values (((l r) (break (λ (x) (> x 2)) '(1 2 3 4 5))))
  (t-eq "break prefix" l '(1 2))
  (t-eq "break rest" r '(3 4 5)))

;; merge edge cases
(t-eq "merge both empty" (merge < '() '()) '())
(t-eq "merge one empty" (merge < '(1 2 3) '()) '(1 2 3))
(t-eq "merge other empty" (merge < '() '(4 5 6)) '(4 5 6))
(t-eq "merge interleaved" (merge < '(1 3 5) '(2 4 6)) '(1 2 3 4 5 6))
(t-eq "merge duplicates" (merge < '(1 2 3) '(2 3 4)) '(1 2 2 3 3 4))

(display "=== vector-map edge cases ===\n")
(t-eq "vector-map empty" (vector-map + '#() '#()) '#())
(t-eq "vector-map add" (vector-map + '#(1 2 3) '#(10 20 30)) '#(11 22 33))
(t-eq "vector-map square" (vector-map (λ (x) (* x x)) '#(1 2 3 4)) '#(1 4 9 16))
(define vm-res (vector-map cons '#(a b c) '#(1 2 3)))
(define vm-list (vector->list vm-res))
(t-eq "vector-map cons" (equal? vm-list '((a . 1) (b . 2) (c . 3))) #t)

(display "=== reverse! and sorted? edge cases ===\n")
(define r-lst (list 1 2 3))
(define r-res (reverse! r-lst))
(t-eq "reverse! empty" (reverse! '()) '())
(t-eq "reverse! single" (reverse! (list 1)) '(1))
(define r-lst3 (list 1 2 3))
(define r-r3 (reverse! r-lst3))
(t-eq "sorted? ascending" (sorted? < '(1 2 3 4 5)) #t)
(t-eq "sorted? descending" (sorted? > '(5 4 3 2 1)) #t)
(t-eq "sorted? not" (sorted? < '(1 3 2 4)) #f)
(t-eq "sorted? empty" (sorted? < '()) #t)
(t-eq "sorted? single" (sorted? < '(1)) #t)

(display "=== filter-map / flat-map ===\n")
(t-eq "filter-map all" (filter-map (λ (x) (* x 2)) '(1 2 3)) '(2 4 6))
(t-eq "filter-map some #f" (filter-map (λ (x) (if (even? x) (* x 2) #f)) '(1 2 3 4)) '(4 8))
(t-eq "filter-map empty" (filter-map (λ (x) #f) '(1 2 3)) '())
(t-eq "flat-map basic" (flat-map (λ (x) (list x (- x))) '(1 2 3)) '(1 -1 2 -2 3 -3))
(t-eq "flat-map empty" (flat-map (λ (x) '()) '(1 2 3)) '())
(t-eq "flat-map nested" (flat-map (λ (x) (if (even? x) (list x) '())) '(1 2 3 4)) '(2 4))

(display "=== alist operations ===\n")
(define al '((a . 1) (b . 2) (c . 3)))
(t-eq "alist-copy" (alist-copy al) al)
(define al2 (alist-cons 'd 4 al))
(t-eq "alist-cons" (assq 'd al2) '(d . 4))
(define al3 (alist-delete 'b al))
(t-eq "alist-delete" (assq 'b al3) #f)
(t-eq "alist-delete preserve rest" (length al3) 2)
(t-eq "alist-delete missing" (alist-delete 'x al) al)

(display "=== unfold / unfold-right ===\n")
(t-eq "unfold stop" (unfold (λ (x) (> x 5)) (λ (x) (* x 2)) (λ (x) (+ x 1)) 1) '(2 4 6 8 10))
(t-eq "unfold zero" (unfold (λ (x) #t) (λ (x) x) (λ (x) x) 42) '())
(t-eq "unfold-right" (unfold-right (λ (x) (> x 5)) (λ (x) (* x 2)) (λ (x) (+ x 1)) 1) '(10 8 6 4 2))

(display "=== iota edge cases ===\n")
(t-eq "iota 0" (iota 0) '())
(t-eq "iota 1" (iota 1) '(0))
(t-eq "iota with start" (iota 5 10) '(10 11 12 13 14))
(t-eq "iota with step" (iota 4 1 3) '(1 4 7 10))
(t-eq "iota negative step" (iota 3 5 -1) '(5 4 3))

(display "=== const identity edge cases ===\n")
(t-eq "const returns fn" (procedure? (const 42)) #t)
(t-eq "const ignores args" ((const 42) 1 2 3) 42)
(t-eq "const nil" ((const '()) 'anything) '())
(t-eq "identity" (identity 42) 42)
(t-eq "identity nil" (identity '()) '())

(display "\n;; === All data-structures edge tests complete ===\n")
