;; Functional tests for primitives (auto-generated)
(define *p* 0) (define *f* 0)
(define (te name)
  (if (not (eq? name (if #f #f)))
      (set! *p* (+ *p* 1))
      (begin (display "[FAIL] ") (display name) (newline)
             (set! *f* (+ *f* 1)))))
(define (check label actual expected)
  (if (equal? actual expected)
      (begin (display "[PASS] ") (display label) (newline))
      (begin (display "[FAIL] ") (display label)
             (display "  expected: ") (write expected)
             (display "  actual: ") (write actual) (newline))))
(display "=== Functional Primitive Tests ===\n")
(te caaadr)
(te caaddr)
(te cadaar)
(te cdadar)
(te cddaar)
(te cddadr)
(te cdddar)
(te alist->hash-table)
(te append!)
(te append-reverse!)
(te assert-violation)
(te assertion-violation)
(check "available-srfis" (list? (available-srfis)) #t)
(check "between?" (between? 5 1 10) #t)
(te binary-heap?)
(check "bytevector->list" (bytevector->list (bytevector 65 66 67)) '(65 66 67))
(check "bytevector->string" (bytevector->string (bytevector 104 101 108 108 111)) "hello")
(check "bytevector-s8-ref" (bytevector-s8-ref (bytevector 255 128 1) 1) -128)
(check "bytevector-s8-set!" (let ((bv (bytevector 0 0 0))) (bytevector-s8-set! bv 1 -128) (bytevector-u8-ref bv 1)) 128)
(check "caaaar" (caaaar '((((1 2) 3) 4) 5)) 1)
(check "caadar" (caadar '((1 (2)) 3)) 2)
(check "cadadr" (cadadr '(1 (2 3))) 3)
(check "caddar" (caddar '((1 2 3) 4)) 3)
(te call-with-bytevector-output-port)
(te call-with-string-output-port)
(te car+cdr)
(check "cdaaar" (cdaaar '((((1 2) 3) 4) 5)) '(2))
(check "cdaadr" (cdaadr '((1) ((2 3)))) '(3))
(check "cdaddr" (cdaddr '(1 (2) (3 4 5))) '(4 5))
(check "ceiling/" (call-with-values (lambda () (ceiling/ 10 3)) list) '(4 -2))
(check "char-set->integer" (integer? (char-set->integer (char-set #\a))) #t)
(check "char-set-unfold" (procedure? char-set-unfold) #t)
(check "char-set:digit" (char-set? char-set:digit) #t)
(check "char-set:graphic" (char-set? char-set:graphic) #t)
(check "char-set:letter" (char-set? char-set:letter) #t)
(check "char-set:lower" (char-set? char-set:lower) #t)
(check "char-set:lower-case" (char-set? char-set:lower-case) #t)
(check "char-set:printing" (char-set? char-set:printing) #t)
(check "char-set:upper" (char-set? char-set:upper) #t)
(check "char-set:upper-case" (char-set? char-set:upper-case) #t)
(check "char-set:whitespace" (char-set? char-set:whitespace) #t)
(te concatenate!)
(te cond-expand-srfi-61)
(check "constantly" ((constantly 42) 1 2 3) 42)
(check "current-error-port" (output-port? (current-error-port)) #t)
(te define-record-type)
(te define-record-type*)
(check "defined?" (defined? (quote +)) #t)
(check "deque-add-back!" (let ((d (make-deque 1 2))) (deque-add-back! d 3) (deque-back d)) 3)
(check "deque-add-front!" (let ((d (make-deque 2 3))) (deque-add-front! d 1) (deque-front d)) 1)
(check "deque-remove-back!" (let ((d (make-deque 1 2 3))) (deque-remove-back! d) (deque->list d)) '(1 2))
(check "deque-remove-front!" (let ((d (make-deque 1 2 3))) (deque-remove-front! d) (deque->list d)) '(2 3))
(te drop-right!)
(check "f32vector" (= (f32vector-length (f32vector 3.14 3.14)) 2) #t)
(check "f32vector-length" (f32vector-length (make-f32vector 5)) 5)
(te f32vector-ref)
(te f32vector-set!)
(check "f32vector?" (f32vector? (make-f32vector 3)) #t)
(check "f64vector" (= (f64vector-length (f64vector 3.14 3.14)) 2) #t)
(check "f64vector-length" (f64vector-length (make-f64vector 5)) 5)
(check "f64vector-ref" (f64vector-ref (make-f64vector 3 3.14) 1) 3.14)
(check "f64vector-set!" (let ((v (make-f64vector 3 0))) (f64vector-set! v 1 3.14) (f64vector-ref v 1)) 3.14)
(check "f64vector?" (f64vector? (make-f64vector 3)) #t)
(te find-tail)
(te fold-right-1)
(check "gentemp" (symbol? (gentemp)) #t)
(te hash-table-copy)
(check "identifier?" (identifier? (quote +)) #t)
(te include)
(te include-ci)
(te integer->char-set)
(check "keyword->string" (string? (keyword->string "test:")) #t)
(check "keyword?" (keyword? (string->keyword "test")) #t)
(te let*-values)
(te let-values)
(te let-values-helper)
(te letrec*)
(check "list->bytevector" (list->bytevector (quote (65 66 67))) #u8(65 66 67))
(te logand)
(te logior)
(te lognot)
(te logtest)
(te logxor)
(te lset-adjoin)
(te lset<=)
(te lset=)
(te make-coroutine-generator)
(check "make-f32vector" (= (f32vector-length (make-f32vector 3)) 3) #t)
(check "make-f64vector" (= (f64vector-length (make-f64vector 3)) 3) #t)
(te make-iota-generator)
(te make-random-source)
(te make-range-generator)
(te make-record-type)
(check "make-s16vector" (= (s16vector-length (make-s16vector 3)) 3) #t)
(check "make-s32vector" (= (s32vector-length (make-s32vector 3)) 3) #t)
(check "make-s64vector" (= (s64vector-length (make-s64vector 3)) 3) #t)
(check "make-s8vector" (= (s8vector-length (make-s8vector 3)) 3) #t)
(check "make-u16vector" (= (u16vector-length (make-u16vector 3)) 3) #t)
(check "make-u32vector" (= (u32vector-length (make-u32vector 3)) 3) #t)
(check "make-u64vector" (= (u64vector-length (make-u64vector 3)) 3) #t)
(check "make-u8vector" (= (u8vector-length (make-u8vector 3)) 3) #t)
(te random-source-make-integers)
(te random-source-make-reals)
(te record-accessor)
(te record-constructor)
(te record-modifier)
(te record-predicate)
(check "remq" (remq (quote a) (quote (a b a c))) '(b c))
(check "remv" (remv 1 (quote (1 2 1 3))) '(2 3))
(te require-extension)
(te require-srfi)
(check "s16vector" (= (s16vector-length (s16vector -1000 -1000)) 2) #t)
(check "s16vector-length" (s16vector-length (make-s16vector 5)) 5)
(check "s16vector-ref" (s16vector-ref (make-s16vector 3 -1000) 1) -1000)
(check "s16vector-set!" (let ((v (make-s16vector 3 0))) (s16vector-set! v 1 -1000) (s16vector-ref v 1)) -1000)
(check "s16vector?" (s16vector? (make-s16vector 3)) #t)
(check "s32vector" (= (s32vector-length (s32vector -100000 -100000)) 2) #t)
(check "s32vector-length" (s32vector-length (make-s32vector 5)) 5)
(check "s32vector-ref" (s32vector-ref (make-s32vector 3 -100000) 1) -100000)
(check "s32vector-set!" (let ((v (make-s32vector 3 0))) (s32vector-set! v 1 -100000) (s32vector-ref v 1)) -100000)
(check "s32vector?" (s32vector? (make-s32vector 3)) #t)
(check "s64vector" (= (s64vector-length (s64vector -1 -1)) 2) #t)
(check "s64vector-length" (s64vector-length (make-s64vector 5)) 5)
(check "s64vector-ref" (s64vector-ref (make-s64vector 3 -1) 1) -1)
(check "s64vector-set!" (let ((v (make-s64vector 3 0))) (s64vector-set! v 1 -1) (s64vector-ref v 1)) -1)
(check "s64vector?" (s64vector? (make-s64vector 3)) #t)
(check "s8vector" (= (s8vector-length (s8vector -42 -42)) 2) #t)
(check "s8vector-length" (s8vector-length (make-s8vector 5)) 5)
(check "s8vector-ref" (s8vector-ref (make-s8vector 3 -42) 1) -42)
(check "s8vector-set!" (let ((v (make-s8vector 3 0))) (s8vector-set! v 1 -42) (s8vector-ref v 1)) -42)
(check "s8vector?" (s8vector? (make-s8vector 3)) #t)
(check "set-box!" (let ((b (box 1))) (set-box! b 99) (unbox b)) 99)
(te simple-conditions)
(te source-file)
(check "srfi-available?" (srfi-available? 1) #t)
(check "stream?" (stream? (quote (1 2 3))) #f)
(check "string->bytevector" (bytevector? (string->bytevector "abc")) #t)
(check "string->keyword" (keyword? (string->keyword "test")) #t)
(check "string-normalize-nfc" (string-normalize-nfc "hello") "hello")
(check "string-normalize-nfd" (string-normalize-nfd "hello") "hello")
(check "string-normalize-nfkc" (string-normalize-nfkc "hello") "hello")
(check "string-normalize-nfkd" (string-normalize-nfkd "hello") "hello")
(check "string-prefix-ci?" (string-prefix-ci? "ABC" "abcdef") #t)
(te syntax-violation)
(te test-equal?)
(te transcript-off)
(te transcript-on)
(check "u16vector" (= (u16vector-length (u16vector 1000 1000)) 2) #t)
(check "u16vector-length" (u16vector-length (make-u16vector 5)) 5)
(check "u16vector-ref" (u16vector-ref (make-u16vector 3 1000) 1) 1000)
(check "u16vector-set!" (let ((v (make-u16vector 3 0))) (u16vector-set! v 1 1000) (u16vector-ref v 1)) 1000)
(check "u16vector?" (u16vector? (make-u16vector 3)) #t)
(check "u32vector" (= (u32vector-length (u32vector 100000 100000)) 2) #t)
(check "u32vector-length" (u32vector-length (make-u32vector 5)) 5)
(check "u32vector-ref" (u32vector-ref (make-u32vector 3 100000) 1) 100000)
(check "u32vector-set!" (let ((v (make-u32vector 3 0))) (u32vector-set! v 1 100000) (u32vector-ref v 1)) 100000)
(check "u32vector?" (u32vector? (make-u32vector 3)) #t)
(check "u64vector" (= (u64vector-length (u64vector 1 1)) 2) #t)
(check "u64vector-length" (u64vector-length (make-u64vector 5)) 5)
(check "u64vector-ref" (u64vector-ref (make-u64vector 3 1) 1) 1)
(check "u64vector-set!" (let ((v (make-u64vector 3 0))) (u64vector-set! v 1 1) (u64vector-ref v 1)) 1)
(check "u64vector?" (u64vector? (make-u64vector 3)) #t)
(check "u8vector" (= (u8vector-length (u8vector 42 42)) 2) #t)
(check "u8vector-length" (u8vector-length (make-u8vector 5)) 5)
(check "u8vector-ref" (u8vector-ref (make-u8vector 3 42) 1) 42)
(check "u8vector-set!" (let ((v (make-u8vector 3 0))) (u8vector-set! v 1 42) (u8vector-ref v 1)) 42)
(check "u8vector?" (u8vector? (make-u8vector 3)) #t)
(check "unbox" (unbox (box 42)) 42)
(te vector-sort!)
(te xsubstring)

(display "=== Functional Tests Complete ===\n")