;; test-install-core.scm — test for install() + install_core() + install_list()
;; Run: python allinone.py test-install-core.scm

(import (scheme base))
(define-syntax test
  (syntax-rules ()
    ((_ expected expr)
     (test-equal 'expr expected expr))))

(test 12 (* 3 4))
(test 1 (*))
(test 3 (+ 1 2))
(test 0 (+))
(test 2 (- 5 3))
(test -5 (- 5))
(test 5 (/ 10 2))
(test #t (< 1 2 3))
(test #t (<= 1 2 2))
(test #t (= 2 2 2))
(test #t (> 3 2 1))
(test #t (>= 3 2 2))
(test 5 (abs 5))
(test 5 (abs -5))
(test 0.0 (acos 1))
(test 0.0 (angle 1))
(test #t (any odd? '(2 3 4)))
(test '(1 2 3 4) (append '(1 2) '(3 4)))
(test '(1 -1 2 -2) (append-map (lambda (x) (list x (- x))) '(1 2)))
(test 6 (apply + '(1 2 3)))
(test 12 (arithmetic-shift 3 2))
(test 0.0 (asin 0))
(test '(a . 1) (assoc 'a '((a . 1) (b . 2))))
(test '(a . 1) (assq 'a '((a . 1))))
(test '(1 . a) (assv 1 '((1 . a))))
(test 0.0 (atan 0))
(test #f (binary-port? (current-input-port)))
(test 2 (bit-and 6 3))
(test 2 (bit-count 6))
(test 2 (bit-field 13 1 3))
(test -1 (bit-not 0))
(test 7 (bit-or 6 3))
(test #t (bit-set? 6 1))
(test 12 (bit-shift 3 2))
(test 5 (bit-xor 6 3))
(test #t (bitwise-any-bit-set? 6 2))
(test 12 (bitwise-arithmetic-shift 3 2))
(test 7 (bitwise-ior 6 3))
(test "#t" (boolean->string #t))
(test #t (boolean=? #t #t #t))
(test #t (boolean? #t))
(test '((1 3) (4 5)) (call-with-values (lambda () (break even? '(1 3 4 5))) list))
(test '((1 2) (3 4)) (call-with-values (lambda () (break-list (lambda (x) (> x 2)) '(1 2 3 4))) list))
(test '#u8(65 66 67) (bytevector 65 66 67))
(test '#u8(1 2 3 4) (bytevector-append #u8(1 2) #u8(3 4)))
(test '#u8(1 2 3) (bytevector-copy #u8(1 2 3)))
(test '#u8(1 10 20 4 5) (let ((t (bytevector 1 2 3 4 5))) (bytevector-copy! t 1 #u8(10 20)) t))
(test 3 (bytevector-length #u8(1 2 3)))
(test 20 (bytevector-u8-ref #u8(10 20 30) 1))
(test '#u8(1 99 3) (let ((bv (bytevector 1 2 3))) (bytevector-u8-set! bv 1 99) bv))
(test #t (bytevector? #u8(1 2)))
(test 1 (caaar '(((1) 2) 3)))
(test 2 (caadr '((1) (2) (3))))
(test 1 (caar '((1 2) 3)))
(test 2 (cadar '((1 2 3) 4)))
(test 4 (cadddr '(1 2 3 4)))
(test 3 (caddr '(1 2 3)))
(test 2 (cadr '(1 2 3)))
(test 42 (call-with-current-continuation (lambda (k) (k 42))))
(test '#\a (call-with-input-string "abc" (lambda (p) (read-char p))))
(test '#\a (call-with-port (open-input-string "abc") (lambda (p) (read-char p))))
(test "\"hi\"" (call-with-string-output (lambda (p) (write "hi" p))))
(test '(1 2) (call-with-values (lambda () (values 1 2)) list))
(test 42 (call/cc (lambda (k) (k 42))))
(test 1 (car '(1 . 2)))
(test '(2) (cdaar '(((1 2) 3) 4)))
(test '(3 4) (cdadr '(1 (2 3 4))))
(test '(2) (cdar '((1 2) 3)))
(test '(3) (cddar '((1 2 3) 4)))
(test '(5) (cddddr '(1 2 3 4 5)))
(test '(4) (cdddr '(1 2 3 4)))
(test '(3) (cddr '(1 2 3)))
(test 2 (cdr '(1 . 2)))
(test 4.0 (ceiling 3.2))
(test 4 (ceiling->exact 3.2))
(test 65 (char->integer #\A))
(test #t (char-alphabetic? #\a))
(test #t (char-ci<=? #\a #\A))
(test #t (char-ci<? #\a #\B))
(test #t (char-ci=? #\a #\A))
(test #t (char-ci>=? #\A #\a))
(test #t (char-ci>? #\B #\a))
(test '#\a (char-downcase #\A))
(test '#\a (char-foldcase #\A))
(test #t (char-lower-case? #\a))
(test "space" (char-name #\space))
(test #t (char-numeric? #\5))
(test #t (char-ready?))
(test '#\A (char-upcase #\a))
(test #t (char-upper-case? #\A))
(test #t (char-whitespace? #\space))
(test #t (char<=? #\a #\a))
(test #t (char<? #\a #\b))
(test #t (char=? #\a #\a))
(test #t (char>=? #\b #\a))
(test #t (char>? #\b #\a))
(test #t (char? #\a))
(test 1 (car (circular-list 1 2)))
(test #t (circular-list? (circular-list 1)))
(test #t (string? (car (command-line))))
(test #t (complex? 5))
(test 8 ((compose (lambda (x) (* x 2)) (lambda (x) (+ x 1))) 3))
(test '(1 2 3 4) (concatenate '((1 2) (3 4))))
(test #f (condition-has-type? (make-compound-condition) 42))
(test #f (condition-type? 42))
(test #t (string? (condition/report-string (make-compound-condition))))
(test #f (condition? 5))
(test '(1 . 2) (cons 1 2))
(test '(1 2 . 3) (cons* 1 2 3))
(test 4 (copy-bit 0 2 #t))
(test 1.0 (cos 0))
(test 1.0 (cosh 0))
(test 2 (count even? '(1 2 3 4)))
(test #t (> (current-jiffy) 0))
(test #t (> (current-second) 1e9))
(test 3 (force (delay-force (delay (+ 1 2)))))
(test '(1 3) (delete 2 '(1 2 3 2)))
(test '((b . 2)) (delete-assoc 'a '((a . 1) (b . 2))))
(test '(1 2 3) (delete-duplicates '(1 2 1 3)))
(test 1 (denominator 3))
(test 5 (digit-value #\5))
(test #t (dotted-list? '(1 . 2)))
(test '(3 4) (drop '(1 2 3 4) 2))
(test '(1 2) (drop-right '(1 2 3 4) 2))
(test '(5 6) (drop-while even? '(2 4 5 6)))
(test '(a b) (let ((x '())) (dynamic-wind (lambda () (set! x (cons 'a x))) (lambda () 'done) (lambda () (set! x (cons 'b x)))) (reverse x)))
(test (if #f #f) (begin (environment) (void)))
(test #t (eof-object? (eof-object)))
(test #f (eof-object? 5))
(test #t (eq? 'a 'a))
(test #t (equal? '(a b) '(a b)))
(test #t (eqv? 2 2))
(test #f (error-object? 5))
(test #f (error? 5))
(test 3 (eval '(+ 1 2)))
(test #t (even? 4))
(test #t (every even? '(2 4 6)))
(test (inexact->exact 5.0) (exact 5.0))
(test 5.0 (exact->inexact 5))
(test '(4 1) (call-with-values (lambda () (exact-integer-sqrt 17)) list))
(test #t (exact-integer? 5))
(test #t (exact? 5))
(test #f (exact? 5.0))
(test 1.0 (exp 0))
(test 8 (expt 2 3))
(test #f (extract-condition (make-compound-condition) 42))
(test #t (pair? (features)))
(test #f (file-error? 5))
(test #t (file-exists? "/123/scheme/base.py"))
(test '(2 4) (filter even? '(1 2 3 4)))
(test 2 (find even? '(1 2 3)))
(test #t (finite? 5))
(test '(1 -1 2 -2) (flat-map (lambda (x) (list x (- x))) '(1 2)))
(test '(1 2 3 4) (flatten '(1 (2 (3) 4))))
(test 3.0 (floor 3.9))
(test 3 (floor->exact 3.9))
(test 3 (floor-quotient 10 3))
(test 1 (floor-remainder 10 3))
(test '(3 1) (call-with-values (lambda () (floor/ 10 3)) list))
(test (if #f #f) (begin (flush-output-port) (void)))
(test 6 (fold + 0 '(1 2 3)))
(test 6 (fold-left + 0 '(1 2 3)))
(test 2 (fold-right - 0 '(1 2 3)))
(test '(1 2 3) (let ((acc '())) (for-each (lambda (x) (set! acc (cons x acc))) '(1 2 3)) (reverse acc)))
(test 3 (force (delay (+ 1 2))))
(test "hello world" (format "hello ~a" "world"))
(test 4 (gcd 12 8))
(test #t (string? (get-environment-variable "PATH")))
(test #t (pair? (get-environment-variables)))
(test '#u8(65) (let ((p (open-output-bytevector))) (write-u8 65 p) (get-output-bytevector p)))
(test "\"hi\"" (let ((p (open-output-string))) (write "hi" p) (get-output-string p)))
(test #t (let ((ht (make-hash-table))) (hash-table-set! ht 'a 1) (pair? (hash-table->alist ht))))
(test #t (let ((ht (make-hash-table))) (hash-table-set! ht 'a 1) (hash-table-contains? ht 'a)))
(test #f (let ((ht (make-hash-table))) (hash-table-set! ht 'a 1) (hash-table-delete! ht 'a) (hash-table-contains? ht 'a)))
(test #f (hash-table-exists? (make-hash-table) 'a))
(test '(a) (let ((ht (make-hash-table)) (acc '())) (hash-table-set! ht 'a 1) (hash-table-for-each (lambda (k v) (set! acc (cons k acc))) ht) (reverse acc)))
(test '(a) (let ((ht (make-hash-table))) (hash-table-set! ht 'a 1) (hash-table-keys ht)))
(test #t (let ((ht (make-hash-table))) (hash-table-set! ht 'a 1) (list? (hash-table-map (lambda (k v) (list k v)) ht))))
(test 2 (let ((a (make-hash-table)) (b (make-hash-table))) (hash-table-set! a 'a 1) (hash-table-set! b 'b 2) (hash-table-size (hash-table-merge! a b))))
(test 1 (let ((ht (make-hash-table))) (hash-table-set! ht 'a 1) (hash-table-ref ht 'a)))
(test 42 (hash-table-ref/default (make-hash-table) 'a 42))
(test 1 (let ((ht (make-hash-table))) (hash-table-set! ht 'a 1) (hash-table-ref ht 'a)))
(test 1 (let ((ht (make-hash-table))) (hash-table-set! ht 'a 1) (hash-table-size ht)))
(test 2 (let ((ht (make-hash-table))) (hash-table-set! ht 'a 1) (hash-table-update! ht 'a (lambda (v) (+ v 1))) (hash-table-ref ht 'a)))
(test '(1) (let ((ht (make-hash-table))) (hash-table-set! ht 'a 1) (hash-table-values ht)))
(test '(a) (let ((ht (make-hash-table)) (acc '())) (hash-table-set! ht 'a 1) (hash-table-walk (lambda (k v) (set! acc (cons k acc))) ht) (reverse acc)))
(test 0 (hash-table/count (make-hash-table)))
(test 1 (let ((ht (make-hash-table))) (hash-table/put! ht 'a 1) (hash-table-ref ht 'a)))
(test #t (hash-table? (make-hash-table)))
(test (if #f #f) (helper 42))
(test 4.0 (imag-part 3+4i))
(test 5.0 (inexact 5))
(test 5 (inexact->exact 5.0))
(test #t (inexact? 5.0))
(test #f (infinite? 5))
(test #t (input-port-open? (current-input-port)))
(test #t (input-port? (current-input-port)))
(test '#\A (integer->char 65))
(test 3 (integer-length 5))
(test #t (integer? 5))
(test (if #f #f) (begin (interaction-environment) (void)))
(test '(0 1 2 3) (iota 4))
(test #t (= (jiffies-per-second) 1000000))
(test '(3) (last-pair '(1 2 3)))
(test 12 (lcm 4 6))
(test 3 (length '(1 2 3)))
(test '(1 2) (linear-update-list 1 2))
(test '(1 2 3) (list 1 2 3))
(test '(1 2 3 4) (list* 1 2 '(3 4)))
(test "ab" (list->string '(#\a #\b)))
(test '#(a b c) (list->vector '(a b c)))
(test '(1 2) (list-copy '(1 2)))
(test '(1 2) (list-head '(1 2 3) 2))
(test 'b (list-ref '(a b c) 1))
(test '(1 x 3) (let ((l (list 1 2 3))) (list-set! l 1 'x) l))
(test '(1 2 3) (list-sort < '(3 1 2)))
(test '(1 2 3) (list-stable-sort < '(3 1 2)))
(test '(0 1 2 3) (list-tabulate 4 values))
(test '(2 3) (list-tail '(1 2 3) 1))
(test #t (list? '(1 2)))
(test 0.0 (log 1))
(test 'done (begin (define (loop-n n) (if (= n 0) 'done (loop-n (- n 1)))) (loop-n 3)))
(test 5 (magnitude -5))
(test '#u8(255 255 255) (make-bytevector 3 255))
(test #t (condition? (make-compound-condition)))
(test #t (hash-table? (make-eq-hash-table)))
(test #t (hash-table? (make-equal-hash-table)))
(test #t (hash-table? (make-eqv-hash-table)))
(test #t (hash-table? (make-hash-table)))
(test '(x x x) (make-list 3 'x))
(test 5 (let ((p (make-parameter 5))) (p)))
(test 1.0 (real-part (make-polar 1 0)))
(test #t (promise? (make-promise (+ 1 2))))
(test 3+4i (make-rectangular 3 4))
(test "xxx" (make-string 3 #\x))
(test #t (hash-table? (make-strong-hash-table)))
(test '#(x x x) (make-vector 3 'x))
(test '(11 22 33) (map + '(1 2 3) '(10 20 30)))
(test 3 (max 3 1 2))
(test '(2 3) (member 2 '(1 2 3)))
(test '(a c) (memq 'a '(b a c)))
(test '(2 3) (memv 2 '(1 2 3)))
(test '(1 2 3 4) (merge < '(1 3) '(2 4)))
(test '(1 2 3 4) (merge! < '(1 3) '(2 4)))
(test 1 (min 3 1 2))
(test 1 (modulo 10 3))
(test #f (nan? 5))
(test #t (negative? -3))
(test (if #f #f) (begin (newline) (void)))
(test (if #f #f) (begin (null-environment 5) (void)))
(test #t (null? '()))
(test "123" (number->string 123))
(test #t (number? 5))
(test 3 (numerator 3))
(test #t (odd? 3))
(test 65 (read-u8 (open-input-bytevector #u8(65 66))))
(test '#\a (read-char (open-input-string "abc")))
(test #t (bytevector? (get-output-bytevector (open-output-bytevector))))
(test #t (string? (get-output-string (open-output-string))))
(test #t (output-port-open? (current-output-port)))
(test #t (output-port? (current-output-port)))
(test '(3 2 1) (pair-fold (lambda (p a) (cons (car p) a)) '() '(1 2 3)))
(test '(1 2 3) (pair-fold-right (lambda (p a) (cons (car p) a)) '() '(1 2 3)))
(test #t (pair? '(1 . 2)))
(test '((2 4) (1 3)) (call-with-values (lambda () (partition even? '(1 2 3 4))) list))
(test #t (port-open? (current-input-port)))
(test 0 (port-position (open-input-string "abc")))
(test #t (port? (current-input-port)))
(test #t (positive? 5))
(test (if #f #f) (pp 42))
(test (if #f #f) (pretty-print 42))
(test (if #f #f) (print 42))
(test #t (procedure? +))
(test #t (promise? (delay (+ 1 2))))
(test 3 (quotient 10 3))
(test #t (rational? 5))
(test #f (read-error? 5))
(test 3.0 (real-part 3+4i))
(test #t (real? 5))
(test #f (record? 5))
(test 6 (reduce + 0 '(1 2 3)))
(test 1 (remainder 10 3))
(test '(1 3) (remove even? '(1 2 3 4)))
(test '(3 2 1) (reverse '(1 2 3)))
(test 4.0 (round 3.5))
(test 4 (round->exact 3.5))
(test (if #f #f) (begin (scheme-report-environment 5) (void)))
(test '(3 . 2) (let ((p (cons 1 2))) (set-car! p 3) p))
(test '(1 . 3) (let ((p (cons 1 2))) (set-cdr! p 3) p))
(test '#\c (let ((p (open-input-string "abcde"))) (set-port-position! p 2) (read-char p)))
(test 0.0 (sin 0))
(test 0.0 (sinh 0))
(test (if #f #f) (sink 42))
(test #t (sorted? < '(1 2 3)))
(test '((2 4) (5 6)) (call-with-values (lambda () (span even? '(2 4 5 6))) list))
(test '((1 2) (3 4)) (call-with-values (lambda () (split-at '(1 2 3 4) 2)) list))
(test 3 (sqrt 9))
(test 16 (square 4))
(test '(#\a #\b #\c) (string->list "abc"))
(test 456 (string->number "456"))
(test 'hello (string->symbol "hello"))
(test '#u8(97 98 99) (string->utf8 "abc"))
(test "abcd" (string-append "ab" "cd"))
(test #t (string-ci<=? "abc" "ABC"))
(test #t (string-ci<? "abc" "ABD"))
(test #t (string-ci=? "abc" "ABC"))
(test #t (string-ci>=? "ABC" "abc"))
(test #t (string-ci>? "ABD" "abc"))
(test "abc" (string-copy "abc"))
(test "aXYZe" (let ((t (string-copy "abcde"))) (string-copy! t 1 "XYZ") t))
(test "zzz" (let ((s (string-copy "abc"))) (string-fill! s #\z) s))
(test 3 (string-length "abc"))
(test '#\b (string-ref "abc" 1))
(test "aXc" (let ((s (string-copy "abc"))) (string-set! s 1 #\X) s))
(test #t (string<=? "abc" "abc"))
(test #t (string<? "abc" "abd"))
(test #t (string=? "abc" "abc"))
(test #t (string>=? "abc" "abc"))
(test #t (string>? "abd" "abc"))
(test #t (string? "abc"))
(test "ell" (substring "hello" 1 4))
(test "hello" (symbol->string 'hello))
(test #t (symbol=? 'a 'a))
(test #t (symbol? 'abc))
(test #f (syntax? 5))
(test '(1 2) (take '(1 2 3 4) 2))
(test '(3 4) (take-right '(1 2 3 4) 2))
(test '(2 4) (take-while even? '(2 4 5 6)))
(test 0.0 (tan 0))
(test 0.0 (tanh 0))
(test #t (textual-port? (current-input-port)))
(test 3.0 (truncate 3.9))
(test 3 (truncate->exact 3.9))
(test 3 (truncate-quotient 10 3))
(test 1 (truncate-remainder 10 3))
(test '(3 1) (call-with-values (lambda () (truncate/ 10 3)) list))
(test #t (u8-ready?))
(test '(0 2 4 6) (unfold (lambda (x) (> x 3)) (lambda (x) (* x 2)) (lambda (x) (+ x 1)) 0))
(test "abc" (utf8->string #u8(97 98 99)))
(test '(1 2) (call-with-values (lambda () (values 1 2)) list))
(test '#(1 2 3) (vector 1 2 3))
(test '(a b c) (vector->list '#(a b c)))
(test '#(1 2 3 4) (vector-append '#(1 2) '#(3 4)))
(test '#(1 2 3) (vector-copy '#(1 2 3)))
(test '#(1 10 20 4 5) (let ((t (vector 1 2 3 4 5))) (vector-copy! t 1 '#(10 20)) t))
(test '#(x x x) (let ((v (vector 1 2 3))) (vector-fill! v 'x) v))
(test 3 (vector-length '#(1 2 3)))
(test '#(11 22 33) (vector-map + '#(1 2 3) '#(10 20 30)))
(test 'b (vector-ref '#(a b c) 1))
(test '#(1 x) (let ((v (vector 1 2))) (vector-set! v 1 'x) v))
(test #t (vector? #(1 2)))
(test 42 (with-input-from-string "42" read))
(test (if #f #f) (write-shared 42))
(test (if #f #f) (write-simple 42))
(test #t (zero? 0))
(test #f (zero? 1))
(test '((1 a) (2 b)) (zip '(1 2) '(a b)))

(print "install-core tests done")

(test (if #f #f) (let ((p (open-input-string "abc"))) (close-input-port p) (void)))
(test (if #f #f) (let ((p (open-output-string))) (close-output-port p) (void)))
(test (if #f #f) (let ((p (open-input-string "abc"))) (close-port p) (void)))
(test (if #f #f) (let ((p (open-output-string))) (close-port p) (void)))
(test '#\a (peek-char (open-input-string "abc")))
(test '#\b (let ((p (open-input-string "abc"))) (peek-char p) (read-char p) (peek-char p)))
(test '#\b (let ((p (open-input-string "abc"))) (read-char p) (peek-char p)))
(test '#\a (peek-char (open-input-string "a")))
(test 65 (peek-u8 (open-input-bytevector #u8(65 66 67))))
(test 66 (begin (define p (open-input-bytevector #u8(65 66 67))) (read-u8 p) (peek-u8 p)))
(test "abc" (read-line (open-input-string "abc\nnext")))
(test "abc" (read-line (open-input-string "abc")))
(test "" (read-line (open-input-string "\n")))
(test (eof-object) (read-line (open-input-string "")))
(test "abc" (read-string 3 (open-input-string "abcdef")))
(test "abc" (read-string 5 (open-input-string "abc")))
(test "" (read-string 0 (open-input-string "abc")))
(test '#u8(65 66 67) (read-bytevector 3 (open-input-bytevector #u8(65 66 67 68))))
(test '#u8(65 66) (read-bytevector 5 (open-input-bytevector #u8(65 66))))
(test '#u8(10 20 30 40) (let ((bv (bytevector 0 0 0 0))) (read-bytevector! bv (open-input-bytevector #u8(10 20 30 40))) bv))
(test 4 (let ((bv (bytevector 0 0 0 0))) (read-bytevector! bv (open-input-bytevector #u8(10 20 30 40)))))
(test "a" (let ((p (open-output-string))) (write-char #\a p) (get-output-string p)))
(test "a" (let ((p (open-output-string))) (write-char #\a p) (get-output-string p)))
(test "hello" (let ((p (open-output-string))) (write-string "hello" p) (get-output-string p)))
(test "wor" (let ((p (open-output-string))) (write-string "world" p 0 3) (get-output-string p)))
(test '#u8(10 20 30) (let ((p (open-output-bytevector))) (write-bytevector #u8(10 20 30) p) (get-output-bytevector p)))
(test "hello" (let ((p (open-output-string))) (display "hello" p) (get-output-string p)))
(test "42" (let ((p (open-output-string))) (display 42 p) (get-output-string p)))
(test "abc" (let ((p (open-output-string))) (display 'abc p) (get-output-string p)))
(test "abc" (call-with-output-string (lambda (p) (display "abc" p))))
(test "" (call-with-output-string (lambda (p) (void))))
(test 42 (begin (call-with-output-file "/tmp/_test_scm_out.txt" (lambda (p) (write 42 p))) (call-with-input-file "/tmp/_test_scm_out.txt" read)))
(test #t (begin (delete-file "/tmp/_test_scm_out.txt") #t))
(test "data" (begin (call-with-output-file "/tmp/_test_scm_data.txt" (lambda (p) (display "data" p))) (let ((p (open-input-file "/tmp/_test_scm_data.txt"))) (read-line p))))
(test '#u8(1 2 3) (begin (let ((p (open-binary-output-file "/tmp/_test_scm_bin.dat"))) (write-bytevector #u8(1 2 3) p) (close-port p)) (let ((p (open-binary-input-file "/tmp/_test_scm_bin.dat"))) (read-bytevector 10 p))))
(test 99 (begin (with-output-to-file "/tmp/_test_scm_w.txt" (lambda () (write 99))) (with-input-from-file "/tmp/_test_scm_w.txt" read)))
(test #t (begin (call-with-output-file "/tmp/_test_scm_del.txt" (lambda (p) (display "x" p))) (file-exists? "/tmp/_test_scm_del.txt")))
(test #t (begin (delete-file "/tmp/_test_scm_del.txt") (not (file-exists? "/tmp/_test_scm_del.txt"))))
(test #t (begin (call-with-output-file "/tmp/_test_scm_old.txt" (lambda (p) (display "x" p))) (rename-file "/tmp/_test_scm_old.txt" "/tmp/_test_scm_new.txt") (and (file-exists? "/tmp/_test_scm_new.txt") (not (file-exists? "/tmp/_test_scm_old.txt")))))
(test #t (begin (delete-file "/tmp/_test_scm_new.txt") #t))
(test #t (begin (delete-file "/tmp/_test_scm_data.txt") #t))
(test #t (begin (when (file-exists? "/tmp/_test_scm_bin.dat") (delete-file "/tmp/_test_scm_bin.dat")) #t))
(test #t (begin (when (file-exists? "/tmp/_test_scm_w.txt") (delete-file "/tmp/_test_scm_w.txt")) #t))
(test (if #f #f) (begin (call-with-output-file "/tmp/_test_scm_load.scm" (lambda (p) (display "(define loaded-val 777)" p))) (load "/tmp/_test_scm_load.scm") (delete-file "/tmp/_test_scm_load.scm") (void)))
(test 777 loaded-val)
(test 42 (call-with-current-continuation (lambda (k) (with-exception-handler (lambda (e) (k 42)) (lambda () (raise "oops"))))))
(test 'caught (call-with-current-continuation (lambda (k) (with-exception-handler (lambda (e) (k 'caught)) (lambda () (+ 1 (raise "err")))))))
(test 'handled (with-exception-handler (lambda (e) 'handled) (lambda () (raise-continuable "cont"))))
(test #t (error? (car (call-with-current-continuation (lambda (k) (with-exception-handler (lambda (e) (k (list e))) (lambda () (error "test-err"))))))))
(test #t (let* ((e (car (call-with-current-continuation (lambda (k) (with-exception-handler (lambda (e) (k (list e))) (lambda () (raise "test-irr")))))))) (list? (error-object-irritants e))))
(test #t (string? (error-message (car (call-with-current-continuation (lambda (k) (with-exception-handler (lambda (e) (k (list e))) (lambda () (raise "test-msg")))))))))
(test (rationalize 3.14 0.01) (rationalize 3.14 0.01))
(test #t (< (abs (- (rationalize 3.1415926535 0.001) 3.1416)) 0.001))
(test (rationalize (inexact->exact 3.14) 1/100) (rationalize 3.14 0.01))
(test 'a (syntax->datum (datum->syntax (syntax->datum #'car) 'a)))
(test (quote (1 2 3)) (syntax->datum (datum->syntax #'car (quote (1 2 3)))))
(test #t (bound-identifier=? #'a #'a))
(test #t (free-identifier=? #'car #'car))
(test 3 (let ((stx (generate-temporaries '(a b c)))) (length stx)))
(test #t (let ((stx (generate-temporaries '(a b c)))) (every syntax? stx)))
(test '(1 2 3 4) (call-with-values (lambda () (values 1 2)) (lambda (a b) (call-with-values (lambda () (values 3 4)) (lambda (c d) (list a b c d))))))
(test '(3 8) (call-with-values (lambda () (values (+ 1 2) (* 2 4))) list))
(test '(4 16 36) (map (lambda (x) (* x x)) (filter even? '(1 2 3 4 5 6))))
(test 12 (fold + 0 (map (lambda (x) (* x 2)) (iota 4))))
(test "HELLO" (string-upcase "hello"))
(test "hello" (string-downcase "HELLO"))
(test "hello world" (string-append (string-downcase "HELLO") " " (string-downcase "WORLD")))
(test 5 (string-length (string-append (make-string 3 #\x) (make-string 2 #\y))))
(test #t (equal? '#(1 2 3) (list->vector (vector->list '#(1 2 3)))))
(test '(a b c) (vector->list (list->vector '(a b c))))
(test '#(10 20 30 40) (vector-map (lambda (x) (* x 10)) (vector 1 2 3 4)))
(test "abc" (utf8->string (string->utf8 "abc")))
(test '#u8(97 98 99) (string->utf8 (utf8->string #u8(97 98 99))))
(test 5+7i (make-rectangular (+ (real-part 3+4i) 2) (+ (imag-part 3+4i) 3)))
(test 5.0 (magnitude (make-rectangular 3 4)))
(test '((1 . 2) (3 . 4)) (map cons '(1 3) '(2 4)))
(test '(3 5 7) (map (lambda (x) (+ x 1)) (map (lambda (x) (* x 2)) '(1 2 3))))
(test 10 (fold + 0 (flatten '((1 2) (3 4)))))
(test #t (let ((ht (make-hash-table))) (hash-table-set! ht 'a 1) (hash-table-set! ht 'b 2) (and (= 1 (hash-table-ref ht 'a)) (= 2 (hash-table-ref ht 'b)))))
(test 3 (let ((ht (make-hash-table))) (hash-table-set! ht 'a 1) (hash-table-update! ht 'a (lambda (x) (+ x 2))) (hash-table-ref ht 'a)))
(test #t (every char-alphabetic? (string->list "abc")))
(test #f (every char-alphabetic? (string->list "a b")))
(test '(#\a #\b #\c) (take-while char-alphabetic? (string->list "abc123")))
(test 7 (bitwise-ior (bit-and 6 3) (bit-xor 6 3)))
(test #t (bit-set? (bitwise-arithmetic-shift 1 3) 3))
(test #t (= 5 (inexact->exact (exact->inexact 5))))
(test #t (exact? (inexact->exact 5.0)))
(test #t (inexact? (exact->inexact 5)))
(test "XYz" (let ((s (string-copy "abcde")) (src (string-copy "XYzzzz"))) (string-copy! s 0 src 0 3) (substring s 0 3)))
(test '(c . 3) (assoc 'c '((a . 1) (b . 2) (c . 3) (d . 4))))
(test #f (assoc 'z '((a . 1) (b . 2))))
(test '(5 7 9) (map + '(1 2 3) '(4 5 6)))
(test '(1 4 9 16) (map (lambda (x) (* x x)) (iota 4 1)))
(test 15 (apply + (iota 5 1)))
(test '(() (1 3 5)) (call-with-values (lambda () (partition even? '(1 3 5))) list))
(test '(3 4) (drop (take '(1 2 3 4 5) 4) 2))
(test #t (and (list? '(a b c)) (not (list? '(a . b)))))
(test #t (and (pair? '(a . b)) (not (pair? '()))))
(test 'hello (string->symbol (symbol->string 'hello)))
(test #t (string? (symbol->string 'abc)))
(test 55 (fold + 0 (iota 10 1)))
(test 3628800 (fold * 1 (iota 10 1)))

;; Additional coverage for remaining builtins
(test #t (string? (error-object-message (car (call-with-current-continuation (lambda (k) (with-exception-handler (lambda (e) (k (list e))) (lambda () (error "err-msg")))))))))
(test #t (let ((p (open-output-file "/tmp/_test_scm_out2.txt"))) (display "test" p) (close-port p) (file-exists? "/tmp/_test_scm_out2.txt")))
(test #f (begin (delete-file "/tmp/_test_scm_out2.txt") (file-exists? "/tmp/_test_scm_out2.txt")))
