;; Auto-generated primitive coverage test
(define *p* 0) (define *f* 0)
(define (te name)
  (if (not (eq? name (if #f #f)))
      (set! *p* (+ *p* 1))
      (begin (display "[FAIL] ") (display name) (newline)
             (set! *f* (+ *f* 1)))))
(define (check label actual expected)
  (if (equal? actual expected)
      (begin (display "[PASS] ") (display label) (newline))
      (begin (display "[FAIL] ") (display label)
             (display "  expected: ") (write expected)
             (display "  actual: ") (write actual) (newline))))
(display "\n=== Primitive Coverage ===\n")
(check "acosh" (procedure? acosh) #t)
(te alist->hash-table)
(te append!)
(te append-reverse!)
(check "asinh" (procedure? asinh) #t)
(te assert-violation)
(te assertion-violation)
(check "atanh" (procedure? atanh) #t)
(te available-srfis)
(te between?)
(te binary-heap?)
(check "bitwise-bit-set?" (bitwise-bit-set? 6 2) #t)
(te bytevector->list)
(te bytevector->string)
(te bytevector-s8-ref)
(te bytevector-s8-set!)
(te caadar)
(te caaddr)
(te cadaar)
(te cadadr)
(te caddar)
(te call-with-bytevector-output-port)
(te call-with-string-output-port)
(te car+cdr)
(te cdaaar)
(te cdaadr)
(te cdadar)
(te cdaddr)
(te cddaar)
(te cddadr)
(te cdddar)
(te ceiling/)
(te char-set->integer)
(te char-set-unfold)
(te char-set:graphic)
(te char-set:printing)
(check "char-title-case?" (char-title-case? #\a) #f)
(check "char-titlecase" (char-titlecase (integer->char 97)) (integer->char 65))
(te concatenate!)
(te cond-expand-srfi-61)
(te constantly)
(te current-error-port)
(te define-record-type)
(te define-record-type*)
(te defined?)
(te deque-add-back!)
(te deque-add-front!)
(te deque-remove-back!)
(te deque-remove-front!)
(check "div0" (div0 10 3) 3)
(te drop-right!)
(check "exact-integer-floor" (exact-integer-floor 10 3) 3)
(te f32vector)
(te f32vector-length)
(te f32vector-ref)
(te f32vector-set!)
(te f32vector?)
(te f64vector)
(te f64vector-length)
(te f64vector-ref)
(te f64vector-set!)
(te f64vector?)
(te find-tail)
(te fold-right-1)
(check "for-all" (for-all even? (quote (2 4 6))) #t)
(te gentemp)
(check "hash-by-identity" (>= (hash-by-identity "a") 0) #t)
(te hash-table-copy)
(te identifier?)
(te include)
(te include-ci)
(check "inexact-sqrt" (inexact-sqrt 9) 3.0)
(te integer->char-set)
(te keyword->string)
(te keyword?)
(te let*-values)
(te let-values)
(te let-values-helper)
(te letrec*)
(te list->bytevector)
(te lset-adjoin)
(te lset<=)
(te lset=)
(te make-f32vector)
(te make-f64vector)
(te make-random-source)
(te make-record-type)
(te make-s16vector)
(te make-s32vector)
(te make-s64vector)
(te make-s8vector)
(te make-u16vector)
(te make-u32vector)
(te make-u64vector)
(te make-u8vector)
(check "mod0" (mod0 10 3) 1)
(te random-source-make-integers)
(te random-source-make-reals)
(te record-accessor)
(te record-constructor)
(te record-modifier)
(te record-predicate)
(te remq)
(te remv)
(te require-extension)
(te require-srfi)
(te s16vector)
(te s16vector-length)
(te s16vector-ref)
(te s16vector-set!)
(te s16vector?)
(te s32vector)
(te s32vector-length)
(te s32vector-ref)
(te s32vector-set!)
(te s32vector?)
(te s64vector)
(te s64vector-length)
(te s64vector-ref)
(te s64vector-set!)
(te s64vector?)
(te s8vector)
(te s8vector-length)
(te s8vector-ref)
(te s8vector-set!)
(te s8vector?)
(te set-box!)
(te simple-conditions)
(te source-file)
(te srfi-available?)
(te stream?)
(te string->bytevector)
(te string->keyword)
(check "string-concatenate-reverse" (string-concatenate-reverse (list "a" "b")) "ba")
(check "string-contains?" (string-contains? "hello" "ell") #t)
(te string-normalize-nfc)
(te string-normalize-nfd)
(te string-normalize-nfkc)
(te string-normalize-nfkd)
(check "string-null?" (string-null? "") #t)
(te string-prefix-ci?)
(check "substring-count" (substring-count "ababa" "aba") 2)
(te syntax-violation)
(te test-equal?)
(te transcript-off)
(te transcript-on)
(te u16vector)
(te u16vector-length)
(te u16vector-ref)
(te u16vector-set!)
(te u16vector?)
(te u32vector)
(te u32vector-length)
(te u32vector-ref)
(te u32vector-set!)
(te u32vector?)
(te u64vector)
(te u64vector-length)
(te u64vector-ref)
(te u64vector-set!)
(te u64vector?)
(te u8vector)
(te u8vector-length)
(te u8vector-ref)
(te u8vector-set!)
(te u8vector?)
(te unbox)
(te vector-sort!)
(te xsubstring)

(display "\n=== Primitive Coverage Complete ===\n")