;; 08-let-syntax.scm — let-syntax / letrec-syntax

(define (generate-pair)
  (let-syntax ((pair-of (lambda (stx)
                          (syntax-case stx ()
                            ((_ type)
                             (syntax (cons (type) (type))))))))
    (pair-of number)))

(let-syntax ((my-let (lambda (stx)
                       (syntax-case stx ()
                         ((_ ((var val) ...) body ...)
                          (syntax ((lambda (var ...) body ...) val ...)))))))
  (my-let ((x 10) (y 20)) (+ x y)))

(letrec-syntax ((or-macro (lambda (stx)
                            (syntax-case stx ()
                              ((_) (syntax #f))
                              ((_ x) (syntax x))
                              ((_ x y ...)
                               (syntax (let ((t x)) (if t t (or-macro y ...)))))))))
  (or-macro #f #f 42))

(let-syntax ((define-inline (lambda (stx)
                              (syntax-case stx ()
                                ((_ (name args ...) body)
                                 (syntax
                                   (define (name args ...) body)))))))
  (define-inline (square x) (* x x))
  (square 5))

(let-syntax ((unless-macro (lambda (stx)
                             (syntax-case stx ()
                               ((_ test body ...)
                                (syntax (if (not test) (begin body ...))))))))
  (define my-val 0)
  (unless-macro (= my-val 1) (set! my-val 1)))

(let-syntax ((define-counter (lambda (stx)
                               (syntax-case stx ()
                                 ((_ name inc reset)
                                  (syntax
                                    (begin
                                      (define name 0)
                                      (define (inc) (set! name (+ name 1)))
                                      (define (reset) (set! name 0)))))))))
  (define-counter count count-inc count-reset)
  (count-inc)
  (count-inc)
  count)

(letrec-syntax ((loop-macro (lambda (stx)
                              (syntax-case stx ()
                                ((_ 0 body ...)
                                 (syntax (begin body ...)))
                                ((_ n body ...)
                                 (syntax (if (> n 0)
                                           (begin body ... (loop-macro (- n 1) body ...))
                                           (void))))))))
  (loop-macro 3 (display "hi ") (newline)))
