(display "=== 特殊形式验证 (无 quasiquote) ===\n")
(display "quote: ") (display (quote (1 2 3))) (newline)
(display "if: ") (display (if #t "yes" "no")) (newline)
(display "begin: ") (display (begin (+ 1 2) (- 5 3))) (newline)
(display "lambda: ") (display ((lambda (x) (* x 2)) 5)) (newline)
(display "define:") (define _x 42) (display _x) (newline)
(display "set!:") (set! _x 99) (display _x) (newline)
(display "cond: ") (display (cond ((> 3 2) "big") (else "small"))) (newline)
(display "case: ") (display (case 2 ((1) "one") ((2) "two"))) (newline)
(display "and: ") (display (and 1 2 3)) (newline)
(display "or: ") (display (or #f 42)) (newline)
(display "when: ") (display (when #t 10)) (newline)
(display "unless: ") (display (unless #f 20)) (newline)
(display "let: ") (display (let ((x 5)) (+ x 3))) (newline)
(display "let*: ") (display (let* ((x 3) (y (* x 2))) y)) (newline)
(display "letrec: ") (display (letrec ((f (lambda (n) (if (< n 2) 1 (* n (f (- n 1))))))) (f 5))) (newline)
(display "do: ") (display (do ((i 0 (+ i 1))) ((= i 3) 'done) (display i))) (newline)
(display "call/cc: ") (display (call/cc (lambda (k) (k 42)))) (newline)
(display "define-values:") (define-values (a b) (values 1 2)) (display a) (display b) (newline)
(display "define-syntax:") (define-syntax my-when (syntax-rules () ((_ t b ...) (if t (begin b ...))))) (display (my-when #t 42)) (newline)
(display "let-syntax:") (let-syntax ((twice (syntax-rules () ((_ x) (* 2 x))))) (display (twice 5))) (newline)
(display "case-lambda:") (display ((case-lambda ((a) (* a a)) ((a b) (+ a b))) 3)) (newline)
(display "parameterize:") (define p (make-parameter 0)) (parameterize ((p 5)) (display (p))) (display "|") (display (p)) (newline)
(display "dynamic-wind:") (display (dynamic-wind (lambda () 'b) (lambda () 77) (lambda () 'a))) (newline)
(display "=== ALL PASS ===\n")
