;; test-edge-cases.scm — 边界条件与边缘测试
;; 覆盖空值、空列表、类型边界、特殊情况

(define (check label actual expected)
  (if (equal? actual expected)
      (begin (display "[PASS] ") (display label) (newline))
      (begin (display "[FAIL] ") (display label)
             (display "  expected: ") (write expected)
             (display "  actual: ") (write actual) (newline))))

(define (try-catch thunk fallback)
  (guard (exn (else fallback)) (thunk)))

(display "\n===== 1. 空列表操作 =====\n")
(check "car of non-pair error" (try-catch (lambda () (car '())) 'error) 'error)
(check "cdr of non-pair error" (try-catch (lambda () (cdr '())) 'error) 'error)
(check "null? '()" (null? '()) #t)
(check "null? (list)" (null? (list)) #t)
(check "pair? '()" (pair? '()) #f)
(check "list? '()" (list? '()) #t)
(check "length '()" (length '()) 0)
(check "reverse '()" (reverse '()) '())
(check "append '() '()" (append '() '()) '())
(check "append '() '(1)" (append '() '(1)) '(1))
(check "append '(1) '()" (append '(1) '()) '(1))
(check "map on empty" (map + '() '()) '())
(check "filter on empty" (filter even? '()) '())
(check "member not found" (member 'z '(a b c)) #f)
(check "assoc not found" (assoc 'z '((a . 1))) #f)

(display "\n===== 2. 零值 =====\n")
(check "0 is zero?" (zero? 0) #t)
(check "1 is zero?" (zero? 1) #f)
(check "positive? 0" (positive? 0) #f)
(check "negative? 0" (negative? 0) #f)
(check "positive? 1" (positive? 1) #t)
(check "negative? -1" (negative? -1) #t)
(check "even? 0" (even? 0) #t)
(check "odd? 0" (odd? 0) #f)
(check "- 0" (- 0) 0)
(check "/ 0 1" (/ 0 1) 0)
(check "expt 0 0" (expt 0 0) 1)
(check "expt 0 5" (expt 0 5) 0)
(check "gcd 0 5" (gcd 0 5) 5)
(check "gcd 0 0" (gcd 0 0) 0)
(check "lcm 0 5" (lcm 0 5) 0)

(display "\n===== 3. 单元素列表 =====\n")
(check "car of single" (car '(42)) 42)
(check "cdr of single" (cdr '(42)) '())
(check "length 1" (length '(a)) 1)
(check "reverse single" (reverse '(a)) '(a))
(check "map single" (map (lambda (x) (* x 2)) '(5)) '(10))
(check "filter single pass" (filter even? '(2)) '(2))
(check "filter single fail" (filter even? '(1)) '())
(check "member single found" (member 'a '(a)) '(a))
(check "member single not found" (member 'b '(a)) #f)

(display "\n===== 4. 大数/整数边界 =====\n")
(check "max int 32bit" (* 65536 65536) 4294967296)
(check "min neg int" (- 0 2147483648) -2147483648)
(check "add extra large" (+ 9999999999999999 1) 10000000000000000)
(check "mul large" (* 123456789 987654321) 121932631112635269)
(check "expt large" (expt 10 20) 100000000000000000000)

(display "\n===== 5. 字符与字符串边界 =====\n")
(check "char->integer A" (char->integer #\A) 65)
(check "integer->char 65" (integer->char 65) #\A)
(check "char->integer roundtrip" (integer->char (char->integer #\Z)) #\Z)
(check "string-length 0" (string-length "") 0)
(check "string-length 1" (string-length "a") 1)
(check "string-ref" (string-ref "abc" 1) #\b)
(check "substring full" (substring "hello" 0 5) "hello")
(check "substring middle" (substring "hello" 1 4) "ell")
(check "substring zero" (substring "hello" 2 2) "")
(check "string->list all" (string->list "abc") '(#\a #\b #\c))
(check "list->string" (list->string '(#\h #\i)) "hi")
(check "string-append none" (string-append) "")
(check "string-append single" (string-append "a") "a")
(check "string-copy then equal?" (let ((s (string-copy "abc"))) (equal? s "abc")) #t)
(check "string-fill! all" (let ((s (string-copy "abc"))) (string-fill! s #\z) s) "zzz")
(check "string-fill! empty" (let ((s (string-copy ""))) (string-fill! s #\z) s) "")

(display "\n===== 6. 向量边界 =====\n")
(check "vector-length 0" (vector-length #()) 0)
(check "vector-length 1" (vector-length #(a)) 1)
(check "vector-ref" (vector-ref #(a b c) 1) 'b)
(check "vector->list" (vector->list #(a b c)) '(a b c))
(check "list->vector" (list->vector '(a b c)) #(a b c))
(check "vector-append" (vector-append #(1 2) #(3 4)) #(1 2 3 4))
(check "vector-fill!" (let ((v (vector 1 2 3))) (vector-fill! v 'x) v) #(x x x))
(check "vector-map empty" (vector-map + #() #()) #())
(check "vector-map" (vector-map + #(1 2) #(10 20)) #(11 22))

(display "\n===== 7. cons / improper list =====\n")
(check "cons pair" (cons 1 2) '(1 . 2))
(check "cons list" (cons 1 '(2 3)) '(1 2 3))
(check "car conspair" (car (cons 1 2)) 1)
(check "cdr conspair" (cdr (cons 1 2)) 2)
(check "pair? conspair" (pair? (cons 1 2)) #t)
(check "list? conspair" (list? (cons 1 2)) #f)
(check "list? proper list" (list? (cons 1 (cons 2 '()))) #t)
(check "dotted cdr" (cdr '(a . b)) 'b)
(check "dotted pair? check" (pair? '(a . b)) #t)

(display "\n===== 8. 算术边界 =====\n")
(check "quotient 10 3" (quotient 10 3) 3)
(check "remainder 10 3" (remainder 10 3) 1)
(check "modulo 10 3" (modulo 10 3) 1)
(check "quotient -10 3" (quotient -10 3) -3)
(check "remainder -10 3" (remainder -10 3) -1)
(check "modulo -10 3" (modulo -10 3) 2)
(check "floor-quotient 10 3" (floor-quotient 10 3) 3)
(check "floor-remainder 10 3" (floor-remainder 10 3) 1)
(check "floor-quotient -10 3" (floor-quotient -10 3) -4)
(check "floor-remainder -10 3" (floor-remainder -10 3) 2)
(check "truncate-quotient 10 3" (truncate-quotient 10 3) 3)
(check "truncate-remainder 10 3" (truncate-remainder 10 3) 1)
(check "truncate-quotient -10 3" (truncate-quotient -10 3) -3)
(check "truncate-remainder -10 3" (truncate-remainder -10 3) -1)

(display "\n===== 9. 多参算术 =====\n")
(check "+ single" (+ 42) 42)
(check "+ 3 args" (+ 1 2 3) 6)
(check "+ 4 args" (+ 1 2 3 4) 10)
(check "* no args" (*) 1)
(check "* single" (* 5) 5)
(check "* 4 args" (* 2 3 4 5) 120)
(check "- single negates" (- 5) -5)
(check "- 3 args" (- 10 3 2) 5)

(display "\n===== 10. 布尔与eq?边界 =====\n")
(check "eq? same symbol" (eq? 'a 'a) #t)
(check "eq? diff symbol" (eq? 'a 'b) #f)
(check "eq? same int" (eq? 42 42) #t)
(check "eq? diff int" (eq? 42 43) #f)
(check "equal? list same" (equal? '(1 2 3) '(1 2 3)) #t)
(check "equal? list diff" (equal? '(1 2 3) '(1 2 4)) #f)
(check "equal? nested" (equal? '((a) (b)) '((a) (b))) #t)
(check "equal? dotted" (equal? '(1 . 2) '(1 . 2)) #t)
(check "boolean? #t" (boolean? #t) #t)
(check "boolean? #f" (boolean? #f) #t)
(check "boolean? 0" (boolean? 0) #f)
(check "not #t" (not #t) #f)
(check "not #f" (not #f) #t)
(check "not 0" (not 0) #f)

(display "\n===== 11. 环境与定义边界 =====\n")
(check "define and overwrite" (begin (define x 1) (define x 2) x) 2)
(check "set! overwrites" (begin (define y 10) (set! y 20) y) 20)
(check "define lambda" (begin (define (f x) (+ x 1)) (f 41)) 42)

(display "\n===== 12. 多值与call/cc =====\n")
(check "values single" (call-with-values (lambda () (values 42)) list) '(42))
(check "values two" (call-with-values (lambda () (values 1 2)) list) '(1 2))
(check "values three" (call-with-values (lambda () (values 1 2 3)) list) '(1 2 3))
(check "call/cc escape" (call/cc (lambda (k) (+ 1 (k 99)) 2)) 99)
(check "call/cc normal" (call/cc (lambda (k) (+ 1 2))) 3)

(display "\n===== 13. 条件式真值 =====\n")
(check "if with #t" (if #t 'yes 'no) 'yes)
(check "if with #f" (if #f 'yes 'no) 'no)
(check "if with 0" (if 0 'yes 'no) 'yes)    ; 0 is truthy
(check "if with empty list" (if '() 'yes 'no) 'yes)  ; '() is truthy
(check "if with #f only false" (if #f 'yes 'no) 'no)
(check "if no else" (if #t 42) 42)
(check "if no else false" (if #f 42) (if #f #f))
(check "when true" (when #t 42) 42)
(check "when false" (begin (when #f (display "x")) 'ok) 'ok)
(check "unless false" (unless #f 42) 42)
(check "unless true" (begin (unless #t (display "x")) 'ok) 'ok)

(display "\n===== 14. 尾递归混合边界 =====\n")
;; 某些尾调用涉及混合类型
(define (mix-tail n acc)
  (if (= n 0) acc
      (if (even? n)
          (mix-tail (- n 1) (cons n acc))
          (mix-tail (- n 1) (cons (* n n) acc)))))
(check "mix-tail 100 length" (length (mix-tail 100 '())) 100)
(check "mix-tail contains 100" (if (member 100 (mix-tail 100 '())) #t #f) #t)
(check "mix-tail contains 9801" (if (member 9801 (mix-tail 100 '())) #t #f) #t)

(display "\n===== 15. 空begin/不返回 =====\n")
(check "begin empty" (begin) (if #f #f))
(check "begin single" (begin 42) 42)
(check "begin multiple" (begin 1 2 3) 3)
(check "begin with define" (begin (define z 99) z) 99)
(check "begin side-effect order" (let ((x 1)) (begin (set! x 2) (set! x 3) x)) 3)

(display "\n===== 16. 类型谓词 =====\n")
(check "pair? proper" (pair? '(1 2)) #t)
(check "pair? improper" (pair? '(1 . 2)) #t)
(check "pair? empty" (pair? '()) #f)
(check "symbol? sym" (symbol? 'hello) #t)
(check "symbol? string" (symbol? "hello") #f)
(check "number? int" (number? 42) #t)
(check "number? fraction" (number? 1/3) #t)
(check "string? str" (string? "hello") #t)
(check "string? sym" (string? 'hello) #f)
(check "vector? vec" (vector? #(1 2)) #t)
(check "vector? list" (vector? '(1 2)) #f)
(check "char? char" (char? #\a) #t)
(check "char? integer" (char? 65) #f)
(check "procedure? lambda" (procedure? (lambda (x) x)) #t)
(check "procedure? builtin" (procedure? +) #t)
(check "procedure? symbol" (procedure? 'car) #f)
(check "procedure? number" (procedure? 42) #f)

(display "\n===== 17. 列表组合原语 =====\n")
(check "cons* 2 args" (cons* 1 2) '(1 . 2))
(check "cons* 3 args" (cons* 1 2 3) '(1 2 . 3))
(check "cons* 1 arg" (cons* 42) 42)
(check "list* 2 args" (list* 1 '(2)) '(1 2))
(check "list* 3 args" (list* 1 2 '(3 4)) '(1 2 3 4))
(check "make-list 0" (make-list 0 'x) '())
(check "make-list 3" (make-list 3 'x) '(x x x))
(check "list-tabulate 0" (list-tabulate 0 values) '())
(check "iota 0" (iota 0) '())
(check "iota 1" (iota 1) '(0))

(display "\n===== 18. 转换往返 =====\n")
(check "list->vector->list" (vector->list (list->vector '(a b c))) '(a b c))
(check "string->list->string" (list->string (string->list "abc")) "abc")
(check "symbol->string->symbol" (string->symbol (symbol->string 'hello)) 'hello)
(check "number->string->roundtrip" (string->number (number->string 12345)) 12345)

(display "\n===== 19. 算术语义边界 =====\n")
(check "/ 2 4 reduces" (/ 2 4) 1/2)
(check "/ 10 5" (/ 10 5) 2)
(check "/ 1 2 3" (/ 1 2 3) 1/6)
(check "abs 0" (abs 0) 0)
(check "abs -5" (abs -5) 5)
(check "abs 5" (abs 5) 5)
(check "floor 3.7" (floor 3.7) 3.0)
(check "ceiling 3.1" (ceiling 3.1) 4.0)
(check "truncate 3.7" (truncate 3.7) 3.0)
(check "round 3.5" (round 3.5) 4.0)
(check "round 4.5" (round 4.5) 4.0)
(check "max single" (max 42) 42)
(check "min single" (min 42) 42)
(check "max 3 values" (max 1 5 3) 5)
(check "min 3 values" (min 3 1 5) 1)

(display "\n===== 20. eqv? 语义 =====\n")
(check "eqv? same int" (eqv? 42 42) #t)
(check "eqv? diff int" (eqv? 42 43) #f)
(check "eqv? same char" (eqv? #\a #\a) #t)
(check "eqv? same bool" (eqv? #t #t) #t)
(check "eqv? same symbol" (eqv? 'a 'a) #t)
(check "eqv? pairs (same obj only)" (let ((p (cons 1 2))) (eqv? p p)) #t)
(check "eqv? pairs diff obj" (eqv? (cons 1 2) (cons 1 2)) #f)

(display "\n===== 21. 字符串复杂操作 =====\n")
(check "string-ref" (string-ref "abc" 2) #\c)
(check "string-set!" (let ((s (string-copy "abc"))) (string-set! s 1 #\X) s) "aXc")
(check "string-ci=? same" (string-ci=? "ABC" "abc") #t)
(check "string-ci=? diff" (string-ci=? "ABC" "abd") #f)
(check "string-ci<? true" (string-ci<? "abc" "ABD") #t)
(check "string-ci>? true" (string-ci>? "ABD" "abc") #t)
(check "string-upcase" (string-upcase "Hello") "HELLO")
(check "string-downcase" (string-downcase "Hello") "hello")
(check "string-foldcase" (string-foldcase "Hello") "hello")
(check "substring start=0" (substring "hello" 0 3) "hel")
(check "substring end=len" (substring "hello" 2 5) "llo")

(display "\n===== 22. 生成器边界 =====\n")
(check "generator->list range" (generator->list (make-range-generator 0 3)) '(0 1 2))
(check "generator->list empty" (generator->list (make-range-generator 0 0)) '())

(display "\n===== 全部边界测试完成 =====\n")
