;; test-boot-sugar-edge.scm
;; Edge-case and boundary tests for boot-sugar.scm macros (Phase 6-10)

(display "=== λ (lambda alias) ===\n")
(test-equal "λ single arg" 6 ((λ (x) (+ x 1)) 5))
(test-equal "λ multi arg" 12 ((λ (a b) (* a b)) 3 4))
(test-equal "λ rest arg" 6 ((λ (a . rest) (apply + a rest)) 1 2 3))
(test-equal "λ zero arg" 42 ((λ () 42)))
(test-equal "λ body multi" 10 ((λ (x) (set! x (* x 2)) x) 5))

(display "=== dec ===\n")
(let ((x 10)) (dec x) (test-equal "dec default" 9 x))
(let ((x 10)) (dec x 3) (test-equal "dec by n" 7 x))
(let ((x 0)) (dec x) (test-equal "dec zero" -1 x))
(let ((x -5)) (dec x -2) (test-equal "dec negative" -3 x))

(display "=== ->> thread-last ===\n")
(test-equal "->> single" '(1 2 3 4 5) (->> 5 (list 1 2 3 4)))
(test-equal "->> chain" '(6 4 2) (->> '(1 2 3) (map (λ (x) (* x 2))) (reverse)))
(test-equal "->> identity" 42 (->> 42))
(test-equal "->> zero-arg f" '(1 2 3) (->> '(3 1 2) (sort <)))
(test-equal "->> nested apply" '(2 3 1 5) (->> 5 (list 1) (append '(2 3))))

(display "=== some-> (short-circuit threading) ===\n")
(test-equal "some-> pass" 6 (some-> 2 (λ (x) (* x 3))))
(test-equal "some-> chain" 7 (some-> 2 (λ (x) (* x 3)) (λ (x) (+ x 1))))
(test-equal "some-> short-circuit" #f (some-> #f (λ (x) (* x 3))))
(test-equal "some-> identity" 42 (some-> 42))
(test-equal "some-> chain truthy" 21 (some-> 10 (λ (x) (and (> x 5) (* x 2))) (λ (x) (+ x 1))))

(display "=== doto ===\n")
(let ((v (vector 1 2 3)))
  (doto v (vector-set! 0 10) (vector-set! 1 20))
  (test-equal "doto set!" 10 (vector-ref v 0)))
(let ((v (vector 1 2 3)))
  (test-equal "doto returns val" v (doto v)))
(let ((lst (list 1 2 3)))
  (doto lst (set-car! 99))
  (test-equal "doto set-car!" 99 (car lst)))

(display "=== and=> ===\n")
(test-equal "and=> pass" 10 (and=> 5 (λ (x) (* x 2))))
(test-equal "and=> fail" #f (and=> #f (λ (x) (* x 2))))
(test-equal "and=> chain" 11 (and=> 5 (λ (x) (if (> x 3) (* x 2) #f)) (λ (x) (+ x 1))))
(test-equal "and=> chain fail" #f (and=> 2 (λ (x) (if (> x 3) (* x 2) #f)) (λ (x) (+ x 1))))
(test-equal "and=> single" 42 (and=> 42 values))

(display "=== assert ===\n")
(test-equal "assert pass" (if #f #f) (assert #t))
(test-equal "assert pass with msg" (if #f #f) (assert (< 1 2) "should work"))
(let ((caught #f))
  (guard (exn (else (set! caught #t))) (assert #f))
  (test-equal "assert fail raises" #t caught))

(display "=== if-let / when-let ===\n")
(test-equal "if-let then" 42 (if-let (x 42) x))
(test-equal "if-let else" 'no (if-let (x #f) 'yes 'no))
(test-equal "if-let no else" (if #f #f) (if-let (x #f) 'yes))
(test-equal "when-let true" 43 (when-let (x 42) (+ x 1)))
(test-equal "when-let false" #f (when-let (x #f) 'never))

(display "=== ?? (nil-coalescing) ===\n")
(test-equal "?? first truthy" 42 (?? 42 'default))
(test-equal "?? fallback" 'default (?? #f 'default))
(test-equal "?? empty string" "" (?? "" 'default))
(test-equal "?? zero" 0 (?? 0 'default))
(test-equal "?? nested" 1 (?? (?? #f 1) 2))

(display "=== ??= (nil-coalescing assign) ===\n")
(let ((x #f)) (??= x 42) (test-equal "??= assign" 42 x))
(let ((x 10)) (??= x 99) (test-equal "??= keep" 10 x))

(display "=== do-while ===\n")
(let ((i 0) (result '()))
  (do-while (set! result (cons i result)) (set! i (+ i 1)) (< i 5))
  (test-equal "do-while reverse" '(0 1 2 3 4) (reverse result)))
(let ((x #f))
  (do-while (set! x 'ran) #f)
  (test-equal "do-while body runs once" 'ran x))

(display "=== nameof ===\n")
(test-equal "nameof simple" 'x (nameof x))
(test-equal "nameof long" 'my-variable (nameof my-variable))
(test-equal "nameof with ?" 'pair? (nameof pair?))

(display "=== cond? ===\n")
(test-equal "cond? true" 'yes (cond? #t 'yes 'no))
(test-equal "cond? false" 'no (cond? #f 'yes 'no))
(test-equal "cond? nested" 'b (cond? (> 3 1) (cond? #f 'a 'b) 'c))

(display "=== try-finally ===\n")
(let ((side-effect #f))
  (try-finally (set! side-effect 1) (set! side-effect 2))
  (test-equal "try-finally runs cleanup" 2 side-effect))
(let ((order '()))
  (try-finally (set! order (cons 'body order)) (set! order (cons 'cleanup order)))
  (test-equal "try-finally body before cleanup" '(body cleanup) (reverse order)))

(display "=== try-catch ===\n")
(test-equal "try-catch normal" 3 (try-catch (+ 1 2) (exn (display exn))))
(test-equal "try-catch exception" 'caught (try-catch (error "oops") (exn 'caught)))

(display "=== scope-exit ===\n")
(let ((x 'before))
  (scope-exit (set! x 'after) (set! x 'during))
  (test-equal "scope-exit runs on exit" 'after x))
(let ((order '()))
  (scope-exit (set! order (cons 'exit order)) (set! order (cons 'body order)))
  (test-equal "scope-exit order" '(body exit) (reverse order)))

(display "=== scope-success ===\n")
(let ((x 'before))
  (scope-success (set! x 'after) (set! x 'during))
  (test-equal "scope-success runs cleanup" 'after x))
(test-equal "scope-success returns body" 42 (scope-success (set! x 'cleanup) 42))

(display "=== times ===\n")
(let ((sum 0))
  (times 5 (set! sum (+ sum i)))
  (test-equal "times 0..4 sum" 10 sum))
(let ((result '()))
  (times 3 (set! result (cons i result)))
  (test-equal "times produces 0,1,2" '(0 1 2) (reverse result)))
(let ((count 0))
  (times 0 (set! count (+ count 1)))
  (test-equal "times 0 no loop" 0 count))

(display "=== static-if ===\n")
(test-equal "static-if true" 'a (static-if #t 'a 'b))
(test-equal "static-if false" 'b (static-if #f 'a 'b))
(test-equal "static-if nested" 'a (static-if (static-if #t #t #f) 'a 'b))

(display "=== tap ===\n")
(test-equal "tap identity" 42 (tap 42))
(let ((side-effect '()))
  (let ((result (tap 10 (λ (x) (set! side-effect x)))))
    (test-equal "tap side-effect" 10 side-effect)
    (test-equal "tap returns original" 10 result)))

(display "=== lazy ===\n")
(define lazy-val (lazy (+ 1 2 3)))
(test-equal "lazy returns promise" #t (promise? lazy-val))
(test-equal "lazy force" 6 (force lazy-val))
(test-equal "lazy idempotent" 6 (force lazy-val))

(display "=== memo ===\n")
(let ((call-count 0))
  (memo (get-val) (set! call-count (+ call-count 1)) 42)
  (test-equal "memo first call" 42 (get-val))
  (test-equal "memo second call" 42 (get-val))
  (test-equal "memo only calls once" 1 call-count))

(display "=== once ===\n")
(define once-call (once (display "runs once") 99))
(test-equal "once returns thunk" #t (procedure? once-call))
(test-equal "once first call" 99 (once-call))
(test-equal "once second call void" (if #f #f) (once-call))
(test-equal "once third call void" (if #f #f) (once-call))

(display "=== either ===\n")
(test-equal "either true" 1 (either #t 1 2))
(test-equal "either false" 2 (either #f 1 2))
(test-equal "either nested" 1 (either (either #f #f #t) 1 2))

(display "=== tuple ===\n")
(test-equal "tuple 3 values" '(1 2 3) (call-with-values (λ () (tuple 1 2 3)) list))
(test-equal "tuple empty" '() (call-with-values (λ () (tuple)) list))
(test-equal "tuple single" '(42) (call-with-values (λ () (tuple 42)) list))

(display "=== enumerate ===\n")
(let ((pairs '()))
  (enumerate (i v '(a b c)) (set! pairs (cons (list i v) pairs)))
  (test-equal "enumerate reverse" '((0 a) (1 b) (2 c)) (reverse pairs)))
(let ((pairs '()))
  (enumerate (i v '()) (set! pairs (cons (list i v) pairs)))
  (test-equal "enumerate empty" '() pairs))

(display "=== $ (apply) ===\n")
(test-equal "$ simple" 3 ($ + 1 2))
(test-equal "$ multi" '(1 2 3) ($ list 1 2 3))
(test-equal "$ nested" 1 ($ car ($ list 1 2 3)))

(display "=== o (compose) ===\n")
(define add1 (λ (x) (+ x 1)))
(define double (λ (x) (* x 2)))
(test-equal "o single" 6 ((o add1) 5))
(test-equal "o double" 12 ((o double add1) 5))
(test-equal "o triple" 14 ((o double add1 double) 3))
(test-equal "o identity" 42 ((o values) 42))

(display "=== cond-> (conditional threading) ===\n")
(test-equal "cond-> none" 5 (cond-> 5))
(test-equal "cond-> true" 10 (cond-> 5 (#t (λ (x) (* x 2)))))
(test-equal "cond-> false" 5 (cond-> 5 (#f (λ (x) (* x 2)))))
(test-equal "cond-> mixed" 7 (cond-> 5 (#t (λ (x) (* x 2))) (#f (λ (x) (+ x 1))) (#t (λ (x) (- x 3)))))

(display "=== as-> (named threading) ===\n")
(test-equal "as-> identity" 5 (as-> 5 x x))
(test-equal "as-> simple" 6 (as-> 5 x (+ x 1)))
(test-equal "as-> chain" 12 (as-> 5 x (+ x 1) y (* y 2)))
(test-equal "as-> nested" '(6 4 2) (as-> '(1 2 3) x (map (λ (n) (* n 2)) x) y (reverse y)))

(display "=== juxt (juxtaposition) ===\n")
(define j1 (juxt add1))
(define j2 (juxt add1 double))
(define j3 (juxt add1 double (λ (x) (* x x))))
(test-equal "juxt single" 6 (j1 5))
(test-equal "juxt two" '(6 10) (j2 5))
(test-equal "juxt three" '(6 10 25) (j3 5))

(display "=== also ===\n")
(let ((side '()))
  (test-equal "also returns x" 42 (also 42 (set! side 'ran)))
  (test-equal "also side effect" 'ran side))
(let ((acc '()))
  (also 1 (set! acc (cons 'a acc)) (set! acc (cons 'b acc)))
  (test-equal "also multi side" '(a b) (reverse acc)))

(display "=== unwrap / expect ===\n")
(test-equal "unwrap truthy" 42 (unwrap 42))
(let ((caught #f))
  (guard (exn (else (set! caught #t))) (unwrap #f))
  (test-equal "unwrap #f raises" #t caught))
(test-equal "expect truthy" 42 (expect 42 "msg"))
(let ((caught #f))
  (guard (exn (else (set! caught #t))) (expect #f "expected"))
  (test-equal "expect #f raises" #t caught))

(display "=== with-chain ===\n")
(test-equal "with-chain do body" 42 (with-chain (x 42) do x))
(test-equal "with-chain do else" 'fallback (with-chain (x #f) do x else 'fallback))
(test-equal "with-chain do body multi" 11 (with-chain (x 10) do (set! x (+ x 1)) x))
(test-equal "with-chain fallback" 'always (with-chain (x #f) do 'never else 'always))

(display "=== all? / any? ===\n")
(test-equal "all? true" #t (all? even? '(2 4 6)))
(test-equal "all? false" #f (all? even? '(2 3 4)))
(test-equal "all? empty" #t (all? even? '()))
(test-equal "any? true" #t (any? odd? '(2 3 4)))
(test-equal "any? false" #f (any? odd? '(2 4 6)))
(test-equal "any? empty" #f (any? even? '()))

(display "=== prog1 / prog2 ===\n")
(test-equal "prog1" 1 (prog1 1 2 3))
(test-equal "prog1 side effect" 0 (let ((x 0)) (prog1 x (set! x 1))))
(test-equal "prog2" 2 (prog2 1 2 3))
(test-equal "prog2 side" 1 (let ((x 0) (y 1)) (prog2 (set! x 1) y (set! y 2))))

(display "=== value-> ===\n")
(define add1 (λ (x) (+ x 1)))
(define double (λ (x) (* x 2)))
(test-equal "value-> identity" 42 (value-> 42))
(test-equal "value-> chain" 11 (value-> 5 double add1))
(test-equal "value-> multi arg" '(3 1 2) (value-> 3 (list 1 2)))

(display "=== nlet (named let) ===\n")
(test-equal "nlet factorial" 120 (nlet fact ((n 5) (acc 1)) (if (= n 0) acc (fact (- n 1) (* acc n)))))
(test-equal "nlet zero" 55 (nlet loop ((i 0) (sum 0)) (if (> i 10) sum (loop (+ i 1) (+ sum i)))))
(test-equal "nlet range" '(3 2 1) (nlet rev ((lst '(1 2 3)) (acc '())) (if (null? lst) acc (rev (cdr lst) (cons (car lst) acc)))))

(display "=== let1 ===\n")
(test-equal "let1 simple" 42 (let1 x 42 x))
(test-equal "let1 expr" 9 (let1 x (+ 1 2) (* x 3)))
(test-equal "let1 nested" 30 (let1 x 10 (let1 y 20 (+ x y))))

(display "=== letr (letrec shortcut) ===\n")
(test-equal "letr mutual" #t (letr ((even? (λ (n) (if (= n 0) #t (odd? (- n 1)))))
                                    (odd? (λ (n) (if (= n 0) #f (even? (- n 1))))))
                               (even? 6)))
(test-equal "letr odd" #f (letr ((even? (λ (n) (if (= n 0) #t (odd? (- n 1)))))
                                 (odd? (λ (n) (if (= n 0) #f (even? (- n 1))))))
                            (odd? 6)))

(display "=== tf (ternary if) ===\n")
(test-equal "tf true" 'a (tf #t 'a 'b))
(test-equal "tf false" 'b (tf #f 'a 'b))
(test-equal "tf nested" 'b (tf (> 3 1) (tf #f 'a 'b) 'c))

(display "=== true? / false? ===\n")
(test-equal "true? #t" #t (true? #t))
(test-equal "true? 42" #f (true? 42))
(test-equal "true? #f" #f (true? #f))
(test-equal "false? #f" #t (false? #f))
(test-equal "false? 0" #f (false? 0))
(test-equal "false? '()" #f (false? '()))

(display "\n;; === All boot-sugar edge tests complete ===\n")
