;; test-morphic-ic.scm — Selective Morphic IC 缓存正确性验证
;; 验证不可变标准原语安全内联缓存 + 用户变量动态查找 + 内联优化

(define (check label actual expected)
  (if (equal? actual expected)
      (begin (display "[PASS] ") (display label) (newline))
      (begin (display "[FAIL] ") (display label)
             (display "  expected: ") (write expected)
             (display "  actual: ") (write actual) (newline))))

(display "\n===== 1. 不可变原语 IC 缓存 — JIT 编译后正确 =====\n")
;; 这些函数被 JIT 编译时使用 Morphic IC 缓存 _IMMUTABLE_PRIMITIVES
(define (ic-cons x y) (cons x y))
(define (ic-car x) (car x))
(define (ic-cdr x) (cdr x))
(define (ic-null? x) (null? x))
(define (ic-pair? x) (pair? x))
(define (ic-list . args) (apply list args))
(define (ic-append a b) (append a b))
(define (ic-reverse x) (reverse x))
(define (ic-length x) (length x))
(define (ic-map f lst) (map f lst))
(define (ic-eq? a b) (eq? a b))
(define (ic-boolean? x) (boolean? x))
(define (ic-symbol? x) (symbol? x))
(define (ic-number? x) (number? x))
(define (ic-string? x) (string? x))
(define (ic-vector? x) (vector? x))
(define (ic-char? x) (char? x))
(define (ic-memq x lst) (memq x lst))
(define (ic-member x lst) (member x lst))
(define (ic-assq x alist) (assq x alist))

(check "ic-cons" (ic-cons 1 2) '(1 . 2))
(check "ic-car" (ic-car '(a b c)) 'a)
(check "ic-cdr" (ic-cdr '(a b c)) '(b c))
(check "ic-null? empty" (ic-null? '()) #t)
(check "ic-null? nonempty" (ic-null? '(1)) #f)
(check "ic-pair? pair" (ic-pair? '(1 . 2)) #t)
(check "ic-pair? empty" (ic-pair? '()) #f)
(check "ic-list" (ic-list 1 2 3) '(1 2 3))
(check "ic-append" (ic-append '(1 2) '(3 4)) '(1 2 3 4))
(check "ic-reverse" (ic-reverse '(1 2 3)) '(3 2 1))
(check "ic-length" (ic-length '(a b c d e)) 5)
(check "ic-map" (ic-map (lambda (x) (* x 2)) '(1 2 3)) '(2 4 6))
(check "ic-eq? same" (ic-eq? 'a 'a) #t)
(check "ic-eq? diff" (ic-eq? 'a 'b) #f)
(check "ic-boolean?" (ic-boolean? #t) #t)
(check "ic-symbol?" (ic-symbol? 'hello) #t)
(check "ic-number?" (ic-number? 42) #t)
(check "ic-string?" (ic-string? "abc") #t)
(check "ic-vector?" (ic-vector? #(1 2)) #t)
(check "ic-char?" (ic-char? #\a) #t)
(check "ic-memq found" (ic-memq 'b '(a b c)) '(b c))
(check "ic-memq not found" (ic-memq 'z '(a b c)) #f)
(check "ic-member" (ic-member 2 '(1 2 3)) '(2 3))
(check "ic-assq" (ic-assq 'a '((a . 1) (b . 2))) '(a . 1))

(display "\n===== 2. 用户变量的 set! 安全性 — 不被 IC 缓存 =====\n")
;; 用户自定义变量可能被 set! 修改，必须使用 env.lookup 不可缓存
(define my-fn list)
(check "my-fn before" (my-fn 1 2) '(1 2))
(set! my-fn cons)
(check "my-fn after set!" (my-fn 1 2) '(1 . 2))

(define my-val 42)
(check "my-val before" my-val 42)
(set! my-val 100)
(check "my-val after set!" my-val 100)

(define my-car car)
(check "my-car before" (my-car '(a b)) 'a)
(set! my-car cdr)
(check "my-car after set!" (my-car '(a b)) '(b))

(display "\n===== 3. 算术内联优化 =====\n")
(define (ic-add . args) (apply + args))
(define (ic-sub . args) (apply - args))
(define (ic-mul . args) (apply * args))

(check "ic-add 2" (ic-add 10 20) 30)
(check "ic-add 3" (ic-add 1 2 3) 6)
(check "ic-sub" (ic-sub 10 3) 7)
(check "ic-mul" (ic-mul 2 3 4) 24)

;; 算术与不可变原语组合
(define (ic-compute x)
  (car (cons (* x 2) (cdr (cons x x)))))
(check "ic-compute inline" (ic-compute 10) 20)

(display "\n===== 4. 逻辑比较内联优化 =====\n")
(define (ic-lt a b) (< a b))
(define (ic-gt a b) (> a b))
(define (ic-le a b) (<= a b))
(define (ic-ge a b) (>= a b))
(define (ic-eq a b) (= a b))

(check "ic-lt true" (ic-lt 1 2) #t)
(check "ic-lt false" (ic-lt 3 2) #f)
(check "ic-gt" (ic-gt 5 3) #t)
(check "ic-le" (ic-le 3 3) #t)
(check "ic-ge" (ic-ge 4 3) #t)
(check "ic-eq" (ic-eq 5 5) #t)

(display "\n===== 5. 高阶函数使用 IC 缓存 =====\n")
(define (call-twice f x) (f (f x)))
(check "call-twice car/cdr" (call-twice cdr '(1 2 3 4)) '(3 4))
(check "call-twice null?" (call-twice cdr '()) '())
(check "call-twice add1" (call-twice (lambda (x) (+ x 1)) 5) 7)

(define (mymap f lst)
  (if (null? lst)
      '()
      (cons (f (car lst)) (mymap f (cdr lst)))))
(check "mymap car/cdr/cons/null?" (mymap (lambda (x) (+ x 1)) '(1 2 3)) '(2 3 4))

(display "\n===== 6. TCO 与 IC 缓存共存 =====\n")
(define (cnt-down n acc)
  (if (= n 0)
      (reverse acc)
      (cnt-down (- n 1) (cons n acc))))
(check "cnt-down 100000 length" (length (cnt-down 100000 '())) 100000)
(check "cnt-down 100000 car" (car (cnt-down 100000 '())) 100000)

(display "\n===== 7. 标准原语不可修改性 =====\n")
;; 尝试 set! 标准过程（Scheme 规范规定未定义行为，但运行时应安全）
(define saved-car car)
(set! car (lambda (x) (if (pair? x) (ic-cdr x) (error "no pair"))))
;; 现在 car 指向用户函数（不可缓存的原语），但应该还能工作
(check "set! car to user fn" (car '(1 2 3)) '(2 3))
;; 恢复
(set! car saved-car)
(check "car restored" (car '(1 2 3)) 1)

(display "\n===== 所有 Morphic IC 测试完成 =====\n")
