;; test-lang-all.scm — Verify prefix expressions across all language DSLs
;; Run: python3 miniscm.py test/test-lang-all.scm

(define (t label actual expected)
  (if (equal? actual expected)
      (begin (display "[PASS] ") (display label) (newline))
      (begin (display "[FAIL] ") (display label)
             (display "  expected: ") (write expected)
             (display "  actual: ") (write actual) (newline))))

(display "========================================\n")
(display "  Prefix expression smoke tests — All Languages\n")
(display "========================================\n\n")

(display "--- prefix expressions ---\n")
(t "(+ 2 3)" 5 (+ 2 3))
(t "(- 10 4)" 6 (- 10 4))
(t "(* 3 4)" 12 (* 3 4))
(t "(/ 10 2)" 5 (/ 10 2))
(t "(+ 2 (* 3 4))" 14 (+ 2 (* 3 4)))
(t "(* (+ 2 3) 4)" 20 (* (+ 2 3) 4))
(t "(expt x 2)" 25 ((lambda (x) (expt x 2)) 5))
(t "(set! x 42)" (if #f #f) (let ((x 0)) (set! x 42)))
(t "(< 2 3)" #t (< 2 3))
(t "(> 5 2)" #t (> 5 2))
(t "(<= 3 3)" #t (<= 3 3))
(t "(>= 3 5)" #f (>= 3 5))
(t "(not (= 2 3))" #t (not (= 2 3)))

(display "\n--- Python ---\n")
(load "scm/lang/lang-py.scm")
(t "py (+ n 1)" 6 ((lambda (n) (+ n 1)) 5))
(t "py (<= n 1)" #f ((lambda (n) (<= n 1)) 5))
(t "py (+ (* n 2) 1)" 11 ((lambda (n) (+ (* n 2) 1)) 5))

(display "\n--- JavaScript ---\n")
(load "scm/lang/lang-js.scm")
(t "js (+ i 1)" 4 ((lambda (i) (+ i 1)) 3))
(t "js (< i n)" #t ((lambda (i n) (< i n)) 3 10))
(t "js (+ 2 (* 3 4))" 14 (+ 2 (* 3 4)))

(display "\n--- C ---\n")
(load "scm/lang/lang-c.scm")
(t "c (/ (* n (+ n 1)) 2)" 55 ((lambda (n) (/ (* n (+ n 1)) 2)) 10))
(t "c (+ x 1)" 43 ((lambda (x) (+ x 1)) 42))
(t "c (< i 5)" #t ((lambda (i) (< i 5)) 3))

(display "\n--- Rust ---\n")
(load "scm/lang/lang-rust.scm")
(t "rs (/ (* n (+ n 1)) 2)" 55 ((lambda (n) (/ (* n (+ n 1)) 2)) 10))
(t "rs (<= n 1)" #f ((lambda (n) (<= n 1)) 3))
(t "rs (+ x 1)" 101 ((lambda (x) (+ x 1)) 100))

(display "\n--- Go ---\n")
(load "scm/lang/lang-go.scm")
(t "go (+ n 1)" 11 ((lambda (n) (+ n 1)) 10))
(t "go (<= n 1)" #t ((lambda (n) (<= n 1)) 1))
(t "go (< i 100)" #t ((lambda (i) (< i 100)) 50))

(display "\n--- Julia ---\n")
(load "scm/lang/lang-julia.scm")
(t "jl (/ (* n (+ n 1)) 2)" 15 ((lambda (n) (/ (* n (+ n 1)) 2)) 5))
(t "jl (* x 2)" 20 ((lambda (x) (* x 2)) 10))
(t "jl (+ i 1)" 4 ((lambda (i) (+ i 1)) 3))

(display "\n--- Elixir ---\n")
(load "scm/lang/lang-elixir.scm")
(t "ex (+ n 1)" 11 ((lambda (n) (+ n 1)) 10))
(t "ex (* x 2)" 14 ((lambda (x) (* x 2)) 7))
(t "ex (+ 5 3)" 8 (+ 5 3))

(display "\n--- Shell ---\n")
(load "scm/lang/lang-sh.scm")
(t "sh (+ x 1)" 6 ((lambda (x) (+ x 1)) 5))
(t "sh (< i 5)" #t ((lambda (i) (< i 5)) 3))
(t "sh (> x 0)" #f ((lambda (x) (> x 0)) -1))

(display "\n--- Kotlin ---\n")
(load "scm/lang/lang-kt.scm")
(t "kt (+ x 1)" 11 ((lambda (x) (+ x 1)) 10))
(t "kt (<= n 1)" #t ((lambda (n) (<= n 1)) 0))
(t "kt (< i 10)" #t ((lambda (i) (< i 10)) 5))
(t "kt (+ items 42)" 84 ((lambda (items) (+ items 42)) 42))

(display "\n--- Swift ---\n")
(load "scm/lang/lang-swift.scm")
(t "sw (/ (* n (+ n 1)) 2)" 55 ((lambda (n) (/ (* n (+ n 1)) 2)) 10))
(t "sw (+ x 1)" 43 ((lambda (x) (+ x 1)) 42))
(t "sw (+ (* a b) c)" 23 ((lambda (a b c) (+ (* a b) c)) 2 3 17))

(display "\n--- Lua ---\n")
(load "scm/lang/lang-lua.scm")
(t "lua (+ x 1)" 6 ((lambda (x) (+ x 1)) 5))
(t "lua (<= n 1)" #f ((lambda (n) (<= n 1)) 3))
(t "lua (+ i 1)" 101 ((lambda (i) (+ i 1)) 100))

(display "\n--- Haskell ---\n")
(load "scm/lang/lang-hs.scm")
(t "hs (+ x 1)" 43 ((lambda (x) (+ x 1)) 42))
(t "hs (* n 2)" 20 ((lambda (n) (* n 2)) 10))
(t "hs (+ (* x 2) 1)" 9 ((lambda (x) (+ (* x 2) 1)) 4))

(display "\n--- TypeScript ---\n")
(load "scm/lang/lang-ts.scm")
(t "ts (+ x 1)" 6 ((lambda (x) (+ x 1)) 5))
(t "ts (<= n 1)" #t ((lambda (n) (<= n 1)) 0))
(t "ts (< i n)" #t ((lambda (i n) (< i n)) 3 10))

(display "\n--- Java ---\n")
(load "scm/lang/lang-java.scm")
(t "java (/ (* n (+ n 1)) 2)" 55 ((lambda (n) (/ (* n (+ n 1)) 2)) 10))
(t "java (< i 10)" #t ((lambda (i) (< i 10)) 5))
(t "java (+ x 1)" 7 ((lambda (x) (+ x 1)) 6))

(display "\n--- Ruby ---\n")
(load "scm/lang/lang-rb.scm")
(t "rb (+ x 1)" 4 ((lambda (x) (+ x 1)) 3))
(t "rb (<= n 1)" #f ((lambda (n) (<= n 1)) 7))
(t "rb (* x 2)" 84 ((lambda (x) (* x 2)) 42))

(display "\n========================================\n")
(display "  Prefix expressions work across all languages\n")
(display "========================================\n")
