;; ============================================================
;; test-builtins-misc.scm
;; 测试 builtins_misc.py 全部函数
;; ============================================================

(define (check label actual expected)
  (if (equal? actual expected)
      (begin (display "[PASS] ") (display label) (newline))
      (begin (display "[FAIL] ") (display label)
             (display "  expected: ") (write expected)
             (display "  actual: ") (write actual) (newline))))

(check "add-hook! exists" (procedure? add-hook!) #t)
(check "add1" (add1 5) 6)
(check "alist-copy" (alist-copy '((a . 1))) '((a . 1)))
(check "any true" (any even? '(1 2 3)) #t)
(check "any false" (any even? '(1 3 5)) #f)
(check "append-map" (append-map (lambda (x) (list x x)) '(1 2 3)) '(1 1 2 2 3 3))
(check "append-reverse" (append-reverse '(3 2 1) '(4 5)) '(1 2 3 4 5))
(check "arithmetic-shift exists" (procedure? arithmetic-shift) #t)
(check "array-dimensions exists" (procedure? array-dimensions) #t)
(check "array-ref exists" (procedure? array-ref) #t)
(check "array-set! exists" (procedure? array-set!) #t)
(check "array? exists" (procedure? array?) #t)
(check "ascii? exists" (procedure? ascii?) #t)
(check "assoc" (assoc 'b '((a 1) (b 2) (c 3))) '(b 2))
(check "assq" (assq 'b '((a 1) (b 2) (c 3))) '(b 2))
(check "assv" (assv 2 '((1 a) (2 b) (3 c))) '(2 b))
(check "atom? 42" (atom? 42) #t)
(check "atom? pair" (atom? '(1)) #f)
(check "bimap-contains? exists" (procedure? bimap-contains?) #t)
(check "bimap-forward exists" (procedure? bimap-forward) #t)
(check "bimap-forward/default exists" (procedure? bimap-forward/default) #t)
(check "bimap-reverse exists" (procedure? bimap-reverse) #t)
(check "bimap-set! exists" (procedure? bimap-set!) #t)
(check "binary-heap-empty? exists" (procedure? binary-heap-empty?) #t)
(check "binary-heap-insert! exists" (procedure? binary-heap-insert!) #t)
(check "binary-heap-min exists" (procedure? binary-heap-min) #t)
(check "binary-heap-remove-min! exists" (procedure? binary-heap-remove-min!) #t)
(check "binary-heap-size exists" (procedure? binary-heap-size) #t)
(check "binomial" (binomial 10 3) 120)
(check "bits->integer exists" (procedure? bits->integer) #t)
(check "bitvector->list exists" (procedure? bitvector->list) #t)
(check "bitvector-append exists" (procedure? bitvector-append) #t)
(check "bitvector-copy exists" (procedure? bitvector-copy) #t)
(check "bitvector-length exists" (procedure? bitvector-length) #t)
(check "bitvector-ref exists" (procedure? bitvector-ref) #t)
(check "bitvector-set! exists" (procedure? bitvector-set!) #t)
(check "bitvector? exists" (procedure? bitvector?) #t)
(check "bitwise-and exists" (procedure? bitwise-and) #t)
(check "bitwise-if exists" (procedure? bitwise-if) #t)
(check "bitwise-not exists" (procedure? bitwise-not) #t)
(check "bitwise-or exists" (procedure? bitwise-or) #t)
(check "bitwise-reverse-bit-field exists" (procedure? bitwise-reverse-bit-field) #t)
(check "bitwise-rotate exists" (procedure? bitwise-rotate) #t)
(check "bitwise-xor exists" (procedure? bitwise-xor) #t)
(check "boolean=? all" (boolean=? #t #t #t) #t)
(check "boolean=? mixed" (boolean=? #t #f) #f)
(check "boolean? #t" (boolean? #t) #t)
(check "boolean? #f" (boolean? #f) #t)
(check "boolean? 0" (boolean? 0) #f)
(check "break exists" (procedure? break) #t)
(check "but-last" (but-last '(1 2 3)) '(1 2))
(check "cartesian-product exists" (procedure? cartesian-product) #t)
(check "char->name" (char->name #\space) "space")
(check "char-ascii? exists" (procedure? char-ascii?) #t)
(check "char-control? exists" (procedure? char-control?) #t)
(check "char-iso-control? exists" (procedure? char-iso-control?) #t)
(check "char-set exists" (procedure? char-set) #t)
(check "char-set->list exists" (procedure? char-set->list) #t)
(check "char-set-adjoin exists" (procedure? char-set-adjoin) #t)
(check "char-set-complement exists" (procedure? char-set-complement) #t)
(check "char-set-contains?" (char-set-contains? (char-set #\a #\b) #\a) #t)
(check "char-set-copy exists" (procedure? char-set-copy) #t)
(check "char-set-delete exists" (procedure? char-set-delete) #t)
(check "char-set-difference exists" (procedure? char-set-difference) #t)
(check "char-set-empty?" (char-set-empty? (char-set)) #t)
(check "char-set-intersection exists" (procedure? char-set-intersection) #t)
(check "char-set-union exists" (procedure? char-set-union) #t)
(check "char-set?" (char-set? (char-set #\a #\b)) #t)
(check "combinations exists" (procedure? combinations) #t)
(check "complement #f" ((complement even?) 2) #f)
(check "complement #t" ((complement even?) 3) #t)
(check "compose" ((compose (lambda (x) (* x 2)) (lambda (x) (+ x 1))) 5) 12)
(check "concatenate" (concatenate '((1 2) (3 4))) '(1 2 3 4))
(check "const" ((const 42) 1 2 3) 42)
(check "count" (count even? '(1 2 3 4 5)) 2)
(check "curry" ((curry list 1 2) 3 4) '(1 2 3 4))
(check "default-object? void" (default-object? (void)) #t)
(check "delete" (delete 2 '(1 2 3 2 4)) '(1 3 4))
(check "delete-assoc" (delete-assoc 'b '((a 1) (b 2) (c 3))) '((a 1) (c 3)))
(check "delete-duplicates" (delete-duplicates '(1 2 1 3 2 4)) '(1 2 3 4))
(check "deque->list exists" (procedure? deque->list) #t)
(check "deque-add-back exists" (procedure? deque-add-back) #t)
(check "deque-add-front exists" (procedure? deque-add-front) #t)
(check "deque-back exists" (procedure? deque-back) #t)
(check "deque-empty? exists" (procedure? deque-empty?) #t)
(check "deque-front exists" (procedure? deque-front) #t)
(check "deque-length exists" (procedure? deque-length) #t)
(check "deque-remove-back exists" (procedure? deque-remove-back) #t)
(check "deque-remove-front exists" (procedure? deque-remove-front) #t)
(check "drop" (drop '(1 2 3 4) 2) '(3 4))
(check "drop-right" (drop-right '(1 2 3 4) 2) '(1 2))
(check "drop-while" (drop-while (lambda (x) (< x 3)) '(1 2 3 4)) '(3 4))
(check "eighth exists" (procedure? eighth) #t)
(check "every true" (every even? '(2 4 6)) #t)
(check "every false" (every even? '(2 4 5)) #f)
(check "exact-nonnegative-integer? 0" (exact-nonnegative-integer? 0) #t)
(check "exact-nonnegative-integer? -1" (exact-nonnegative-integer? -1) #f)
(check "exact-rational? exists" (procedure? exact-rational?) #t)
(check "factor" (factor 12) '(2 2 3))
(check "factorial" (factorial 5) 120)
(check "fib-pair exists" (procedure? fib-pair) #t)
(check "fibonacci 10" (fibonacci 10) 55)
(check "fibonacci 0" (fibonacci 0) 0)
(check "fifth exists" (procedure? fifth) #t)
(check "filter" (filter even? '(1 2 3 4 5 6)) '(2 4 6))
(check "find found" (find even? '(1 2 3 4)) 2)
(check "find missing" (find (lambda (x) (= x 10)) '(1 2 3)) #f)
(check "first" (first '(1 2 3)) 1)
(check "first-set-bit exists" (procedure? first-set-bit) #t)
(check "fixnum-width exists" (procedure? fixnum-width) #t)
(check "fixnum? exists" (procedure? fixnum?) #t)
(check "fl* exists" (procedure? fl*) #t)
(check "fl+ exists" (procedure? fl+) #t)
(check "fl- exists" (procedure? fl-) #t)
(check "fl/ exists" (procedure? fl/) #t)
(check "fl<? exists" (procedure? fl<?) #t)
(check "fl>? exists" (procedure? fl>?) #t)
(check "flacos exists" (procedure? flacos) #t)
(check "flasin exists" (procedure? flasin) #t)
(check "flat-map" (flat-map (lambda (x) (list x x)) '(1 2 3)) '(1 1 2 2 3 3))
(check "flatan exists" (procedure? flatan) #t)
(check "flatten" (flatten '((1 2) 3 (4 (5)))) '(1 2 3 4 5))
(check "flceiling exists" (procedure? flceiling) #t)
(check "flcos exists" (procedure? flcos) #t)
(check "fleven? exists" (procedure? fleven?) #t)
(check "flexp exists" (procedure? flexp) #t)
(check "flexpt exists" (procedure? flexpt) #t)
(check "flfloor exists" (procedure? flfloor) #t)
(check "flip" ((flip -) 5 3) -2)
(check "fllog exists" (procedure? fllog) #t)
(check "flmax exists" (procedure? flmax) #t)
(check "flmin exists" (procedure? flmin) #t)
(check "flnegative? exists" (procedure? flnegative?) #t)
(check "flodd? exists" (procedure? flodd?) #t)
(check "flonum? exists" (procedure? flonum?) #t)
(check "flpositive? exists" (procedure? flpositive?) #t)
(check "flround exists" (procedure? flround) #t)
(check "flsin exists" (procedure? flsin) #t)
(check "flsqrt exists" (procedure? flsqrt) #t)
(check "fltan exists" (procedure? fltan) #t)
(check "fltruncate exists" (procedure? fltruncate) #t)
(check "flzero? exists" (procedure? flzero?) #t)
(check "fold" (fold + 0 '(1 2 3 4)) 10)
(check "fold-left" (fold-left + 0 '(1 2 3 4)) 10)
(check "fold-right" (fold-right - 0 '(1 2 3)) 2)
(check "fourth exists" (procedure? fourth) #t)
(check "gcd exists" (procedure? gcd) #t)
(check "generator exists" (procedure? generator) #t)
(check "generator->list exists" (procedure? generator->list) #t)
(check "generator->string exists" (procedure? generator->string) #t)
(check "generator->vector exists" (procedure? generator->vector) #t)
(check "generator-count exists" (procedure? generator-count) #t)
(check "generator-drop exists" (procedure? generator-drop) #t)
(check "generator-filter exists" (procedure? generator-filter) #t)
(check "generator-find exists" (procedure? generator-find) #t)
(check "generator-for-each exists" (procedure? generator-for-each) #t)
(check "generator-map exists" (procedure? generator-map) #t)
(check "generator-take exists" (procedure? generator-take) #t)
(check "gensym exists" (procedure? gensym) #t)
(check "greatest-fixnum exists" (procedure? greatest-fixnum) #t)
(check "hash-table-clear! exists" (procedure? hash-table-clear!) #t)
(check "hash-table-fold exists" (procedure? hash-table-fold) #t)
(check "helper exists" (procedure? helper) #t)
(check "integer->bits exists" (procedure? integer->bits) #t)
(check "integer->list exists" (procedure? integer->list) #t)
(check "integer->string/radix exists" (procedure? integer->string/radix) #t)
(check "iota" (iota 5) '(0 1 2 3 4))
(check "iota start" (iota 5 10) '(10 11 12 13 14))
(check "iterate" (iterate (lambda (x) (* x 2)) 3 1) 8)
(check "just exists" (procedure? just) #t)
(check "just? exists" (procedure? just?) #t)
(check "last" (last '(1 2 3)) 3)
(check "lcm exists" (procedure? lcm) #t)
(check "least-fixnum exists" (procedure? least-fixnum) #t)
(check "linear-update-list exists" (procedure? linear-update-list) #t)
(check "list* exists" (procedure? list*) #t)
(check "list->bitvector exists" (procedure? list->bitvector) #t)
(check "list->generator exists" (procedure? list->generator) #t)
(check "list->integer exists" (procedure? list->integer) #t)
(check "list->mapping exists" (procedure? list->mapping) #t)
(check "list-copy" (list-copy '(1 2 3)) '(1 2 3))
(check "list-head" (list-head '(1 2 3) 2) '(1 2))
(check "list-index found" (list-index (lambda (x) (= x 3)) '(1 2 3 4)) 2)
(check "list-index missing" (list-index (lambda (x) (= x 10)) '(1 2 3)) #f)
(check "list-queue exists" (procedure? list-queue) #t)
(check "list-queue->list exists" (procedure? list-queue->list) #t)
(check "list-queue-add-back! exists" (procedure? list-queue-add-back!) #t)
(check "list-queue-add-front! exists" (procedure? list-queue-add-front!) #t)
(check "list-queue-back exists" (procedure? list-queue-back) #t)
(check "list-queue-copy exists" (procedure? list-queue-copy) #t)
(check "list-queue-empty? exists" (procedure? list-queue-empty?) #t)
(check "list-queue-front exists" (procedure? list-queue-front) #t)
(check "list-queue-remove-front! exists" (procedure? list-queue-remove-front!) #t)
(check "list-queue-size exists" (procedure? list-queue-size) #t)
(check "list-set! exists" (procedure? list-set!) #t)
(check "list-sort" (list-sort < '(3 1 4 1 5)) '(1 1 3 4 5))
(check "list-stable-sort exists" (procedure? list-stable-sort) #t)
(check "list-tabulate" (list-tabulate 5 (lambda (i) (* i i))) '(0 1 4 9 16))
(check "list-transduce exists" (procedure? list-transduce) #t)
(check "loop-n exists" (procedure? loop-n) #t)
(check "make-array exists" (procedure? make-array) #t)
(check "make-bimap exists" (procedure? make-bimap) #t)
(check "make-binary-heap exists" (procedure? make-binary-heap) #t)
(check "make-bitvector exists" (procedure? make-bitvector) #t)
(check "make-deque exists" (procedure? make-deque) #t)
(check "make-generator exists" (procedure? make-generator) #t)
(check "make-hook exists" (procedure? make-hook) #t)
(check "make-weak-box exists" (procedure? make-weak-box) #t)
(check "mapping exists" (procedure? mapping) #t)
(check "mapping->list exists" (procedure? mapping->list) #t)
(check "mapping-contains? exists" (procedure? mapping-contains?) #t)
(check "mapping-delete exists" (procedure? mapping-delete) #t)
(check "mapping-for-each exists" (procedure? mapping-for-each) #t)
(check "mapping-keys exists" (procedure? mapping-keys) #t)
(check "mapping-map exists" (procedure? mapping-map) #t)
(check "mapping-ref exists" (procedure? mapping-ref) #t)
(check "mapping-set exists" (procedure? mapping-set) #t)
(check "mapping-size exists" (procedure? mapping-size) #t)
(check "mapping-values exists" (procedure? mapping-values) #t)
(check "mapping? exists" (procedure? mapping?) #t)
(check "maybe-ref exists" (procedure? maybe-ref) #t)
(check "maybe? exists" (procedure? maybe?) #t)
(check "member" (member 2 '(1 2 3)) '(2 3))
(check "memq found" (memq 'b '(a b c)) '(b c))
(check "memq not" (memq 'd '(a b c)) #f)
(check "memv found" (memv 2 '(1 2 3)) '(2 3))
(check "merge" (merge < '(1 3 5) '(2 4 6)) '(1 2 3 4 5 6))
(check "merge! exists" (procedure? merge!) #t)
(check "nat-stream exists" (procedure? nat-stream) #t)
(check "naturals exists" (stream-null? naturals) #f)
(check "ne-list? 1" (ne-list? '(1)) #t)
(check "ne-list? 2" (ne-list? '(1 2)) #f)
(check "ninth exists" (procedure? ninth) #t)
(check "not #f" (not #f) #t)
(check "not #t" (not #t) #f)
(check "not 0" (not 0) #f)
(check "not-pair? atom" (not-pair? 42) #t)
(check "not-pair? pair" (not-pair? '(1)) #f)
(check "nothing? exists" (procedure? nothing?) #t)
(check "null-list? nil" (null-list? '()) #t)
(check "null-list? pair" (null-list? '(1)) #f)
(check "number=? all" (number=? 1 1 1) #t)
(check "number=? mixed" (number=? 1 2) #f)
(check "object->string" (string? (object->string '(1 2 3))) #t)
(check "pair-fold exists" (procedure? pair-fold) #t)
(check "pair-fold-right exists" (procedure? pair-fold-right) #t)
(check "partition exists" (procedure? partition) #t)
(check "permutations exists" (procedure? permutations) #t)
(check "prime? 7" (prime? 7) #t)
(check "prime? 8" (prime? 8) #f)
(check "primes exists" (stream-null? primes) #f)
(check "procedure-rename exists" (procedure? procedure-rename) #t)
(check "product" (product 2 3 4) 24)
(check "proper-list? ok" (proper-list? '(1 2 3)) #t)
(check "proper-list? nil" (proper-list? '()) #t)
(check "quick-expt" (quick-expt 2 10) 1024)
(check "random-integer exists" (procedure? random-integer) #t)
(check "random-real exists" (procedure? random-real) #t)
(check "random-source->random-integer exists" (procedure? random-source->random-integer) #t)
(check "random-source->random-real exists" (procedure? random-source->random-real) #t)
(check "random-source-pseudo-randomize! exists" (procedure? random-source-pseudo-randomize!) #t)
(check "random-source-randomize! exists" (procedure? random-source-randomize!) #t)
(check "real->exact exists" (procedure? real->exact) #t)
(check "reduce" (reduce + 0 '(1 2 3 4)) 10)
(check "remove" (remove even? '(1 2 3 4 5 6)) '(1 3 5))
(check "remove-hook! exists" (procedure? remove-hook!) #t)
(check "reset-hook! exists" (procedure? reset-hook!) #t)
(check "run-hook exists" (procedure? run-hook) #t)
(check "scheme-gcd exists" (procedure? scheme-gcd) #t)
(check "scheme-implementation-name exists" (procedure? scheme-implementation-name) #t)
(check "scheme-implementation-version exists" (procedure? scheme-implementation-version) #t)
(check "scheme-lcm exists" (procedure? scheme-lcm) #t)
(check "second" (second '(1 2 3)) 2)
(check "seventh exists" (procedure? seventh) #t)
(check "sieve exists" (procedure? sieve) #t)
(check "sink exists" (procedure? sink) #t)
(check "sixth exists" (procedure? sixth) #t)
(check "sorted? true" (sorted? < '(1 2 3 4)) #t)
(check "sorted? false" (sorted? < '(1 3 2 4)) #f)
(check "span exists" (procedure? span) #t)
(check "split-at exists" (procedure? split-at) #t)
(check "stream-car exists" (procedure? stream-car) #t)
(check "stream-cdr exists" (procedure? stream-cdr) #t)
(check "stream-filter exists" (procedure? stream-filter) #t)
(check "stream-map exists" (procedure? stream-map) #t)
(check "stream-null? exists" (procedure? stream-null?) #t)
(check "stream-ref exists" (procedure? stream-ref) #t)
(check "stream-take exists" (procedure? stream-take) #t)
(check "string exists" (procedure? string) #t)
(check "string->generator exists" (procedure? string->generator) #t)
(check "string->vector" (string->vector "ab") #(#\a #\b))
(check "string-any" (string-any (lambda (c) (char=? c #\l)) "hello") #t)
(check "string-contains" (string-contains "hello world" "world") 6)
(check "string-count" (string-count "hello" (lambda (c) (char=? c #\l))) 2)
(check "string-downcase" (string-downcase "HELLO") "hello")
(check "string-every" (string-every (lambda (c) (char-alphabetic? c)) "hello") #t)
(check "string-foldcase" (string-foldcase "HELLO") "hello")
(check "string-for-each exists" (procedure? string-for-each) #t)
(check "string-index found" (string-index "hello" (lambda (c) (char=? c #\e))) 1)
(check "string-index missing" (string-index "hello" (lambda (c) (char=? c #\z))) #f)
(check "string-join" (string-join '("a" "b" "c") "-") "a-b-c")
(check "string-map exists" (procedure? string-map) #t)
;(check "string-pad" (string-pad "42" 5 "0") "00042")
;(check "string-pad-right" (string-pad-right "42" 5 "0") "42000")
(check "string-prefix? true" (string-prefix? "hel" "hello") #t)
(check "string-prefix? false" (string-prefix? "xyz" "hello") #f)
(check "string-reverse" (string-reverse "hello") "olleh")
(check "string-split" (string-split "a b c") '("a" "b" "c"))
(check "string-suffix? true" (string-suffix? "rld" "world") #t)
(check "string-tabulate exists" (procedure? string-tabulate) #t)
(check "string-titlecase" (string-titlecase "hello world") "Hello World")
(check "string-transduce exists" (procedure? string-transduce) #t)
(check "string-trim" (string-trim "  hello  ") "hello")
(check "string-trim-both exists" (procedure? string-trim-both) #t)
(check "string-trim-left exists" (procedure? string-trim-left) #t)
(check "string-trim-right exists" (procedure? string-trim-right) #t)
(check "string-upcase" (string-upcase "hello") "HELLO")
(check "sub1" (sub1 5) 4)
(check "sub1* exists" (procedure? sub1*) #t)
(check "take" (take '(1 2 3 4) 2) '(1 2))
(check "take-right" (take-right '(1 2 3 4) 2) '(3 4))
(check "take-while" (take-while (lambda (x) (< x 3)) '(1 2 3 4)) '(1 2))
(check "tdrop exists" (procedure? tdrop) #t)
(check "tenth exists" (procedure? tenth) #t)
(check "test-begin exists" (procedure? test-begin) #t)
(check "test-end exists" (procedure? test-end) #t)
(check "tfilter exists" (procedure? tfilter) #t)
(check "third exists" (procedure? third) #t)
(check "tmap exists" (procedure? tmap) #t)
(check "tree->list exists" (procedure? tree->list) #t)
(check "ttake exists" (procedure? ttake) #t)
(check "unfold" (unfold (lambda (x) (> x 5)) (lambda (x) x) (lambda (x) (+ x 1)) 1) '(1 2 3 4 5))
(check "unzip1 exists" (procedure? unzip1) #t)
(check "unzip2 exists" (procedure? unzip2) #t)
(check "unzip3 exists" (procedure? unzip3) #t)
(check "unzip4 exists" (procedure? unzip4) #t)
(check "unzip5 exists" (procedure? unzip5) #t)
(check "vector->generator exists" (procedure? vector->generator) #t)
(check "vector->string" (vector->string #(#\a #\b)) "ab")
(check "vector-any" (vector-any even? #(1 2 3)) #t)
(check "vector-concatenate" (vector-concatenate '(#(1 2) #(3 4))) #(1 2 3 4))
(check "vector-count" (vector-count even? #(1 2 3 4 5)) 2)
(check "vector-empty? true" (vector-empty? #()) #t)
(check "vector-empty? false" (vector-empty? #(1)) #f)
(check "vector-every" (vector-every even? #(2 4 6)) #t)
(check "vector-fold" (vector-fold + 0 #(1 2 3 4)) 16)
(check "vector-fold-right" (vector-fold-right - 0 #(1 2 3)) -1)
(check "vector-for-each exists" (procedure? vector-for-each) #t)
(check "vector-index" (vector-index even? #(1 3 4 5)) 2)
(check "vector-reverse" (vector-reverse #(1 2 3)) #(3 2 1))
(check "vector-reverse!" (let ((v #(1 2 3))) (vector-reverse! v) v) #(3 2 1))
(check "vector-skip exists" (procedure? vector-skip) #t)
(check "vector-sort" (vector-sort < #(3 1 4 1 5)) #(1 1 3 4 5))
(check "vector-swap!" (let ((v #(1 2 3))) (vector-swap! v 0 2) v) #(3 2 1))
(check "vector-transduce exists" (procedure? vector-transduce) #t)
(check "weak-box-ref exists" (procedure? weak-box-ref) #t)
(check "weak-box-set! exists" (procedure? weak-box-set!) #t)
(check "weak-box? exists" (procedure? weak-box?) #t)
(check "with-exception-handler/k exists" (procedure? with-exception-handler/k) #t)
(check "with-output-to-string exists" (procedure? with-output-to-string) #t)
(check "xcons" (xcons '(2 3) 1) '(1 2 3))
(check "zip" (zip '(1 2 3) '(a b c)) '((1 a) (2 b) (3 c)))
(check "vector-map" (vector-map (lambda (x) (* x 2)) #(1 2 3)) #(2 4 6))
(check "vector-unfold" (vector-unfold (lambda (i x) (values x (+ x 1))) 5 0) #(0 1 2 3 4))
(check "vector-unfold" (vector-unfold (lambda (i x) (+ x 1)) 5 0) #(1 2 3 4 5))
