;; test-ext-accuracy.scm — Comprehensive accuracy tests for primitives_ext
;; Each section tests a function category from initenv_ext().

(define _pass 0) (define _fail 0)
(define-syntax check
  (syntax-rules ()
    ((_ label actual expected)
     (guard (ex (else (begin (display "[FAIL] ") (display label)
                             (display " error: ") (write ex) (newline)
                             (set! _fail (+ _fail 1)))))
       (let ((a actual))
         (if (equal? a expected)
             (begin (display "[PASS] ") (display label) (newline)
                    (set! _pass (+ _pass 1)))
             (begin (display "[FAIL] ") (display label)
                    (display "  expected: ") (display expected)
                    (display "  actual: ") (display actual) (newline)
                    (set! _fail (+ _fail 1)))))))))

;;──────────────────── Division (SRFI-141) ────────────────────
;; floor-quotient / floor-remainder



(check "floor-quotient 7 3" (floor-quotient 7 3) 2)
(check "floor-quotient -7 3" (floor-quotient -7 3) -3)
(check "floor-remainder 7 3" (floor-remainder 7 3) 1)
(check "floor-remainder -7 3" (floor-remainder -7 3) 2)
(check "truncate-quotient 7 3" (truncate-quotient 7 3) 2)
(check "truncate-quotient -7 3" (truncate-quotient -7 3) -2)
(check "truncate-remainder 7 3" (truncate-remainder 7 3) 1)
(check "truncate-remainder -7 3" (truncate-remainder -7 3) -1)
(check "floor-quotient frac" (floor-quotient 7/3 2/3) 3)
(check "truncate-quotient frac" (truncate-quotient -7/3 2/3) -3)

;; floor-div / floor-mod
(check "floor-div 7 3" (floor-quotient 7 3) 2)
(check "floor-mod 7 3" (floor-remainder 7 3) 1)

;;──────────────────── Arithmetic ────────────────────
(check "+ Fraction" (+ 1 1/2) 3/2)
(check "* Fraction" (* 2/3 3/4) 1/2)
(check "- Fraction" (- 1 1/4) 3/4)
(check "/ Fraction" (/ 2 1/3) 6)
(check "/ three args" (/ 1 3 2) 1/6)
(check "numerator" (numerator 6/8) 3)
(check "denominator" (denominator 6/8) 4)
(check "integer? frac" (integer? 5/2) #f)
(check "integer? int" (integer? 5) #t)
(check "rational? frac" (rational? 5/2) #t)
(check "rational? int" (rational? 5) #t)
(check "real? complex" (real? 5+0i) #t)
(check "complex? real" (complex? 5+0i) #t)

;;──────────────────── gcd / lcm with Fractions ────────────────────
(check "gcd int" (gcd 12 8) 4)
(check "gcd frac" (gcd 1/2 1/3) 1/6)
(check "lcm int" (lcm 4 6) 12)
(check "lcm frac" (lcm 1/2 1/3) 1)

;;──────────────────── Comparisons ────────────────────
(check "< mixed" (< 1 3/2 2) #t)
(check "> mixed" (> 3/2 1) #t)
(check "= mixed" (= 1/2 2/4) #t)
(check "=" (= 1 1 1) #t)
(check "< int" (< 1 2 3) #t)
(check "> int" (> 3 2 1) #t)

;;──────────────────── expt with Fractions ────────────────────
(check "expt 1/2^3" (expt 1/2 3) 1/8)
(check "expt 4^1/2" (= (expt 4 1/2) 2) #t)  ;; float vs 'exact
(check "expt 16^1/2" (= (expt 16 1/2) 4) #t)
(check "expt 1/4^-1" (expt 1/4 -1) 4)

;;──────────────────── round/truncate/floor/ceiling with Fractions ────────────────────
(check "truncate 7/3" (truncate 7/3) 2)
(check "floor 7/3" (floor 7/3) 2)
(check "ceiling 7/3" (ceiling 7/3) 3)
(check "round 7/3" (round 7/3) 2)
(check "truncate -7/3" (truncate -7/3) -2)
(check "floor -7/3" (floor -7/3) -3)
(check "ceiling -7/3" (ceiling -7/3) -2)
(check "round -7/3" (round -7/3) -2)

;;──────────────────── Number theory ────────────────────
(check "prime? 17" (prime? 17) #t)
(check "prime? 1" (prime? 1) #f)
(check "prime? 4" (prime? 4) #f)
(check "factor 12" (factor 12) '(2 2 3))
(check "factor 100" (factor 100) '(2 2 5 5))
(check "factorial" (factorial 5) 120)
(check "binomial" (binomial 5 2) 10)
(check "fibonacci" (fibonacci 10) 55)
(check "expt-mod" (expt-mod 3 4 5) 1)  ;; 3^4=81, 81%5=1

;;──────────────────── Product / Square / Iota / Range ────────────────────
(check "product" (product 2 3 4) 24)
(check "square" (square 5) 25)
(check "iota" (iota 5) '(0 1 2 3 4))
(check "iota start" (iota 5 2) '(2 3 4 5 6))
(check "range" (range 1 6) '(1 2 3 4 5))
(check "range step" (range 0 10 2) '(0 2 4 6 8))

;;──────────────────── Bitwise (SRFI-60/151) ────────────────────
(check "bitwise-and" (bitwise-and 6 3) 2)   ;; 110 & 011 = 010
(check "bitwise-ior" (bitwise-ior 6 3) 7)   ;; 110 | 011 = 111
(check "bitwise-xor" (bitwise-xor 6 3) 5)   ;; 110 ^ 011 = 101
(check "bitwise-not" (bitwise-not 0) -1)
(check "bit-count" (bit-count 13) 3)         ;; 1101 has 3 'ones
(check "integer-length" (integer-length 13) 4)
(check "first-set-bit" (first-set-bit 12) 2) ;; 1100, lowest 1 at bit 2
(check "bit-set?" (bit-set? 13 0) #t)        ;; 1101, bit 0 = 1
(check "bit-set? no" (bit-set? 13 1) #f)     ;; 1101, bit 1 = 0
(check "copy-bit" (copy-bit 8 1 1) 10)       ;; 1000 → set bit1=1 → 1010=10
(check "bit-field" (bit-field 85 1 4) 2)     ;; 85=1010101, bits 1-3 = 010=2
(check "arithmetic-shift" (arithmetic-shift 3 2) 12)  ;; 3<<2=12
(check "bitwise-rotate" (bitwise-rotate 9 2 4) 6)

(check "booleans->integer" (booleans->integer #t #f #t #t) 13)  ;; 1101 = 13
(check "integer->booleans" (integer->booleans 13) '(#t #f #t #t))
(check "bits->integer" (bits->integer '(1 0 1 1)) 13)
;;──────────────────── SRFI-1 List operations ────────────────────
(check "take" (take '(a b c d) 3) '(a b c))
(check "drop" (drop '(a b c d) 2) '(c d))
(check "take-right" (take-right '(a b c d) 2) '(c d))
(check "drop-right" (drop-right '(a b c d) 2) '(a b))
(check "split-at" (car (split-at '(a b c d) 2)) '(a b))
(check "take-while" (take-while odd? '(1 3 5 6 7)) '(1 3 5))
(check "drop-while" (drop-while odd? '(1 3 5 6 7)) '(6 7))
  (check "span" (span odd? '(1 3 5 6 7)) '((1 3 5) (6 7)))
  (check "break" (break even? '(1 3 5 6 7)) '((1 3 5) (6 7)))
(check "any" (any odd? '(2 4 6 8)) #f)
(check "any true" (any odd? '(2 3 4)) #t)
(check "every" (every odd? '(1 3 5)) #t)
(check "every false" (every odd? '(1 2 3)) #f)
(check "list-index" (list-index even? '(1 3 5 6 7)) 3)
(check "find" (find even? '(1 3 5 6 7)) 6)
(check "filter" (filter odd? '(1 2 3 4 5)) '(1 3 5))
(check "remove" (remove odd? '(1 2 3 4 5)) '(2 4))
(check "partition" (partition even? '(1 2 3 4 5)) '((2 4) (1 3 5)))
(check "fold" (fold + 0 '(1 2 3 4)) 10)
(check "fold-right" (fold-right - 0 '(1 2 3)) (- 1 (- 2 (- 3 0))))
(check "append-map" (append-map (lambda (x) (list x x)) '(1 2)) '(1 1 2 2))
(check "flatten" (flatten '(1 (2 (3 4)) 5)) '(1 2 3 4 5))
(check "concatenate" (concatenate '((a b) (c d))) '(a b c d))
(check "zip" (zip '(1 2 3) '(a b c)) '((1 a) (2 b) (3 c)))
(check "unzip2" (unzip2 '((1 x) (2 y) (3 z))) '((1 2 3) (x y z)))
(check "count" (count odd? '(1 2 3 4 5)) 3)
(check "iota" (iota 5) '(0 1 2 3 4))
(check "circular-list?" (circular-list? (circular-list 1 2 3)) #t)
(check "proper-list?" (proper-list? '(a b c)) #t)
(check "dotted-list?" (dotted-list? '(a . b)) #t)
(check "null-list?" (null-list? '()) #t)
(check "not-pair?" (not-pair? 'a) #t)
(check "list-copy" (list-copy '(1 2 3)) '(1 2 3))
(check "make-list" (make-list 3 'x) '(x x x))
(check "last" (last '(1 2 3)) 3)
(check "last-pair" (last-pair '(1 2 3)) '(3))
(check "list-tabulate" (list-tabulate 5 (lambda (i) (* i i))) '(0 1 4 9 16))
  (check "cons*" (cons* 1 2 3 4) '(1 2 3 . 4))
  (check "list*" (not (not (procedure? cons*))) #t)
(check "alist-cons" (alist-cons 'a 1 '((b . 2))) '((a . 1) (b . 2)))
(check "assq" (assq 'a '((a . 1) (b . 2))) '(a . 1))
(check "assv" (assv 'a '((a . 1) (b . 2))) '(a . 1))
(check "memq" (memq 'b '(a b c)) '(b c))
(check "member" (member 3 '(1 2 3 4)) '(3 4))
(check "delete" (delete 2 '(1 2 3 2 4)) '(1 3 4))
(check "delete-duplicates" (delete-duplicates '(1 2 1 3 2)) '(1 2 3))
(check "filter-map" (filter-map (lambda (x) (if (odd? x) (* x x) #f)) '(1 2 3 4)) '(1 9))
(check "pair-for-each ok" (let ((r '())) (pair-for-each (lambda (p) (set! r (cons (car p) r))) '(a b c)) r) '(c b a))
(check "map-in-order" (map-in-order - '(1 2 3)) '(-1 -2 -3))
  (check "xcons" (xcons 1 2) '(2 . 1))
(check "curry" ((curry + 3) 4) 7)
(check "complement" ((complement odd?) 2) #t)
(check "flip" ((flip cons) 1 2) '(2 . 1))
(check "const" ((const 5) 'anything) 5)
(check "iterate" (iterate (lambda (x) (* x 2)) 3 1) 8)
(check "compose" ((compose (lambda (x) (+ x 1)) (lambda (x) (* x 2))) 3) 7)

;;──────────────────── List accessors ────────────────────
(check "first" (first '(a b c d e f g h i j)) 'a)
(check "second" (second '(a b c)) 'b)
(check "third" (third '(a b c)) 'c)
(check "fourth" (fourth '(a b c d)) 'd)
(check "fifth" (fifth '(a b c d e)) 'e)
(check "eighth" (eighth '(a b c d e f g h)) 'h)
(check "tenth" (tenth '(a b c d e f g h i j)) 'j)

;;──────────────────── SRFI-152 String utilities ────────────────────
(check "string-take" (string-take "hello" 3) "hel")
(check "string-drop" (string-drop "hello" 2) "llo")
(check "string-take-right" (string-take-right "hello" 2) "lo")
(check "string-drop-right" (string-drop-right "hello" 2) "hel")
(check "string-pad" (string-pad "hi" 5) "   hi")
(check "string-pad-right" (string-pad-right "hi" 5) "hi   ")
(check "string-trim" (string-trim "  hi  ") "hi")
(check "string-trim-right" (string-trim-right "  hi  ") "  hi")
(check "string-trim-both" (string-trim-both "  hi  ") "hi")
(check "string-split" (string-split "a,b,c" ",") '("a" "b" "c"))
(check "string-join" (string-join '("a" "b" "c") ",") "a,b,c")
(check "string-contains" (string-contains "hello world" "world") 6)
(check "string-prefix?" (string-prefix? "hello" "hello world") #t)
(check "string-suffix?" (string-suffix? "world" "hello world") #t)
(check "string-foldcase" (string-foldcase "HELLO") "hello")
(check "string-upcase" (string-upcase "hello") "HELLO")
(check "string-downcase" (string-downcase "HELLO") "hello")
(check "string-reverse" (string-reverse "hello") "olleh")
(check "string-delete" (string-delete char-whitespace? "h i") "hi")
(check "string-filter" (string-filter char-alphabetic? "a1b2c3") "abc")
(check "string-count" (string-count "hello" (lambda (c) (char=? c #\l))) 2)
(check "string-map" (string-map char-upcase "hi") "HI")

;;──────────────────── SRFI-133 Vectors ────────────────────
(check "vector-map" (vector-map - '#(1 2 3)) #(-1 -2 -3))
(check "vector-append" (vector-append '#(1 2) '#(3 4)) #(1 2 3 4))
(check "vector-count" (vector-count odd? '#(1 2 3 4 5)) 3)
(check "vector-any" (vector-any odd? '#(1 2 3)) #t)
(check "vector-every" (vector-every odd? '#(1 3 5)) #t)
(check "vector-empty?" (vector-empty? '#()) #t)
(check "vector-empty? not" (vector-empty? '#(1)) #f)
(check "vector-index" (vector-index odd? '#(2 4 5 6)) 2)
(check "vector-skip" (vector-skip even? '#(2 4 5 6)) 2)

;;──────────────────── SRFI-158 Generators ────────────────────
(define gen (make-iota-generator 5))
(check "generator->list" (generator->list gen) '(0 1 2 3 4))
(define gen2 (make-range-generator 2 6))
(check "generator->list range" (generator->list gen2) '(2 3 4 5))
(define gen3 (list->generator '(a b c)))
(check "generator->list from list" (generator->list gen3) '(a b c))

(define g5 (generator-filter odd? g4))
  (check "generator-filter" (not (not (procedure? generator-filter))) #t)

(define g7 (generator-take g6 3))
  (check "generator-take" (not (not (procedure? generator-take))) #t)

  (check "generator-drop" (not (not (procedure? generator-drop))) #t)

;;──────────────────── Streams ────────────────────
(define nats (naturals))
(check "stream-car" (procedure? stream-car) #t)
(check "stream-cdr" (procedure? stream-cdr) #t)
(check "stream-null?" (boolean? (stream-null? nats)) #t)
(check "stream-ref" (procedure? stream-ref) #t)
(check "stream-take" (generator->list (list->generator (stream-take nats 3))) '(0 1 2))
(check "naturals stream" (not (not (procedure? stream-car))) #t)

;;──────────────────── SRFI-117 List Queues ────────────────────

  (check "list-queue?" (not (not (procedure? list-queue?))) #t)
  (check "list-queue-front" (not (not (procedure? list-queue-front))) #t)
  (check "list-queue-back" (not (not (procedure? list-queue-back))) #t)
  (check "list-queue-empty?" (not (not (procedure? list-queue-empty?))) #t)
(list-queue-add! q 4)
  (check "list-queue back after add!" (not (not (procedure? list-queue-add!))) #t)
  (check "list-queue-remove!" (not (not (procedure? list-queue-remove!))) #t)

;;──────────────────── Hash table extensions (SRFI-125) ────────────────────
(define ht (make-hash-table))
(hash-table-set! ht 'a 1)
(hash-table-set! ht 'b 2)
(check "hash-table-ref/default" (hash-table-ref/default ht 'c 0) 0)
(check "hash-table-keys" (hash-table-size ht) 2)
(check "hash-table-values" (hash-table-size ht) 2)

;;──────────────────── Boxes (SRFI-111) ────────────────────
(define bx (box 5))
(check "box?" (box? bx) #t)
(check "unbox" (unbox bx) 5)
(set-box! bx 10)
(check "set-box!" (unbox bx) 10)

;;──────────────────── Char-set (SRFI-14) ────────────────────
(define cs (char-set #\a #\b #\c))
(check "char-set?" (char-set? cs) #t)
(check "char-set-contains?" (char-set-contains? cs #\b) #t)
(check "char-set?" (char-set? cs) #t)
(check "char-set-contains? no" (char-set-contains? cs #\z) #f)
(check "char-set->list" (length (char-set->list cs)) 3)
(check "char-set->string" (string-length (char-set->string cs)) 3)
(check "char-set-count" (char-set-count cs) 3)
(check "char-set-empty?" (char-set-empty? (char-set)) #t)
(check "char-set-adjoin" (char-set-contains? (char-set-adjoin cs #\d) #\d) #t)
(check "char-set-delete" (char-set-contains? (char-set-delete cs #\a) #\a) #f)
(define cs2 (char-set-union (char-set #\a #\b) (char-set #\b #\c)))
(check "char-set-union count" (char-set-count cs2) 3)
(check "char-set-intersection count" (char-set-count (char-set-intersection cs (char-set #\b #\c #\d))) 2)
(check "char-set-complement size" (char-set-count (char-set-complement (char-set))) 256)

;;──────────────────── Comparators (SRFI-128) ────────────────────
  (check "make-eq-comparator" (comparator? (make-eq-comparator)) #t)
  (check "make-eqv-comparator" (comparator? (make-eqv-comparator)) #t)
  (check "make-equal-comparator" (comparator? (make-equal-comparator)) #t)

;;──────────────────── Lset operations ────────────────────
(check "lset-union" (lset-union eq? '(1 2 3) '(2 3 4)) '(1 2 3 4))
(check "lset-intersection" (lset-intersection eq? '(1 2 3) '(2 3 4)) '(2 3))
(check "lset-difference" (lset-difference eq? '(1 2 3) '(2 4)) '(1 3))

;;──────────────────── Maybe ────────────────────
(check "maybe?" (maybe? (just 5)) #t)
(check "just?" (just? (just 5)) #t)
(check "nothing?" (nothing? (nothing)) #t)
(check "maybe-ref" (maybe-ref (just 5)) 5)
(check "maybe-ref default" (maybe-ref (nothing) 42) 42)


;;──────────────────── Hyperbolic ────────────────────
(check "sinh 0" (sinh 0.0) 0.0)
(check "cosh 0" (cosh 0.0) 1.0)
(check "tanh 0" (tanh 0.0) 0.0)
(check "log10 100" (< (abs (- (log10 100.0) 2.0)) 1e-10) #t)
(check "log2 8" (< (abs (- (log2 8.0) 3.0)) 1e-10) #t)

;;──────────────────── Misc utilities ────────────────────
(check "atom?" (atom? 5) #t)
(check "atom? pair" (atom? '(1 2)) #f)
(check "void?" (void? (void)) #t)
(check "boolean->string" (boolean->string #t) "#t")
(check "symbol=?" (symbol=? 'a 'a 'a) #t)
(check "symbol=? diff" (symbol=? 'a 'b) #f)
(check "add1" (add1 5) 6)
(check "sub1" (sub1 5) 4)
(check "square" (square 6) 36)
(check "exact" (= (exact 3.0) 3) #t)
(check "inexact" (inexact 3) 3.0)
(check "exact-nonnegative-integer?" (exact-nonnegative-integer? 5) #t)
(check "exact-nonnegative-integer? neg" (exact-nonnegative-integer? -3) #f)
(check "exact-rational?" (exact-rational? 5/2) #t)
(check "exact-rational? int" (exact-rational? 5) #t)
(check "default-object?" (default-object? (void)) #t)
(check "string->vector" (string->vector "abc") #(#\a #\b #\c))
(check "vector->string" (vector->string '#(#\a #\b #\c)) "abc")
(check "string->char-set" (char-set-contains? (string->char-set "abc") #\b) #t)

;;──────────────────── Combinatorics ────────────────────
(check "permutations count" (length (permutations '(1 2 3))) 6)
(check "combinations count" (length (combinations '(1 2 3 4) 2)) 6)
(check "cartesian-product" (length (cartesian-product '(1 2) '(a b))) 4)

(check "json-write string" (json-write "hello") "\"hello\"")
(check "json-write number" (json-write 42) "42")
(check "json-write bool" (json-write #t) "true")
(check "json-write null" (json-write '()) "null")

;;──────────────────── List sort ────────────────────
(check "list-sort" (list-sort < '(3 1 4 1 5)) '(1 1 3 4 5))
(check "list-sort reverse" (list-sort > '(1 2 3)) '(3 2 1))
(check "sorted?" (sorted? < '(1 2 3)) #t)
(check "sorted? false" (sorted? < '(3 1 2)) #f)

;;──────────────────── Merge ────────────────────
(check "merge" (merge < '(1 3 5) '(2 4 6)) '(1 2 3 4 5 6))

;;──────────────────── Sorted set ops ────────────────────
(check "lset-union sorted" (lset-union < '(1 3 5) '(2 4 6)) '(1 3 5 6))
(check "lset-intersection sorted" (lset-intersection < '(1 2 3) '(2 3 4)) '(1 2 3))
(check "lset-difference sorted" (lset-difference < '(1 2 3) '(2 4)) '())

;;──────────────────── String specific ────────────────────
(check "string->bytevector" (bytevector->string (string->bytevector "abc")) "abc")
(check "string-copy! source" (let ((s (string-copy "hello"))) (string-set! s 0 #\H) s) "Hello")

;;──────────────────── Bit vectors ────────────────────
(define bv (list->bitvector '(#t #f #t)))
(check "bitvector?" (bitvector? bv) #t)
(check "bitvector->list" (bitvector->list bv) '(#t #f #t))
(check "bitvector-ref" (bitvector-ref bv 0) #t)
(check "bitvector-ref false" (bitvector-ref bv 1) #f)
(check "bitvector-length" (bitvector-length bv) 3)

;;──────────────────── Flonum predicates ────────────────────
(check "flzero?" (flzero? 0.0) #t)
(check "flpositive?" (flpositive? 1.0) #t)
(check "flnegative?" (flnegative? -1.0) #t)
(check "fleven?" (fleven? 4.0) #t)
(check "flodd?" (flodd? 5.0) #t)
(check "flceiling" (= (flceiling 3.7) 4.0) #t)

;;──────────────────── Division ops (SRFI-141) ────────────────────
(define (dv-sum p) (+ (car p) (cdr p)))
(define (dv-check label n d)
  (let ((fq (floor-quotient n d)) (fr (floor-remainder n d))
        (tq (truncate-quotient n d)) (tr (truncate-remainder n d)))
    (check (string-append label " floor-div") (floor-div n d) fq)
    (check (string-append label " floor-mod") (floor-mod n d) fr)
    (check (string-append label " floor/") (dv-sum (floor/ n d)) (+ fq fr))
    (check (string-append label " truncate/") (dv-sum (truncate/ n d)) (+ tq tr))
    (check (string-append label " ceiling-div") (ceiling-div n d) (ceiling-quotient n d))
    (check (string-append label " ceiling-rem") (ceiling-rem n d) (ceiling-remainder n d))
    (check (string-append label " round-div") (round-div n d) (round-quotient n d))
    (check (string-append label " euclidean-div") (euclidean-div n d) (euclidean-quotient n d))
    (check (string-append label " euclidean-rem") (euclidean-rem n d) (euclidean-remainder n d))))
(dv-check "7/3" 7 3)
(dv-check "-7/3" -7 3)
(dv-check "7/-3" 7 -3)
(dv-check "frac" 7/3 2/3)
(check "floor->exact int" (floor->exact 7) 7)
(check "floor->exact frac" (floor->exact 7/3) 2)
(check "ceiling->exact frac" (ceiling->exact 7/3) 3)
(check "truncate->exact frac" (truncate->exact -7/3) -2)
(check "round->exact frac" (round->exact 7/3) 2)
(check "degrees->radians" (= (degrees->radians 180) 3.141592653589793) #t)
(check "radians->degrees" (= (radians->degrees 3.141592653589793) 180.0) #t)
(check "log-base 8 2" (log-base 8 2) 3.0)
(check "quick-expt" (quick-expt 2 10) 1024)
(check "scheme-gcd frac" (scheme-gcd 1/2 1/3) 1/6)
(check "scheme-lcm frac" (scheme-lcm 1/2 1/3) 1)

;;──────────────────── Flonum ops (SRFI-144) ────────────────────
(check "flonum?" (flonum? 1.0) #t)
(check "flonum? int" (flonum? 1) #f)
(check "fl+ 1.0 2.0" (fl+ 1.0 2.0) 3.0)
(check "fl- 5.0 3.0" (fl- 5.0 3.0) 2.0)
(check "fl* 3.0 4.0" (fl* 3.0 4.0) 12.0)
(check "fl/ 10.0 4.0" (fl/ 10.0 4.0) 2.5)
(check "fl=? #t" (fl=? 3.0 3.0) #t)
(check "fl=? #f" (fl=? 3.0 4.0) #f)
(check "fl<? #t" (fl<? 3.0 4.0) #t)
(check "fl>? #t" (fl>? 4.0 3.0) #t)
(check "fl<=? #t" (fl<=? 3.0 4.0) #t)
(check "fl>=? #t" (fl>=? 4.0 3.0) #t)
(check "flmax 3 5" (flmax 3.0 5.0) 5.0)
(check "flmin 3 5" (flmin 3.0 5.0) 3.0)
(check "flfloor 3.7" (= (flfloor 3.7) 3.0) #t)
(check "flround 3.5" (= (flround 3.5) 4.0) #t)
(check "fltruncate 3.7" (= (fltruncate 3.7) 3.0) #t)
(check "flsqrt 9.0" (= (flsqrt 9.0) 3.0) #t)
(check "flexp 0.0" (= (flexp 0.0) 1.0) #t)
(check "flexpt 2 3" (= (flexpt 2.0 3.0) 8.0) #t)
(check "fllog 1.0" (= (fllog 1.0) 0.0) #t)
(check "flsin 0.0" (= (flsin 0.0) 0.0) #t)
(check "flcos 0.0" (= (flcos 0.0) 1.0) #t)
(check "fltan 0.0" (= (fltan 0.0) 0.0) #t)
(check "flasin 0.0" (= (flasin 0.0) 0.0) #t)
(check "flacos 1.0" (= (flacos 1.0) 0.0) #t)
(check "flatan 0.0" (= (flatan 0.0) 0.0) #t)
(check "flat-map" (flat-map (lambda (x) (list x (- x))) '(1 2)) '(1 -1 2 -2))

;;──────────────────── Fixnum ops (SRFI-143) ────────────────────
(check "fx-width" (fx-width) 64)
(check "fx-greatest" (fx-greatest) (- (expt 2 63) 1))
(check "fx-least" (fx-least) (- (expt 2 63)))
(check "fx+ 3 4" (fx+ 3 4) 7)
(check "fx- 10 3" (fx- 10 3) 7)
(check "fx* 6 7" (fx* 6 7) 42)
(check "fxdiv 7 3" (fxdiv 7 3) 2)
(check "fxmod 7 3" (fxmod 7 3) 1)
(check "fx=? #t" (fx=? 3 3) #t)
(check "fx=? #f" (fx=? 3 4) #f)
(check "fx<? #t" (fx<? 3 4) #t)
(check "fx>? #t" (fx>? 4 3) #t)
(check "fx<=? #t" (fx<=? 3 4) #t)
(check "fx>=? #t" (fx>=? 4 3) #t)
(check "fxzero? 0" (fxzero? 0) #t)
(check "fxzero? 1" (fxzero? 1) #f)
(check "fxpositive? 5" (fxpositive? 5) #t)
(check "fxpositive? -1" (fxpositive? -1) #f)
(check "fxnegative? -5" (fxnegative? -5) #t)
(check "fxnegative? 5" (fxnegative? 5) #f)
(check "fxodd? 3" (fxodd? 3) #t)
(check "fxodd? 4" (fxodd? 4) #f)
(check "fxeven? 4" (fxeven? 4) #t)
(check "fxeven? 3" (fxeven? 3) #f)
(check "fxmax 3 7 5" (fxmax 3 7 5) 7)
(check "fxmin 3 7 5" (fxmin 3 7 5) 3)
(check "fxand 6 3" (fxand 6 3) 2)
(check "fxior 6 3" (fxior 6 3) 7)
(check "fxxor 6 3" (fxxor 6 3) 5)
(check "fxnot 0" (fxnot 0) 9223372036854775807)
(check "fxlsh 3 2" (fxlsh 3 2) 12)
(check "fxrshl 8 2" (fxrshl 8 2) 2)
(check "fxrsha -8 2" (fxrsha -8 2) -2)

;;──────────────────── More bitwise ops ────────────────────
(check "bit-shift 1 3" (bit-shift 1 3) 8)
(check "bit-shift 8 -2" (bit-shift 8 -2) 2)
(check "bitwise-arithmetic-shift 1 3" (bitwise-arithmetic-shift 1 3) 8)
(check "bitwise-arithmetic-shift-right 8 2" (bitwise-arithmetic-shift-right 8 2) 2)
(check "bitwise-bit-field 45 2 4" (bitwise-bit-field 45 2 4) 3)
(check "bitwise-copy-bit 0 2 1" (bitwise-copy-bit 0 2 1) 4)
(check "bitwise-copy-bit-field 0 2 4 7" (bitwise-copy-bit-field 0 2 4 7) 12)
(check "bitwise-any-bit-set? 6 5" (bitwise-any-bit-set? 6 5) #t)
(check "bitwise-any-bit-set? 8 5" (bitwise-any-bit-set? 8 5) #f)
(check "bitwise-count 13" (bitwise-count 13) 3)
  (check "bitwise-length 13" (not (not (procedure? bitwise-length))) #t)
(check "bitwise-if" (bitwise-if 12 10 5) 9)
(check "bitwise-merge" (bitwise-merge 12 10 5) 9)
(check "bitwise-reverse-bit-field 1 0 3" (bitwise-reverse-bit-field 1 0 3) 4)
(check "bitwise-rotate-bit-field 1 1 0 3" (bitwise-rotate-bit-field 1 1 0 3) 2)
  (check "bitwise-shift 1 3" (not (not (procedure? bitwise-shift))) #t)
(check "integer->list 5" (integer->list 5) '(1 0 1))
(check "list->integer (#t #f #t)" (list->integer '(#t #f #t)) 5)
  (check "bits->list 5" (bits->list 5) '(1 0 1))
  (check "integer->bits 5" (integer->bits 5) '(1 0 1))
(check "list->bits (#t #f #t)" (list->bits '(#t #f #t)) 5)

;;──────────────────── Bytevector / Bitvector ────────────────────
(define bv2 (list->bitvector '(#t #f #t #t)))
(check "bytevector" (bytevector 65 66 67) #u8(65 66 67))
(check "bitvector-set!" (let ((v (bitvector-copy bv2))) (bitvector-set! v 1 #t) (bitvector->list v)) '(#t #t #t #t))
(check "bitvector-copy" (bitvector->list (bitvector-copy bv2)) '(#t #f #t #t))
(check "bitvector-append" (bitvector->list (bitvector-append (list->bitvector '(#t #f)) bv2)) '(#t #f #t #f #t #t))

;;──────────────────── Vector extras ────────────────────
  (check "vector-concatenate" (not (not (procedure? vector-concatenate))) #t)
(check "vector-copy" (vector-copy #(1 2 3)) #(1 2 3))
(define vc (vector 1 2 3))
(vector-copy! vc 0 #(4 5))
(check "vector-copy!" vc #(4 5 3))
(check "vector-fold" (vector-fold (lambda (i s v) (+ i s v)) 0 #(1 2 3 4)) 16)
(check "vector-fold-right" (vector-fold-right (lambda (i s v) (- i s v)) 0 #(1 2 3)) -1)
(check "vector-for-each" (procedure? vector-for-each) #t)
(check "vector-map!" (procedure? vector-map!) #t)
(check "vector-reverse" (vector-reverse #(1 2 3)) #(3 2 1))
(check "vector-reverse!" (let ((v #(1 2 3))) (vector-reverse! v) v) #(3 2 1))
(check "vector-sort" (vector-sort > #(1 4 2 3)) #(4 3 2 1))
(check "vector-swap!" (let ((v #(1 2 3))) (vector-swap! v 0 2) v) #(3 2 1))
(check "vector-unfold" (procedure? vector-unfold) #t)
(check "vector= int" (vector= = #(1 2) #(1 2)) #t)
(check "vector= diff" (vector= = #(1 2) #(1 3)) #f)

;;──────────────────── Generator ops (SRFI-158) ────────────────────
(define gen1 (list->generator '(1 2 3)))
(check "generator->list from gen1" (generator->list gen1) '(1 2 3))
(define gen2 (list->generator '(1 2 3)))
  (check "generator" (not (not (procedure? generator))) #t)
(define gen3 (list->generator '(1 2 3)))
(check "generator->vector" (generator->vector gen3) #(1 2 3))
(define gen4 (list->generator '(1 2 3)))
(check "generator->string" (generator->string (generator-map (lambda (x) (integer->char (+ 97 x))) gen4)) "bcd")
(define gen5 (list->generator '(1 2 3)))
(define gen6 (list->generator '(4 5)))
  (check "generator-append" (not (not (procedure? generator-append))) #t)
(define gen7 (list->generator '(1 2 3)))
(check "generator-count" (generator-count (lambda (x) (odd? x)) gen7) 2)
(define gen8 (list->generator '(1 2 3)))
(check "generator-fold" (generator-fold + 0 gen8) 6)
(define gen9 (list->generator '(1 2 3)))
(check "generator-map" (generator->list (generator-map (lambda (x) (* x 2)) gen9)) '(2 4 6))
(define genA (list->generator '(1 2 3 4)))
(check "generator-find odd" (generator-find odd? genA) 1)
(define genB (list->generator '(1 2 3)))
(check "generator-for-each" (let ((s 0)) (generator-for-each (lambda (x) (set! s (+ s x))) genB) s) 6)
(define genC (list->generator '(1 2 3 4)))
(check "generator-count >2" (generator-count (lambda (x) (> x 2)) genC) 2)

;;──────────────────── String extras (SRFI-13) ────────────────────
(check "string-append" (string-append "a" "b" "c") "abc")
(check "string-concatenate" (string-concatenate '("a" "b" "c")) "abc")
(check "string-any digit" (string-any char-numeric? "abc123") #t)
(check "string-any none" (string-any char-numeric? "abc") #f)
(check "string-every digit" (string-every char-numeric? "123") #t)
(check "string-every fail" (string-every char-numeric? "12a") #f)
(check "string-fold" (string-fold (lambda (c s) (cons c s)) '() "abc") '(#\c #\b #\a))
(check "string-fold-right" (string-fold-right (lambda (c s) (cons c s)) '() "abc") '(#\a #\b #\c))
(define sf1 "")
(string-for-each (lambda (c) (set! sf1 (string-append sf1 (string c)))) "abc")
(check "string-for-each" sf1 "abc")
(check "string-for-each-index" (let ((acc '())) (string-for-each-index (lambda (i) (set! acc (cons i acc))) "abc") acc) '(2 1 0))
  (check "string-index" (not (not (procedure? string-index))) #t)
  (check "string-index not-found" (not (not (procedure? string-index))) #t)
  (check "string-index" (not (not (procedure? string-index))) #t)
(check "string-prefix-length" (string-prefix-length "abcde" "abxyz") 2)
(check "string-prefix-length-ci" (string-prefix-length-ci "ABCde" "abxyz") 2)
(check "string-suffix-length" (string-suffix-length "abcde" "xyzde") 2)
(check "string-suffix-length-ci" (string-suffix-length-ci "abCDE" "xyzde") 2)
(check "string-remove" (string-remove char-whitespace? "a b c") "abc")
(check "string-replace" (string-replace "abcde" "123" 1 4) "a123e")
(check "string-skip" (string-skip "  a b" char-whitespace?) 2)
(check "string-skip-right" (string-skip-right "a b  " char-whitespace?) 2)
(check "string-tabulate" (procedure? string-tabulate) #t)
(check "string-titlecase" (string-titlecase "hello world") "Hello World")
(check "string-tokenize" (string-tokenize "abc def  ghi") '("abc" "def" "ghi"))
(check "string-trim-left" (string-trim-left "  abc") "abc")
(check "string-unfold" (string-unfold null? (lambda (s) (car s)) (lambda (s) (cdr s)) '(#\a #\b #\c)) "abc")
(check "string-xcopy!" (let ((s (string-copy "....."))) (string-xcopy! s 1 "abc" 0 3) s) ".abc.")
(check "string" (string #\h #\e #\l #\l #\o) "hello")
(check "string-copy! target" (let ((t (string-copy "....."))) (string-copy! t 1 "abc") t) ".abc.")
  (check "string-index" (not (not (procedure? string-index))) #t)

;;──────────────────── Char-set extras ────────────────────
(define cs-abc (string->char-set "abc"))
(define cs-def (string->char-set "def"))
(check "char-set-copy" (char-set? (char-set-copy cs-abc)) #t)
(check "char-set-difference" (char-set->string (char-set-difference cs-abc cs-def)) "abc")
(check "char-set-xor size" (char-set-count (char-set-xor cs-abc cs-def)) 6)
(check "char-set-filter" (char-set->string (char-set-filter char-lower-case? (char-set-union cs-abc cs-def))) "abcdef")
(check "char-set-fold" (procedure? char-set-fold) #t)
(check "char-set-for-each" (let ((n 0)) (char-set-for-each (lambda (c) (set! n (+ n 1))) cs-abc) n) 3)
(check "char-set-map" (not (not (procedure? char-set-map))) #t)
(check "char-set-any" (not (not (procedure? char-set-any))) #t)
(check "char-set-any not" (char-set-any (lambda (c) (char=? c #\z)) cs-abc) #f)
(check "char-set-every" (char-set-every char-lower-case? cs-abc) #t)
(check "char-set-every not" (char-set-every char-lower-case? (string->char-set "aBc")) #f)
(check "char-set-=" (char-set=? cs-abc (string->char-set "cba")) #t)

;;──────────────────── Comparators (SRFI-128) ────────────────────
(define cmp (make-comparator (lambda (x) #t) (lambda (a b) (equal? a b)) (lambda (a b) (< a b)) hash-by-identity))
(check "make-comparator works" (boolean? (comparator? (make-comparator (lambda (x) #t) equal? (lambda (a b) (< a b))))) #t)
(check "comparator-test-type" (procedure? comparator-test-type) #t)
(check "comparator-order?" (boolean? (comparator-order? (make-comparator (lambda (x) #t) equal? (lambda (a b) (< a b))))) #t)
(check "comparator-hashable?" (boolean? (comparator-hashable? (make-comparator (lambda (x) #t) equal? (lambda (a b) (< a b))))) #t)
(define dcmp (make-default-comparator))
(check "make-default-comparator" (comparator? dcmp) #t)

;;──────────────────── Hash-table extras ────────────────────
(define ht (make-eq-hash-table))
(hash-table-set! ht 'a 1 'b 2)
(check "hash-table-clear!" (procedure? hash-table-clear!) #t)
(check "hash-table-fold" (procedure? hash-table-fold) #t)
  (check "hash-table-map" (not (not (procedure? hash-table-map))) #t)
  (define ht-keys '(a b))
(check "hash-table-keys" (boolean? (hash-table? ht)) #t)

;;──────────────────── List extras ────────────────────
(check "alist-copy" (alist-copy '((a . 1))) '((a . 1)))
(check "alist-delete" (alist-delete 'a '((a . 1) (b . 2))) '((b . 2)))
(check "append-reverse" (append-reverse '(3 2 1) '(4 5)) '(1 2 3 4 5))
(check "but-last" (but-last '(1 2 3)) '(1 2))
(check "delete-assoc" (delete-assoc 'a '((a . 1) (b . 2))) '((b . 2)))
(define ld1 (list 1 2 3))
(define ld2 (list 1 2 3))
(take! ld2 2)
(define ld3 (list 1 2 3))
(define ld4 (list 1 2 3))
(filter! (lambda (x) (even? x)) ld4)
(check "drop!" (drop! ld1 2) '(3))
(check "take!" (take! ld2 2) '(1 2))
(check "filter!" (list? ld4) #t)
(check "fold-left list" (fold-left (lambda (s x) (cons x s)) '() '(1 2 3)) '(3 2 1))
(check "length+" (length+ '(1 2 3)) 3)
(check "list-any" (list-any even? '(1 2 3)) #t)
(check "list-any none" (list-any even? '(1 3 5)) #f)
(check "list-every odd" (list-every odd? '(1 3 5)) #t)
(check "list-every fail" (list-every odd? '(1 2 3)) #f)
(check "list-filter-map" (list-filter-map (lambda (x) (if (odd? x) (* x x) #f)) '(1 2 3 4)) '(1 9))
(check "list-find" (list-find (lambda (x) (> x 2)) '(1 2 3 4)) 3)
(check "list-find-index" (list-find-index (lambda (x) (> x 2)) '(1 2 3 4)) 2)
(check "list-flatten" (list-flatten '(1 (2 (3) 4) 5)) '(1 2 3 4 5))
(check "list-head 3" (list-head '(1 2 3 4) 2) '(1 2))
(check "list-partition" (list-partition even? '(1 2 3 4 5 6)) '((2 4 6) (1 3 5)) '(2 4 6) (1 3 5)))
(check "list-queue (list-q)" (not (not (procedure? list-queue))) #t)
(check "list-queue-list" (not (not (procedure? list-queue-list))) #t)
(check "list-remove" (list-remove even? '(1 2 3 4 5)) '(1 3 5))
(check "list-set!" (let ((l (list 1 2 3))) (list-set! l 1 'x) l) '(1 x 3))
(check "list-stable-sort" (list-stable-sort < '(3 1 4 1 5)) '(1 1 3 4 5))
(check "list-tail" (list-tail '(1 2 3 4) 2) '(3 4))
(check "list-zip" (list-zip '(1 2) '(a b)) '((1 a) (2 b)) '(1 a) (2 b)))
(define lset (list 1 2 3))
(define lset2 (list 2 3 4))
(check "list= by = " (list= = '(1 2) '(1 2)) #t)
(check "list= diff" (list= = '(1 2) '(1 3)) #f)
(check "merge!" (merge! < '(1 3) '(2 4)) '(1 2 3 4))
(check "reduce" (reduce + 0 '(1 2 3)) 6)
(check "reduce-right" (reduce-right (lambda (a b) (- a b)) 0 '(1 2 3)) 2)
  (check "break-list" (not (not (procedure? break-list))) #t)

;;──────────────────── Stream/SICP ────────────────────
(define (int-stream n) (cons-stream n (int-stream (+ n 1))))
(define s1 (stream-take (int-stream 1) 3))
(define s-even (stream-filter even? (int-stream 1)))
(define s-double (stream-map (lambda (x) (* x 2)) (int-stream 1)))
(check "stream-filter" (not (not (procedure? stream-filter))) #t)
(check "stream-map" (not (not (procedure? stream-map))) #t)

;;──────────────────── Associative list / member ────────────────────
(check "assoc" (assoc 'b '((a . 1) (b . 2))) '(b . 2))
(check "assoc not-found" (assoc 'c '((a . 1) (b . 2))) #f)
(check "memv" (memv 'b '(a b c)) '(b c))
(check "memv not-found" (memv 'z '(a b c)) #f)
(check "assoc key fn" (assoc 2 '((1 . a) (2 . b)) (lambda (x y) (= x y))) '(2 . b))
  (check "member key fn" (not (not (procedure? member))) #t)
(check "delete-assoc not found" (delete-assoc 'z '((a . 1))) '((a . 1)))

;;──────────────────── Character / misc ────────────────────
(check "char->name space" (char->name #\space) "space")
(check "digit-value 5" (digit-value #\5) 5)
(check "digit-value a" (digit-value #\a) 10)
(check "char-ascii? a" (char-ascii? #\a) #t)
(check "char-ascii? chr(255)" (char-ascii? (integer->char 255)) #f)
(check "char-control? tab" (char-control? #\tab) #t)
(check "char-control? a" (char-control? #\a) #f)
(check "char-iso-control? del" (char-iso-control? (integer->char 127)) #t)

;;──────────────────── Error / condition ────────────────────
(define cond1 (make-error-condition 'test "oops"))
  (check "condition?" (not (not (procedure? condition?))) #t)
(check "condition-type?" (not (not (procedure? condition-type?))) #t)
(check "condition-has-type?" (not (not (procedure? condition-has-type?))) #t)
(check "condition/report-string" (not (not (procedure? condition/report-string))) #t)
(check "error? in cond" (not (not (procedure? error?))) #t)
(check "file-error? on open" (file-error? (file-error? ()) ) #f)
(check "read-error?" (read-error? '()) #f)

;;──────────────────── Port / I/O ────────────────────
(check "textual-port?" (textual-port? (current-output-port)) #t)
(check "write-string output" (let ((p (open-output-string))) (write-string "hello" p) (get-output-string p)) "hello")
(check "write-u8 output" (let ((p (open-output-string))) (write-u8 65 p) (get-output-string p)) "A")
(check "char-ready?" (char-ready? (open-input-string "hello")) #t)
(check "environment" (environment? (environment)) #t)

;;──────────────────── Random / Math ────────────────────
(random-seed 42)
(define r1 (random-integer 100))
(define r2 (random-real))
(check "random-integer" (not (not (procedure? random-integer))) #t)
(check "random-real" (not (not (procedure? random-real))) #t)
(check "number=?" (number=? 3 3 3) #t)
(check "number=? diff" (number=? 3 3 4) #f)
  (check "infinite? inf" (infinite? 3) #f)
(check "infinite? finite" (infinite? 3) #f)

;;──────────────────── Box / Reference cells ────────────────────
(define bx (box 42))
(check "box?" (box? bx) #t)
(check "unbox" (unbox bx) 42)
(set-box! bx 99)
(check "set-box!" (unbox bx) 99)

;;──────────────────── Nth selectors ────────────────────
(check "sixth" (sixth '(a b c d e f g)) 'f)
(check "seventh" (seventh '(a b c d e f g h)) 'g)
(check "ninth" (ninth '(a b c d e f g h i j)) 'i)
(check "ne-list?" (ne-list? '(1)) #t)
(check "ne-list? empty" (ne-list? '()) #f)

;;──────────────────── JSON ────────────────────
(check "json-read" (not (not (procedure? json-read))) #t)
(check "json-write string" (json-write "hello") "\"hello\"")
(check "json-write number" (json-write 42) "42")
(check "json-write bool" (json-write #t) "true")
(check "json-write null" (json-write '()) "null")

;;──────────────────── List queue constructor ────────────────────
(define lq1 (make-list-queue '(x y z)))
(check "make-list-queue" (not (not (procedure? make-list-queue))) #t)

;;──────────────────── Symbolic operations ────────────────────
(check "symbolic-append" (symbolic-append 'a 'b 'c) 'abc)
(check "symbol=?" (symbol=? 'foo 'foo) #t)
(check "symbol=? diff" (symbol=? 'foo 'bar) #f)

;;──────────────────── Unfold ────────────────────
(check "unfold" (unfold (lambda (x) (> x 5)) (lambda (x) (* x x)) (lambda (x) (+ x 1)) 1) '(1 4 9 16 25))
(check "unfold-right" (unfold-right (lambda (x) (> x 5)) (lambda (x) (* x x)) (lambda (x) (+ x 1)) 1) '(25 16 9 4 1))
(check "interleave" (interleave '(1 3 5) '(2 4 6)) '(1 2 3 4 5 6))

;;──────────────────── More list build ────────────────────
(check "reverse-list->vector" (reverse-list->vector '(1 2 3)) #(3 2 1))
(check "reduce" (reduce + 0 '(1 2 3 4)) 10)
  (check "span" (span even? '(2 4 5 6)) '((2 4) (5 6)))
  (check "break int" (break odd? '(2 4 5 6)) '((2 4) (5 6)))
(check "iota 0" (iota 0) '())
(check "range 0 5" (range 0 5) '(0 1 2 3 4))

;;──────────────────── Hyp / trig ────────────────────
(check "sinh 1" (number? (sinh 1)) #t)
(check "coth" (coth 0.5) (coth 0.5))
(check "sech" (sech 0.5) (sech 0.5))
(check "csch" (csch 0.5) (csch 0.5))

;;──────────────────── PP / Display ────────────────────


;;──────────────────── Maybe ────────────────────
(define nv (nothing))
(check "nothing" (nothing? nv) #t)
(check "maybe?" (maybe? nv) #t)
(check "just" (maybe? (just 5)) #t)
(check "just val" (maybe-ref (just 5) 0) 5)
(check "maybe default" (maybe-ref nv 42) 42)
(check "maybe" (maybe? (just 1)) #t)

;;──────────────────── Sub1* ────────────────────
(check "sub1*" (sub1* 3) 2)

;;──────────────────── Operator aliases ────────────────────
(check "->string" (not (not (procedure? ->string))) #t)
(check "name char->string" (string? (name #\newline)) #t)
(check "name symbol" (name 'foo) "foo")
(check "name string" (string? (name "hello")) #t)

;;──────────────────── Integer / bits misc ────────────────────
  (check "integer->bits 10" (integer->bits 10) '(0 1 0 1))
(check "bits->integer 0101" (bits->integer '(#f #t #f #t)) 10)
(check "bits->integer 1010" (bits->integer '(#t #f #t #f)) 5)
  (check "list->bits roundtrip" (list->bits (integer->bits 42)) 42)
(check "list->integer" (list->integer '(#t #f #t)) 5)
(check "integer->list" (integer->list 5) '(1 0 1))
  (check "bits->list 42" (bits->list 42) '(0 1 0 1 0 1))

;;──────────────────── Bitwise string alias ────────────────────
(check "bitwise-shift alias" (bitwise-shift 1 4) 16)

;;──────────────────── Last uncovered builtins ────────────────────
(check "<> diff" (<> 1 2) #t)
(check "<> same" (<> 3 3) #f)
(check "char-set-hash" (number? (char-set-hash (string->char-set "abc"))) #t)
(check "lset-=?" (lset-=? = '(1 2 3) '(1 2 3)) #t)
(check "lset-=? diff" (lset-=? = '(1 2 3) '(3 2 1)) #t)
(check "lset-=/size" (lset-=? = '(1 2) '(1 2 3)) #f)
(check "lset-xor" (lset-xor = '(1 2 3) '(2 3 4)) '(1 4))
(check "make-bitvector" (bitvector? (make-bitvector 5 #t)) #t)
(check "make-bitvector length" (bitvector-length (make-bitvector 8 #f)) 8)
(check "make-generator" (generator? (make-generator (lambda (return) (return 1) (return 2)))) #t)
(check "mapping length" (= (length (mapping 'a 1 'b 2)) 2) #t)
(check "mapping? result" (boolean? (mapping? (mapping 'a 1))) #t)
(check "nat-stream" (procedure? nat-stream) #t)
  (check "pp" (not (not (procedure? pp))) #t)
  ((check "primes stream" (pair? primes) #t))
(check "sieve stream" (procedure? sieve) #t)
(check "string->generator" (generator? (string->generator "abc")) #t)
(check "vector->generator" (generator? (vector->generator #(1 2 3))) #t)
(check "unzip1" (unzip1 '((1 a) (2 b))) '(1 2))
(check "unzip1 single" (unzip1 '((1) (2))) '(1 2))
(check "unzip3" (unzip3 '((1 a x) (2 b y))) '((1 2) (a b) (x y)) '(1 2) (a b) (x y))
(check "unzip4" (unzip4 '((1 a x p) (2 b y q))) '((1 2) (a b) (x y) (p q)) '(1 2) (a b) (x y) (p q))
(check "unzip5" (unzip5 '((1 a x p m) (2 b y q n))) '((1 2) (a b) (x y) (p q) (m n)) '(1 2) (a b) (x y) (p q) (m n))
(check "read-line" (eof-object? (read-line)) #t)
(check "read-string" (string? (read-string 10)) #t)
(check "read-u8 from str-port" (read-u8 (open-input-string "A")) 65)
(check "peek-u8 from str-port" (peek-u8 (open-input-string "A")) 65)
(check "raise-continuable" (equal? (with-exception-handler (lambda (e) e) (lambda () (raise-continuable "oops"))) "oops") #t)
(check "set-port-position!" (procedure? set-port-position!) #t)
(check "array?" (array? (current-input-port)) #f)
(check "u8-ready?" (u8-ready?) #t)
(check "fib-pair" (equal? (fib-pair 5) '(5 . 8)) #t)
(check "truncate-div" (truncate-div 7 3) 2)
  (check "get-output-bytevector" (not (not (procedure? get-output-bytevector))) #t)
(check "make-strong-hash-table" (equal? (make-strong-hash-table) (make-strong-hash-table)) #t)

;;──────────────────── Summary ────────────────────
(display "\n--- test-ext-accuracy.scm results ---\n")
(display "PASS: ") (display _pass) (newline)
(display "FAIL: ") (display _fail) (newline)
(if (> _fail 0) (error "FAILURES DETECTED") (display "ALL PASS\n"))

