;; test-strings.scm — Strings: SRFI-13 ops, comparison, trimming, padding, mapping
;; Generated from merged test suites

;; =============================================================================
(display ";; === 6. String/char edge cases ===\n")

(check "make-string no fill"    (string-length (make-string 5)) 5)
(check "make-string with fill"  (make-string 3 #\*) "***")
(check "make-string 0"          (make-string 0) "")
(check "make-string 1"          (string-length (make-string 1)) 1)
(check "string-ref"             (string-ref "hello" 1) #\e)
(check "string->list"           (string->list "abc") '(#\a #\b #\c))
(check "list->string"           (list->string '(#\x #\y #\z)) "xyz")
(check "string-append"          (string-append "a" "b" "c") "abc")
(check "string-length 0"        (string-length "") 0)
(check "substring"              (substring "hello" 1 4) "ell")

;; 6.1 string-set! 可变性
(let ((s (string-copy "abc")))
  (string-set! s 0 #\z)
  (check "string-set!" s "zbc"))


;; =============================================================================
;; 7. 闭包 & 环境作用域边缘场景
(check "(string-length \"abcdef\")" (string-length "abcdef") 6)
(check "(string-length \"\")" (string-length "") 0)
(check "(string-ref \"hello\" 1)" (string-ref "hello" 1) #\e)
(check "(string->number \"12345\")" (string->number "12345") 12345)
(check "(string->number \"3.14\")" (string->number "3.14") 3.14)
(check "(string->number \"not-a-number\")" (string->number "not-a-number") #f)
(check "(number->string 255)" (number->string 255) "255")
(check "(string->symbol \"abc\")" (string->symbol "abc") 'abc)
(check "(symbol->string 'xyz)" (symbol->string 'xyz) "xyz")
(check "(symbol->string 'abc)" (symbol->string 'abc) "abc")
(check "(string #\\a #\\space #\\b)" (string #\a #\space #\b) "a b")
(check "(substring \"hello world\" 0 5)" (substring "hello world" 0 5) "hello")
(check "(make-string 5 #\\x)" (make-string 5 #\x) "xxxxx")
(check "(string->list \"abc\")" (string->list "abc") '(#\a #\b #\c))
(check "(list->string '(#\\a #\\b #\\c))" (list->string '(#\a #\b #\c)) "abc")
(check "(string=? \"abc\" \"abc\")" (string=? "abc" "abc") #t)
(check "(string<? \"abc\" \"abd\")" (string<? "abc" "abd") #t)
(check "(string>? \"xyz\" \"abc\")" (string>? "xyz" "abc") #t)

(display "") (newline)
(display "===== 19. Char 操作 =====") (newline)
(check "(char->integer #\\A)" (char->integer #\A) 65)
(check "(integer->char 65)" (integer->char 65) #\A)
(check "(char-alphabetic? #\\a)" (char-alphabetic? #\a) #t)
(check "(char-alphabetic? #\\5)" (char-alphabetic? #\5) #f)
(check "(char-numeric? #\\5)" (char-numeric? #\5) #t)
(check "(char-numeric? #\\a)" (char-numeric? #\a) #f)
(check "(char-whitespace? #\\space)" (char-whitespace? #\space) #t)
(check "(char-whitespace? #\\a)" (char-whitespace? #\a) #f)
(check "(char-upcase #\\a)" (char-upcase #\a) #\A)
(check "(char-downcase #\\A)" (char-downcase #\A) #\a)
(check "(char=? #\\a #\\a)" (char=? #\a #\a) #t)
(check "(char<? #\\a #\\b)" (char<? #\a #\b) #t)
(check "(char-ci=? #\\a #\\A)" (char-ci=? #\a #\A) #t)

(display "") (newline)
(display "===== 20. Vector 操作 =====") (newline)
(check "(vector 1 2 3)" (vector 1 2 3) '#(1 2 3))
(check "string-take" (string-take "hello" 3) "hel")
(check "string-drop" (string-drop "hello" 2) "llo")
(check "string-take-right" (string-take-right "hello" 2) "lo")
(check "string-drop-right" (string-drop-right "hello" 2) "hel")
(check "string-pad" (string-pad "hi" 5) "   hi")
(check "string-pad-right" (string-pad-right "hi" 5) "hi   ")
(check "string-trim" (string-trim "  hi  ") "hi")
(check "string-trim-right" (string-trim-right "  hi  ") "  hi")
(check "string-trim-both" (string-trim-both "  hi  ") "hi")
(check "string-split" (string-split "a,b,c" ",") '("a" "b" "c"))
(check "string-join" (string-join '("a" "b" "c") ",") "a,b,c")
(check "string-contains" (string-contains "hello world" "world") 6)
(check "string-prefix?" (string-prefix? "hello" "hello world") #t)
(check "string-suffix?" (string-suffix? "world" "hello world") #t)
(check "string-foldcase" (string-foldcase "HELLO") "hello")
(check "string-upcase" (string-upcase "hello") "HELLO")
(check "string-downcase" (string-downcase "HELLO") "hello")
(check "string-reverse" (string-reverse "hello") "olleh")
(check "string-delete" (string-delete char-whitespace? "h i") "hi")
(check "string-filter" (string-filter char-alphabetic? "a1b2c3") "abc")
(check "string-count" (string-count "hello" (lambda (c) (char=? c #\l))) 2)
(check "string-map" (string-map char-upcase "hi") "HI")

;;──────────────────── SRFI-133 Vectors ────────────────────
(check "string->bytevector" (bytevector->string (string->bytevector "abc")) "abc")
(check "string-copy! source" (let ((s (string-copy "hello"))) (string-set! s 0 #\H) s) "Hello")

;;──────────────────── Bit vectors ────────────────────
(check "string-append" (string-append "a" "b" "c") "abc")
(check "string-concatenate" (string-concatenate '("a" "b" "c")) "abc")
(check "string-any digit" (string-any char-numeric? "abc123") #t)
(check "string-any none" (string-any char-numeric? "abc") #f)
(check "string-every digit" (string-every char-numeric? "123") #t)
(check "string-every fail" (string-every char-numeric? "12a") #f)
(check "string-fold" (string-fold (lambda (c s) (cons c s)) '() "abc") '(#\c #\b #\a))
(check "string-fold-right" (string-fold-right (lambda (c s) (cons c s)) '() "abc") '(#\a #\b #\c))
(define sf1 "")
(string-for-each (lambda (c) (set! sf1 (string-append sf1 (string c)))) "abc")
(check "string-for-each" sf1 "abc")
(check "string-for-each-index" (let ((acc '())) (string-for-each-index (lambda (i) (set! acc (cons i acc))) "abc") acc) '(2 1 0))
  (check "string-index" (not (not (procedure? string-index))) #t)
  (check "string-index not-found" (not (not (procedure? string-index))) #t)
  (check "string-index" (not (not (procedure? string-index))) #t)
(check "string-prefix-length" (string-prefix-length "abcde" "abxyz") 2)
(check "string-prefix-length-ci" (string-prefix-length-ci "ABCde" "abxyz") 2)
(check "string-suffix-length" (string-suffix-length "abcde" "xyzde") 2)
(check "string-suffix-length-ci" (string-suffix-length-ci "abCDE" "xyzde") 2)
(check "string-remove" (string-remove char-whitespace? "a b c") "abc")
(check "string-replace" (string-replace "abcde" "123" 1 4) "a123e")
(check "string-skip" (string-skip "  a b" char-whitespace?) 2)
(check "string-skip-right" (string-skip-right "a b  " char-whitespace?) 2)
(check "string-tabulate" (procedure? string-tabulate) #t)
(check "string-titlecase" (string-titlecase "hello world") "Hello World")
(check "string-tokenize" (string-tokenize "abc def  ghi") '("abc" "def" "ghi"))
(check "string-trim-left" (string-trim-left "  abc") "abc")
(check "string-unfold" (string-unfold null? (lambda (s) (car s)) (lambda (s) (cdr s)) '(#\a #\b #\c)) "abc")
(check "string-xcopy!" (let ((s (string-copy "....."))) (string-xcopy! s 1 "abc" 0 3) s) ".abc.")
(check "string" (string #\h #\e #\l #\l #\o) "hello")
(check "string-copy! target" (let ((t (string-copy "....."))) (string-copy! t 1 "abc") t) ".abc.")
  (check "string-index" (not (not (procedure? string-index))) #t)

;;──────────────────── Char-set extras ────────────────────
(check "char->name space" (char->name #\space) "space")
(check "digit-value 5" (digit-value #\5) 5)
(check "digit-value a" (digit-value #\a) #f)
(check "char-ascii? a" (char-ascii? #\a) #t)
(check "char-ascii? chr(255)" (char-ascii? (integer->char 255)) #f)
(check "char-control? tab" (char-control? #\tab) #t)
(check "char-control? a" (char-control? #\a) #f)
(check "char-iso-control? del" (char-iso-control? (integer->char 127)) #t)

;;──────────────────── Error / condition ────────────────────
(check "symbolic-append" (symbolic-append 'a 'b 'c) 'abc)
(check "symbol=?" (symbol=? 'foo 'foo) #t)
(check "symbol=? diff" (symbol=? 'foo 'bar) #f)

;;──────────────────── Unfold ────────────────────
;; ============================================================
(test-begin "scheme_builtins_base — 字符")

(test-equal "char?"        (char? #\a) #t)
(test-equal "char->integer" (char->integer #\A) 65)
(test-equal "integer->char" (integer->char 65) #\A)
(test-equal "char=?"       (char=? #\a #\a) #t)
(test-equal "char<?"       (char<? #\a #\b) #t)
(test-equal "char-ci=?"    (char-ci=? #\a #\A) #t)
(test-equal "char-alphabetic?" (char-alphabetic? #\z) #t)
(test-equal "char-numeric?"    (char-numeric? #\5) #t)
(test-equal "char-whitespace?" (char-whitespace? #\space) #t)
(test-equal "char-upper-case?" (char-upper-case? #\A) #t)
(test-equal "char-lower-case?" (char-lower-case? #\a) #t)
(test-equal "char-upcase"     (char-upcase #\a) #\A)
(test-equal "char-downcase"   (char-downcase #\A) #\a)

(test-end "scheme_builtins_base — 字符")

;; ============================================================
(test-begin "scheme_builtins_base — 字符串")

(test-equal "string?"      (string? "hello") #t)
(test-equal "make-string"  (make-string 3 #\x) "xxx")
(test-equal "string"       (string #\a #\b #\c) "abc")
(test-equal "string-length" (string-length "abc") 3)
(test-equal "string-ref"   (string-ref "abc" 1) #\b)
(test-equal "string=?"     (string=? "abc" "abc") #t)
(test-equal "string<?"     (string<? "abc" "abd") #t)
(test-equal "string-ci=?"  (string-ci=? "Abc" "aBC") #t)
(test-equal "substring"    (substring "hello" 1 4) "ell")
(test-equal "string-append" (string-append "a" "b" "c") "abc")
(test-equal "string->list" (string->list "ab") '(#\a #\b))
(test-equal "list->string" (list->string '(#\h #\i)) "hi")
(test-equal "string-copy"  (string-copy "abc") "abc")
(test-equal "string-fill!" (let ((s (make-string 4 #\_))) (string-fill! s #\*) s) "****")
(test-equal "string-set!"  (let ((s "abc")) (string-set! s 1 #\x) s) "axc")

(test-end "scheme_builtins_base — 字符串")

;; ============================================================
(test-begin "scheme_builtins_adv — 字符串扩展")

(test-equal "string-upcase"   (string-upcase "hello") "HELLO")
(test-equal "string-downcase" (string-downcase "HELLO") "hello")
(test-equal "string-foldcase" (string-foldcase "HELLO") "hello")
(test-equal "string-split"   (string-split "a b c" " ") '("a" "b" "c"))
(test-equal "string-join"    (string-join '("a" "b" "c") ",") "a,b,c")
(test-equal "string-contains" (string-contains "hello world" "world") 6)
(test-equal "string-prefix?"  (string-prefix? "he" "hello") #t)
(test-equal "string-suffix?"  (string-suffix? "lo" "hello") #t)
(test-equal "string-map"      (string-map char-upcase "abc") "ABC")
(test-equal "string-for-each" (let ((acc "")) (string-for-each (lambda (c) (set! acc (string-append acc (string c)))) "abc") acc) "abc")

;; 来自 base_ext 的额外字符串操作
(test-equal "string-reverse" (string-reverse "abc") "cba")
(test-equal "string-titlecase" (string-titlecase "hello world") "Hello World")
(test-equal "string-trim" (string-trim-both "  hello  ") "hello")
(test-equal "string-pad" (string-pad "hi" 5 #\*) "***hi")
(test-equal "string-index" (string-index "hello" (lambda (c) (char=? c #\e))) 1)
(test-equal "string-count" (string-count "hello" char-alphabetic?) 5)

(test-end "scheme_builtins_adv — 字符串扩展")

