;; Verify all 40+ special forms still work after dispatch refactoring
(display "=== 核心特殊形式 ===\n")

(display "quote: ") (display (quote (1 2 3))) (newline)
(display "if true: ") (display (if #t "yes" "no")) (newline)
(display "if false: ") (display (if #f "yes" "no")) (newline)
(display "if no else: ") (display (if #f 42)) (newline)
(display "begin: ") (display (begin (+ 1 2) (- 5 3))) (newline)
(display "lambda: ") (display ((lambda (x) (* x 2)) 5)) (newline)
(display "define: ") (define _x 42) (display _x) (newline)
(display "set!: ") (set! _x 99) (display _x) (newline)
(display "quasiquote: ") (display `(1 ,(+ 1 2) 3)) (newline)
(display "cond: ") (display (cond ((> 3 2) "big") (else "small"))) (newline)
(display "case: ") (display (case 2 ((1) "one") ((2) "two"))) (newline)
(display "and: ") (display (and 1 2 3)) (newline)
(display "or: ") (display (or #f #f 42)) (newline)
(display "when: ") (display (when #t 10)) (newline)
(display "unless: ") (display (unless #f 20)) (newline)
(display "let: ") (display (let ((x 5)) (+ x 3))) (newline)
(display "let*: ") (display (let* ((x 3) (y (* x 2))) y)) (newline)
(display "letrec fact: ") (display (letrec ((f (lambda (n) (if (< n 2) 1 (* n (f (- n 1))))))) (f 5))) (newline)
(display "do: ") (do ((i 0 (+ i 1))) ((= i 3) (quote done)) (display i) (display " ")) (newline)
(display "delay/force: ") (display (force (delay (+ 2 3)))) (newline)
(display "call/cc: ") (display (call/cc (lambda (k) (k 42)))) (newline)
(display "call-with-values: ") (display (call-with-values (lambda () (values 10 20)) (lambda (a b) (+ a b)))) (newline)
(display "define-values: ") (define-values (a b) (values 1 2)) (display a) (display b) (newline)
(display "define-syntax: ") 
  (define-syntax my-when (syntax-rules () ((_ test body ...) (if test (begin body ...)))))
  (display (my-when #t 42)) (newline)
(display "let-syntax: ") 
  (let-syntax ((twice (syntax-rules () ((_ x) (* 2 x)))))
    (display (twice 5)) (newline))
(display "case-lambda: ") 
  (display ((case-lambda ((a) (* a a)) ((a b) (+ a b))) 3)) (newline)
(display "parameterize: ")
  (define p (make-parameter 0))
  (parameterize ((p 5)) (display (p))) (display " outside: ") (display (p)) (newline)
(display "guard: ")
  (guard (e ((error-object? e) (display "caught"))) (error "oh no")) (newline)
(display "receive: ") (display (receive (a b) (values 1 2) (+ a b))) (newline)
(display "dynamic-wind: ") (display (dynamic-wind (lambda () 'before) (lambda () 77) (lambda () 'after))) (newline)
(display "=== ALL 38 SPECIAL FORMS PASSED ===\n")
