(define wind-trace '())
(define (wind-test)
  (set! wind-trace '())
  (call/cc (lambda (k)
    (dynamic-wind
      (lambda () (set! wind-trace (cons 'before wind-trace)))
      (lambda () (k 42))
      (lambda () (set! wind-trace (cons 'after wind-trace)))))))
(check "wind-test result" (wind-test) 42)
(check "wind-test before" (car wind-trace) 'after)
(check "wind-test after" (cadr wind-trace) 'before)